// SPDX-License-Identifier: Apache-2.0
//! `metal_cost_sweep` — the calibration entrypoint for Apple Silicon GPUs.
//!
//! Emits `kernel,M,N,K,cost_us` rows to stdout. Pipe into
//! `crates/ferrite-metal-targets/profiles/cost_<chip>.csv` so the
//! ferrite solver's `CostTable` can score the calibrated kernels per
//! workload.
//!
//! Sweep families:
//!   1. [`rmsnorm_sweep`] — RMSNorm placeholder rows kept for binary
//!      compat (see the module docstring; rows are unused by the
//!      solver due to a naming convention mismatch).
//!   2. [`affine_qmv_sweep`] — int4 GEMV (qmv_quad / qmv_fast / qmv)
//!      across decode-shape `(M=1, N, K)` covering every mlx-community
//!      4bit Llama / Qwen / Gemma checkpoint.
//!   3. [`affine_qmm_sweep`] — int4 GEMM (qmm_t / qmm_t_splitk) across
//!      prefill-shape `(M, N, K)` for the same shape set.
//!
//! Usage:
//!   cargo run -p ferrite-metal-cost-sweep --release \
//!     --bin metal_cost_sweep \
//!     > crates/ferrite-metal-targets/profiles/cost_<chip>.csv
//!
//! The CSV format matches CUDA's stable format (`kernel,M,N,K,cost_us`)
//! and is consumed by
//! `ferrite_metal_targets::MetalTargetProfile::load_costs_from_csv`.

mod affine_qmm_sweep;
mod affine_qmv_sweep;
mod attention_sweep;
mod rmsnorm_sweep;
mod synth_mlp_pre_down_sweep;
mod synth_pre_attn_sweep;
mod util;

fn main() {
    util::init_metal();

    let launch_overhead_us = util::measure_launch_overhead();

    println!("# Metal GPU cost table — generated by metal_cost_sweep");
    println!("# Device: {}", util::device_name());
    println!("# Launch overhead: {launch_overhead_us:.2} us (subtracted from all timings)");
    println!("# Timings are compute-only. To get wall-clock time for N separate");
    println!("# kernel launches, add N * launch_overhead_us.");
    println!("# Regenerate: cargo run -p ferrite-metal-cost-sweep --release");
    println!("kernel,M,N,K,cost_us");
    println!("launch_overhead,0,0,0,{launch_overhead_us:.2}");

    // Optional filter — `FERRITE_SWEEP=synth_pre_attn` etc. — useful
    // when iterating on a single sweep family without paying for the
    // ~4-min full table regen.
    let filter = std::env::var("FERRITE_SWEEP").ok();
    let want = |name: &str| filter.as_deref().map_or(true, |f| f.split(',').any(|s| s == name));
    if want("rmsnorm") {
        rmsnorm_sweep::run(launch_overhead_us);
    }
    if want("affine_qmv") {
        affine_qmv_sweep::run(launch_overhead_us);
    }
    if want("affine_qmm") {
        affine_qmm_sweep::run(launch_overhead_us);
    }
    if want("synth_pre_attn") {
        synth_pre_attn_sweep::run(launch_overhead_us);
    }
    if want("synth_mlp_pre_down") {
        synth_mlp_pre_down_sweep::run(launch_overhead_us);
    }
    if want("attention") {
        attention_sweep::run(launch_overhead_us);
    }

    eprintln!("metal_cost_sweep: done");
}
