// SPDX-License-Identifier: Apache-2.0
//! `metal_cost_sweep` — the calibration entrypoint for Apple Silicon GPUs.
//!
//! Emits `kernel,M,N,K,cost_us` rows to stdout. Pipe into
//! `target_profiles/cost_<chip>.csv` so the ferrite solver's
//! `CostTable` can score the calibrated kernels per workload.
//!
//! Sweep families:
//!   1. [`rmsnorm_sweep`] — RMSNorm F16/BF16 across shape ranges
//!      covering typical hidden_size values (2048-8192) and
//!      sequence lengths (1-8192 tokens).
//!   2. Future: attention, GEMM via MPS, etc.
//!
//! Usage:
//!   cargo run -p ferrite-metal-cost-sweep --release \
//!     --bin metal_cost_sweep \
//!     > target_profiles/cost_m1_max.csv
//!
//! The CSV format matches CUDA's stable format (`kernel,M,N,K,cost_us`)
//! and is consumed by `ferrite_forward_macro::target::CostTable::load_csv`.

mod rmsnorm_sweep;
mod util;

fn main() {
    util::init_metal();

    // Determine launch-overhead baseline by timing a no-op command buffer.
    // All subsequent timings subtract this so each row reports
    // compute-only cost — matches the convention the CSV header
    // documents and the solver's `cost_us_for` expects.
    let launch_overhead_us = util::measure_launch_overhead();

    // CSV header + launch_overhead row. Keep format byte-identical
    // to the CUDA sweep so CSVs are mergeable.
    println!("# Metal GPU cost table — generated by metal_cost_sweep");
    println!("# Device: {}", util::device_name());
    println!("# Launch overhead: {launch_overhead_us:.2} us (subtracted from all timings)");
    println!("# Timings are compute-only. To get wall-clock time for N separate");
    println!("# kernel launches, add N * launch_overhead_us.");
    println!("# Regenerate: cargo run -p ferrite-metal-cost-sweep --release");
    println!("kernel,M,N,K,cost_us");
    println!("launch_overhead,0,0,0,{launch_overhead_us:.2}");

    rmsnorm_sweep::run(launch_overhead_us);

    eprintln!("metal_cost_sweep: done");
}
