// SPDX-License-Identifier: Apache-2.0
//! GPU cost sweep — THE entrypoint for new GPUs.
//!
//! Benchmarks every kernel the solver can pick (cuBLAS + the full CUTLASS
//! tile grid + GEMV at M=1) across a dense (M, N, K) grid, printing a CSV to
//! stdout that becomes `crates/vllm-tk-macros-core/data/cost_<gpu>.csv`.
//!
//! The solver's cost model is keyed by the CSV column names — adding a new
//! CUTLASS config means adding one entry to the `bench_cutlass!` macro below
//! (and the `cutlass_gemm_ffi!` macro in `solver_dispatch.rs`).
//!
//! Running:
//!   CUDA_PATH=/usr/local/cuda-12.9 cargo test -p vllm-tk-test-harness \
//!     --features cuda --test gpu_cost_sweep gpu_cost_sweep \
//!     -- --ignored --nocapture \
//!     2>/dev/null > crates/vllm-tk-macros-core/data/cost_<gpu>.csv

#![cfg(feature = "cuda")]

use cudarc::driver::result;
use vllm_tk_test_harness::ffi;

fn init_cuda() {
    result::init().expect("cuInit failed");
    let device = result::device::get(0).expect("cuDeviceGet failed");
    let ctx = unsafe { result::primary_ctx::retain(device) }.expect("cuCtxRetain failed");
    unsafe { result::ctx::set_current(ctx) }.expect("cuCtxSetCurrent failed");
}

fn gpu_alloc_zeros(bytes: usize) -> u64 {
    unsafe {
        let dptr = result::malloc_sync(bytes).expect("cuMemAlloc failed");
        result::memset_d8_sync(dptr, 0, bytes).expect("cuMemsetD8 failed");
        dptr
    }
}

#[test]
#[ignore = "needs GPU, ~5 min"]
fn gpu_cost_sweep() {
    use cudarc::driver::sys;

    init_cuda();

    let mut handle: ffi::CublasHandle = std::ptr::null_mut();
    unsafe {
        let s = ffi::cublasCreate_v2(&mut handle);
        assert_eq!(s, 0);
        let s = ffi::cublasSetStream_v2(handle, std::ptr::null_mut());
        assert_eq!(s, 0);
    }

    // Dense grid of (N, K) shapes covering LLaMA 1B through 70B.
    let nk_shapes: &[(u32, u32)] = &[
        // Small models (1B-3B)
        (2048, 2048),
        (3072, 2048),
        (3072, 3072),
        (4608, 3072),
        (8192, 2048),
        (8192, 3072),
        (2048, 8192),
        (3072, 8192),
        // Medium models (7B-13B)
        (4096, 4096),
        (6144, 4096),
        (11008, 4096),
        (14336, 4096),
        (4096, 11008),
        (4096, 14336),
        // Large models (30B-70B)
        (8192, 8192),
        (10240, 8192),
        (28672, 8192),
        (8192, 28672),
    ];

    let m_values: &[u32] = &[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096];

    const WARMUP: u32 = 5;
    const ITERS: u32 = 5;

    let stream: sys::CUstream = std::ptr::null_mut();

    // ── Measure kernel launch overhead using a null kernel ──
    // This is subtracted from all timings to get compute-only cost.
    let launch_overhead_us = {
        let null_launch = || unsafe { ffi::null_kernel_launch(stream as u64) };
        // Extra warmup for the null kernel
        for _ in 0..100 {
            null_launch();
        }
        unsafe { result::stream::synchronize(stream).unwrap() };
        bench_kernel(stream, 100, 500, null_launch)
    };

    println!("# GPU cost table — generated by gpu_cost_sweep");
    println!("# Launch overhead: {launch_overhead_us:.2} us (subtracted from all timings)");
    println!("# Timings are compute-only. To get wall-clock time for N separate");
    println!("# kernel launches, add N * launch_overhead_us.");
    println!("# To regenerate, see instructions in gpu_cost_sweep.rs");
    println!("kernel,M,N,K,cost_us");
    println!("launch_overhead,0,0,0,{launch_overhead_us:.2}");

    for &(n, k) in nk_shapes {
        for &m in m_values {
            let a = gpu_alloc_zeros((m * k) as usize * 2);
            let b = gpu_alloc_zeros((n * k) as usize * 2);
            let c = gpu_alloc_zeros((m * n) as usize * 2);

            let one: f32 = 1.0;
            let zero: f32 = 0.0;
            let m_i = m as i32;
            let n_i = n as i32;
            let k_i = k as i32;

            // ── cuBLAS ──
            let cublas_gemm = || unsafe {
                ffi::cublasGemmEx(
                    handle,
                    ffi::CUBLAS_OP_T,
                    ffi::CUBLAS_OP_N,
                    n_i,
                    m_i,
                    k_i,
                    &one as *const f32,
                    b as *const _,
                    ffi::CUDA_R_16BF,
                    k_i,
                    a as *const _,
                    ffi::CUDA_R_16BF,
                    k_i,
                    &zero as *const f32,
                    c as *mut _,
                    ffi::CUDA_R_16BF,
                    n_i,
                    ffi::CUBLAS_COMPUTE_32F,
                    ffi::CUBLAS_GEMM_DEFAULT,
                );
            };
            let cublas_us =
                (bench_kernel(stream, WARMUP, ITERS, cublas_gemm) - launch_overhead_us).max(0.0);
            println!("cublas,{m},{n},{k},{cublas_us:.1}");

            // ── All CUTLASS tile configs ──
            macro_rules! bench_cutlass {
                ($($name:literal => $fn:path),* $(,)?) => {
                    $(
                        let us = (bench_kernel(stream, WARMUP, ITERS, || unsafe {
                            $fn(
                                c as *mut u16, a as *const u16, b as *const u16,
                                m_i, n_i, k_i, 1.0, 0.0, stream as u64,
                            );
                        }) - launch_overhead_us).max(0.0);
                        println!(concat!($name, ",{},{},{},{:.1}"), m, n, k, us);
                    )*
                };
            }
            bench_cutlass!(
                "cutlass_32x64_s4"   => ffi::cutlass_gemm_32x64_s4_launch,
                "cutlass_32x64_s3"   => ffi::cutlass_gemm_32x64_s3_launch,
                "cutlass_32x128_s4"  => ffi::cutlass_gemm_32x128_s4_launch,
                "cutlass_32x128_s3"  => ffi::cutlass_gemm_32x128_s3_launch,
                "cutlass_32x256_s3"  => ffi::cutlass_gemm_32x256_s3_launch,
                "cutlass_64x64_s4"   => ffi::cutlass_gemm_64x64_s4_launch,
                "cutlass_64x64_s3"   => ffi::cutlass_gemm_64x64_s3_launch,
                "cutlass_64x128_s4"  => ffi::cutlass_gemm_64x128_s4_launch,
                "cutlass_64x128_s3"  => ffi::cutlass_gemm_64x128_s3_launch,
                "cutlass_128x64_s4"  => ffi::cutlass_gemm_128x64_s4_launch,
                "cutlass_128x64_s3"  => ffi::cutlass_gemm_128x64_s3_launch,
                "cutlass_128x128_s4" => ffi::cutlass_gemm_128x128_s4_launch,
                "cutlass_128x128_s3" => ffi::cutlass_gemm_128x128_s3_launch,
                "cutlass_128x256_s3" => ffi::cutlass_gemm_128x256_s3_launch,
                "cutlass_256x64_s4"  => ffi::cutlass_gemm_256x64_s4_launch,
                "cutlass_256x64_s3"  => ffi::cutlass_gemm_256x64_s3_launch,
            );

            // ── CUTLASS SplitK variants ──
            // SplitK is critical for large-K shapes (down_proj at small batch).
            // The splitK kernel allocates a workspace, so we bench it separately.
            bench_cutlass!(
                "cutlass_64x64_s4_sk2"   => ffi::cutlass_gemm_64x64_s4_sk2_launch,
                "cutlass_64x64_s4_sk4"   => ffi::cutlass_gemm_64x64_s4_sk4_launch,
                "cutlass_64x64_s4_sk8"   => ffi::cutlass_gemm_64x64_s4_sk8_launch,
                "cutlass_128x128_s3_sk2" => ffi::cutlass_gemm_128x128_s3_sk2_launch,
                "cutlass_128x128_s3_sk4" => ffi::cutlass_gemm_128x128_s3_sk4_launch,
                "cutlass_128x128_s3_sk8" => ffi::cutlass_gemm_128x128_s3_sk8_launch,
                "cutlass_64x128_s4_sk2"  => ffi::cutlass_gemm_64x128_s4_sk2_launch,
                "cutlass_64x128_s4_sk4"  => ffi::cutlass_gemm_64x128_s4_sk4_launch,
                "cutlass_64x128_s4_sk8"  => ffi::cutlass_gemm_64x128_s4_sk8_launch,
                "cutlass_32x64_s4_sk4"   => ffi::cutlass_gemm_32x64_s4_sk4_launch,
                "cutlass_32x64_s4_sk8"   => ffi::cutlass_gemm_32x64_s4_sk8_launch,
                "cutlass_32x64_s4_sk16"  => ffi::cutlass_gemm_32x64_s4_sk16_launch,
                // Round 2: closing M=128/1024 gaps
                "cutlass_128x128_s4_sk2" => ffi::cutlass_gemm_128x128_s4_sk2_launch,
                "cutlass_128x128_s4_sk4" => ffi::cutlass_gemm_128x128_s4_sk4_launch,
                "cutlass_128x128_s4_sk8" => ffi::cutlass_gemm_128x128_s4_sk8_launch,
                "cutlass_128x64_s4_sk2"  => ffi::cutlass_gemm_128x64_s4_sk2_launch,
                "cutlass_128x64_s4_sk4"  => ffi::cutlass_gemm_128x64_s4_sk4_launch,
                "cutlass_128x64_s4_sk8"  => ffi::cutlass_gemm_128x64_s4_sk8_launch,
                "cutlass_256x64_s4_sk2"  => ffi::cutlass_gemm_256x64_s4_sk2_launch,
                "cutlass_256x64_s4_sk4"  => ffi::cutlass_gemm_256x64_s4_sk4_launch,
                "cutlass_64x64_s4_sk16"  => ffi::cutlass_gemm_64x64_s4_sk16_launch,
                "cutlass_64x128_s4_sk16" => ffi::cutlass_gemm_64x128_s4_sk16_launch,
                // TB_K=64 variants
                "cutlass_64x64_k64_s4"   => ffi::cutlass_gemm_64x64_k64_s4_launch,
                "cutlass_64x64_k64_s3"   => ffi::cutlass_gemm_64x64_k64_s3_launch,
                "cutlass_64x128_k64_s4"  => ffi::cutlass_gemm_64x128_k64_s4_launch,
                "cutlass_64x128_k64_s3"  => ffi::cutlass_gemm_64x128_k64_s3_launch,
                "cutlass_128x64_k64_s4"  => ffi::cutlass_gemm_128x64_k64_s4_launch,
                "cutlass_128x64_k64_s3"  => ffi::cutlass_gemm_128x64_k64_s3_launch,
                "cutlass_128x128_k64_s4" => ffi::cutlass_gemm_128x128_k64_s4_launch,
                "cutlass_128x128_k64_s3" => ffi::cutlass_gemm_128x128_k64_s3_launch,
                "cutlass_256x64_k64_s4"  => ffi::cutlass_gemm_256x64_k64_s4_launch,
                "cutlass_256x64_k64_s3"  => ffi::cutlass_gemm_256x64_k64_s3_launch,
                "cutlass_128x256_k64_s3" => ffi::cutlass_gemm_128x256_k64_s3_launch,
                "cutlass_32x64_k64_s4"   => ffi::cutlass_gemm_32x64_k64_s4_launch,
                "cutlass_32x128_k64_s4"  => ffi::cutlass_gemm_32x128_k64_s4_launch,
                // TB_K=64 splitK
                "cutlass_64x64_k64_s4_sk2"   => ffi::cutlass_gemm_64x64_k64_s4_sk2_launch,
                "cutlass_64x64_k64_s4_sk4"   => ffi::cutlass_gemm_64x64_k64_s4_sk4_launch,
                "cutlass_64x64_k64_s4_sk8"   => ffi::cutlass_gemm_64x64_k64_s4_sk8_launch,
                "cutlass_128x128_k64_s3_sk2" => ffi::cutlass_gemm_128x128_k64_s3_sk2_launch,
                "cutlass_128x128_k64_s3_sk4" => ffi::cutlass_gemm_128x128_k64_s3_sk4_launch,
                // k64 stages=2
                "cutlass_128x128_k64_s2" => ffi::cutlass_gemm_128x128_k64_s2_launch,
                "cutlass_64x64_k64_s2"   => ffi::cutlass_gemm_64x64_k64_s2_launch,
                "cutlass_64x128_k64_s2"  => ffi::cutlass_gemm_64x128_k64_s2_launch,
                "cutlass_128x64_k64_s2"  => ffi::cutlass_gemm_128x64_k64_s2_launch,
                "cutlass_256x64_k64_s2"  => ffi::cutlass_gemm_256x64_k64_s2_launch,
                // 256×128 s2
                "cutlass_256x128_s2"     => ffi::cutlass_gemm_256x128_s2_launch,
                // stages=2 variants
                "cutlass_64x64_s2"       => ffi::cutlass_gemm_64x64_s2_launch,
                "cutlass_64x128_s2"      => ffi::cutlass_gemm_64x128_s2_launch,
                "cutlass_128x64_s2"      => ffi::cutlass_gemm_128x64_s2_launch,
                "cutlass_128x128_s2"     => ffi::cutlass_gemm_128x128_s2_launch,
                "cutlass_128x256_s2"     => ffi::cutlass_gemm_128x256_s2_launch,
                "cutlass_256x64_s2"      => ffi::cutlass_gemm_256x64_s2_launch,
                // Deep pipeline variants (stages=5-10)
                "cutlass_64x128_s5"      => ffi::cutlass_gemm_64x128_s5_launch,
                "cutlass_64x128_s6"      => ffi::cutlass_gemm_64x128_s6_launch,
                "cutlass_64x128_s7"      => ffi::cutlass_gemm_64x128_s7_launch,
                "cutlass_64x128_s8"      => ffi::cutlass_gemm_64x128_s8_launch,
                "cutlass_128x128_s5"     => ffi::cutlass_gemm_128x128_s5_launch,
                "cutlass_128x128_s6"     => ffi::cutlass_gemm_128x128_s6_launch,
                "cutlass_64x64_s5"       => ffi::cutlass_gemm_64x64_s5_launch,
                "cutlass_64x64_s6"       => ffi::cutlass_gemm_64x64_s6_launch,
                "cutlass_64x64_s8"       => ffi::cutlass_gemm_64x64_s8_launch,
                "cutlass_64x64_s10"      => ffi::cutlass_gemm_64x64_s10_launch,
                "cutlass_128x64_s5"      => ffi::cutlass_gemm_128x64_s5_launch,
                "cutlass_128x64_s6"      => ffi::cutlass_gemm_128x64_s6_launch,
                "cutlass_128x64_s7"      => ffi::cutlass_gemm_128x64_s7_launch,
                "cutlass_128x64_s8"      => ffi::cutlass_gemm_128x64_s8_launch,
                "cutlass_64x256_s4"      => ffi::cutlass_gemm_64x256_s4_launch,
                "cutlass_64x256_s5"      => ffi::cutlass_gemm_64x256_s5_launch,
                "cutlass_128x256_s4"     => ffi::cutlass_gemm_128x256_s4_launch,
                "cutlass_256x64_s5"      => ffi::cutlass_gemm_256x64_s5_launch,
                "cutlass_256x64_s6"      => ffi::cutlass_gemm_256x64_s6_launch,
                // CTA-swizzled variants (L2 locality)
                "cutlass_128x128_sw_s4"  => ffi::cutlass_gemm_128x128_sw_s4_launch,
                "cutlass_128x128_sw_s3"  => ffi::cutlass_gemm_128x128_sw_s3_launch,
                "cutlass_128x128_sw_s2"  => ffi::cutlass_gemm_128x128_sw_s2_launch,
                "cutlass_128x256_sw_s3"  => ffi::cutlass_gemm_128x256_sw_s3_launch,
                "cutlass_128x256_sw_s2"  => ffi::cutlass_gemm_128x256_sw_s2_launch,
                "cutlass_256x64_sw_s4"   => ffi::cutlass_gemm_256x64_sw_s4_launch,
                "cutlass_256x64_sw_s3"   => ffi::cutlass_gemm_256x64_sw_s3_launch,
                "cutlass_64x128_sw_s4"   => ffi::cutlass_gemm_64x128_sw_s4_launch,
                "cutlass_64x128_sw_s3"   => ffi::cutlass_gemm_64x128_sw_s3_launch,
                // 64×256 tile
                "cutlass_64x256_s3"      => ffi::cutlass_gemm_64x256_s3_launch,
                "cutlass_64x256_s2"      => ffi::cutlass_gemm_64x256_s2_launch,
                "cutlass_64x256_sw_s3"   => ffi::cutlass_gemm_64x256_sw_s3_launch,
                "cutlass_64x256_sw_s2"   => ffi::cutlass_gemm_64x256_sw_s2_launch,
                // 64×256 splitK
                "cutlass_64x256_s3_sk2"  => ffi::cutlass_gemm_64x256_s3_sk2_launch,
                "cutlass_64x256_s3_sk4"  => ffi::cutlass_gemm_64x256_s3_sk4_launch,
                "cutlass_64x256_s3_sk8"  => ffi::cutlass_gemm_64x256_s3_sk8_launch,
                // 8-warp (256 thread) variants
                "cutlass_64x128_k64w8_s3" => ffi::cutlass_gemm_64x128_k64w8_s3_launch,
                "cutlass_64x128_k64w8_s4" => ffi::cutlass_gemm_64x128_k64w8_s4_launch,
                "cutlass_64x128_k64w8_s2" => ffi::cutlass_gemm_64x128_k64w8_s2_launch,
                "cutlass_64x128_w8_s3"    => ffi::cutlass_gemm_64x128_w8_s3_launch,
                "cutlass_64x128_w8_s4"    => ffi::cutlass_gemm_64x128_w8_s4_launch,
                "cutlass_64x128_w8_s5"    => ffi::cutlass_gemm_64x128_w8_s5_launch,
                "cutlass_64x128_w8_s6"    => ffi::cutlass_gemm_64x128_w8_s6_launch,
                "cutlass_128x128_w8_s3"   => ffi::cutlass_gemm_128x128_w8_s3_launch,
                "cutlass_128x128_w8_s4"   => ffi::cutlass_gemm_128x128_w8_s4_launch,
                "cutlass_128x128_w8_s5"   => ffi::cutlass_gemm_128x128_w8_s5_launch,
                // Deep pipeline splitK
                "cutlass_64x128_s5_sk4"  => ffi::cutlass_gemm_64x128_s5_sk4_launch,
                "cutlass_64x128_s6_sk4"  => ffi::cutlass_gemm_64x128_s6_sk4_launch,
                "cutlass_64x128_s6_sk2"  => ffi::cutlass_gemm_64x128_s6_sk2_launch,
                "cutlass_64x128_s6_sk8"  => ffi::cutlass_gemm_64x128_s6_sk8_launch,
                "cutlass_64x128_s7_sk4"  => ffi::cutlass_gemm_64x128_s7_sk4_launch,
                "cutlass_64x128_s8_sk4"  => ffi::cutlass_gemm_64x128_s8_sk4_launch,
                "cutlass_128x128_s5_sk4" => ffi::cutlass_gemm_128x128_s5_sk4_launch,
                "cutlass_128x128_s5_sk8" => ffi::cutlass_gemm_128x128_s5_sk8_launch,
                "cutlass_128x64_s5_sk4"  => ffi::cutlass_gemm_128x64_s5_sk4_launch,
                "cutlass_128x64_s6_sk4"  => ffi::cutlass_gemm_128x64_s6_sk4_launch,
            );

            // ── CUTLASS 3.x sm90 (Hopper) tile configs ──
            #[cfg(cuda_arch_sm90)]
            bench_cutlass!(
                "sm90_128x128_coop" => ffi::cutlass_sm90_gemm_128x128_coop_launch,
                "sm90_128x256_coop" => ffi::cutlass_sm90_gemm_128x256_coop_launch,
                "sm90_256x128_coop" => ffi::cutlass_sm90_gemm_256x128_coop_launch,
                "sm90_64x128_ws"    => ffi::cutlass_sm90_gemm_64x128_ws_launch,
                "sm90_128x64_ws"    => ffi::cutlass_sm90_gemm_128x64_ws_launch,
                "sm90_64x64_ws"     => ffi::cutlass_sm90_gemm_64x64_ws_launch,
                "sm90_128x128_pp"   => ffi::cutlass_sm90_gemm_128x128_pp_launch,
                "sm90_64x128_pp"    => ffi::cutlass_sm90_gemm_64x128_pp_launch,
                "sm90_128x64_pp"    => ffi::cutlass_sm90_gemm_128x64_pp_launch,
                "sm90_128x128_c2x1" => ffi::cutlass_sm90_gemm_128x128_c2x1_launch,
                "sm90_128x256_c2x1" => ffi::cutlass_sm90_gemm_128x256_c2x1_launch,
            );

            // ── ThunderKittens persistent-grid GEMM ──
            // TK has tile alignment constraints; the launcher returns -1
            // for shapes it can't handle, so we skip those.
            #[cfg(cuda_arch_sm90)]
            {
                macro_rules! bench_tk {
                    ($($name:literal => $fn:path),* $(,)?) => {
                        $(
                            let rc = unsafe {
                                $fn(
                                    c as *mut u16, a as *const u16, b as *const u16,
                                    m_i, n_i, k_i, 1.0, 0.0, stream as u64,
                                )
                            };
                            if rc == 0 {
                                // Feasible — now benchmark it
                                let us = (bench_kernel(stream, WARMUP, ITERS, || unsafe {
                                    $fn(
                                        c as *mut u16, a as *const u16, b as *const u16,
                                        m_i, n_i, k_i, 1.0, 0.0, stream as u64,
                                    );
                                }) - launch_overhead_us).max(0.0);
                                println!(concat!($name, ",{},{},{},{:.1}"), m, n, k, us);
                            }
                        )*
                    };
                }
                bench_tk!(
                    "tk_128x256" => ffi::tk_gemm_128x256_launch,
                    "tk_128x128" => ffi::tk_gemm_128x128_launch,
                    "tk_64x256"  => ffi::tk_gemm_64x256_launch,
                    "tk_64x128"  => ffi::tk_gemm_64x128_launch,
                    "tk_64x64"   => ffi::tk_gemm_64x64_launch,
                );
            }

            // GEMV only makes sense at M=1
            if m == 1 {
                let us = (bench_kernel(stream, WARMUP, ITERS, || unsafe {
                    ffi::cutlass_gemv_launch(
                        c as *mut u16,
                        a as *const u16,
                        b as *const u16,
                        m_i,
                        n_i,
                        k_i,
                        1.0,
                        0.0,
                        stream as u64,
                    );
                }) - launch_overhead_us)
                    .max(0.0);
                println!("cutlass_gemv,{m},{n},{k},{us:.1}");
            }

            // ── CUTLASS GEMM + SiLU + Mul (EVT epilogue fusion) ──
            // The fused kernel computes D = silu(A @ B_gate) * C_up.
            // C_up has the same shape as the output [M, N].
            {
                let up = gpu_alloc_zeros((m * n) as usize * 2);
                let us = (bench_kernel(stream, WARMUP, ITERS, || unsafe {
                    ffi::cutlass_gemm_silu_mul_launch(
                        c as *mut u16,
                        a as *const u16,
                        b as *const u16,
                        up as *mut u16,
                        m_i,
                        n_i,
                        k_i,
                        stream as u64,
                    );
                }) - launch_overhead_us)
                    .max(0.0);
                println!("cutlass_silu_mul,{m},{n},{k},{us:.1}");
                unsafe { cudarc::driver::sys::cuMemFree_v2(up) };
            }

            unsafe {
                cudarc::driver::sys::cuMemFree_v2(a);
            }
            unsafe {
                cudarc::driver::sys::cuMemFree_v2(b);
            }
            unsafe {
                cudarc::driver::sys::cuMemFree_v2(c);
            }
        }
    }

    unsafe { ffi::cublasDestroy_v2(handle) };

    // ── Elementwise ops (RMSNorm, SiLU+Mul, RoPE) ──
    //
    // These are cheap ops whose exact cost matters in the megakernel
    // model (no launch overhead to hide behind). Sweep across M
    // (num_tokens) for each hidden_size relevant to the model grid.

    let hidden_sizes: &[u32] = &[2048, 3072, 4096, 8192];

    for &hidden in hidden_sizes {
        for &m in m_values {
            let input = gpu_alloc_zeros((m * hidden) as usize * 2);
            let output = gpu_alloc_zeros((m * hidden) as usize * 2);
            let weight = gpu_alloc_zeros(hidden as usize * 2);

            // RMSNorm
            let rms_us = (bench_kernel(stream, WARMUP, ITERS, || unsafe {
                ffi::rms_norm_bf16(
                    output as *mut u16,
                    input as *const u16,
                    weight as *const u16,
                    1e-5,
                    m as i32,
                    hidden as i32,
                    stream as u64,
                );
            }) - launch_overhead_us)
                .max(0.0);
            println!("rms_norm,{m},{hidden},0,{rms_us:.2}");

            // SiLU+Mul (input is [m, 2*hidden], output is [m, hidden])
            let gate_up = gpu_alloc_zeros((m * hidden * 2) as usize * 2);
            let silu_us = (bench_kernel(stream, WARMUP, ITERS, || unsafe {
                ffi::silu_and_mul_fused_bf16(
                    output as *mut u16,
                    gate_up as *const u16,
                    m as i32,
                    hidden as i32,
                    stream as u64,
                );
            }) - launch_overhead_us)
                .max(0.0);
            println!("silu_mul,{m},{hidden},0,{silu_us:.2}");

            unsafe {
                cudarc::driver::sys::cuMemFree_v2(input);
                cudarc::driver::sys::cuMemFree_v2(output);
                cudarc::driver::sys::cuMemFree_v2(weight);
                cudarc::driver::sys::cuMemFree_v2(gate_up);
            }
        }
    }

    // ── Fused QKV RoPE ──
    // Sweep across M for LLaMA-style head configs.
    // q_size = num_q_heads * head_dim, kv_size = num_kv_heads * head_dim
    struct RopeConfig {
        name: &'static str,
        q_size: u32,
        kv_size: u32,
        head_size: u32,
        rotary_dim: u32,
    }
    let rope_configs = [
        RopeConfig {
            name: "rope_1b",
            q_size: 2048,
            kv_size: 512,
            head_size: 64,
            rotary_dim: 64,
        },
        RopeConfig {
            name: "rope_7b",
            q_size: 4096,
            kv_size: 1024,
            head_size: 128,
            rotary_dim: 128,
        },
        RopeConfig {
            name: "rope_70b",
            q_size: 8192,
            kv_size: 1024,
            head_size: 128,
            rotary_dim: 128,
        },
    ];
    for cfg in &rope_configs {
        let total_dim = cfg.q_size + 2 * cfg.kv_size;
        // cos_sin_cache: [max_position, rotary_dim] — we just need it allocated
        let max_pos = 4096u32;
        let cos_sin = gpu_alloc_zeros((max_pos * cfg.rotary_dim) as usize * 2);
        for &m in m_values {
            let qkv = gpu_alloc_zeros((m * total_dim) as usize * 2);
            let q_out = gpu_alloc_zeros((m * cfg.q_size) as usize * 2);
            let k_out = gpu_alloc_zeros((m * cfg.kv_size) as usize * 2);
            let v_out = gpu_alloc_zeros((m * cfg.kv_size) as usize * 2);
            // positions: i64 array
            let positions = gpu_alloc_zeros(m as usize * 8);

            let rope_us = (bench_kernel(stream, WARMUP, ITERS, || unsafe {
                ffi::fused_qkv_rope_bf16(
                    q_out as *mut u16,
                    k_out as *mut u16,
                    v_out as *mut u16,
                    qkv as *const u16,
                    positions as *const u16,
                    cos_sin as *const u16,
                    cfg.q_size as i32,
                    cfg.kv_size as i32,
                    total_dim as i32,
                    cfg.rotary_dim as i32,
                    cfg.head_size as i32,
                    m as i32,
                    stream as u64,
                );
            }) - launch_overhead_us)
                .max(0.0);
            // N = total_dim (QKV fused width), K = rotary_dim
            println!(
                "{},{m},{},{},{rope_us:.2}",
                cfg.name, total_dim, cfg.rotary_dim
            );

            unsafe {
                cudarc::driver::sys::cuMemFree_v2(qkv);
                cudarc::driver::sys::cuMemFree_v2(q_out);
                cudarc::driver::sys::cuMemFree_v2(k_out);
                cudarc::driver::sys::cuMemFree_v2(v_out);
                cudarc::driver::sys::cuMemFree_v2(positions);
            }
        }
        unsafe { cudarc::driver::sys::cuMemFree_v2(cos_sin) };
    }

    eprintln!("gpu_cost_sweep: done");
}

/// Benchmark a GPU kernel: warmup + timed iterations → median µs.
fn bench_kernel(
    stream: cudarc::driver::sys::CUstream,
    warmup: u32,
    iters: u32,
    mut f: impl FnMut(),
) -> f64 {
    use cudarc::driver::sys;
    for _ in 0..warmup {
        f();
    }
    unsafe { result::stream::synchronize(stream).unwrap() };

    let elapsed_ms = unsafe {
        let mut start: sys::CUevent = std::ptr::null_mut();
        let mut stop: sys::CUevent = std::ptr::null_mut();
        sys::cuEventCreate(&mut start, 0);
        sys::cuEventCreate(&mut stop, 0);
        sys::cuEventRecord(start, stream);
        for _ in 0..iters {
            f();
        }
        sys::cuEventRecord(stop, stream);
        sys::cuEventSynchronize(stop);
        let mut ms: f32 = 0.0;
        sys::cuEventElapsedTime(&mut ms, start, stop);
        sys::cuEventDestroy_v2(start);
        sys::cuEventDestroy_v2(stop);
        ms / iters as f32
    };
    (elapsed_ms * 1000.0) as f64
}
