// SPDX-License-Identifier: Apache-2.0
//! GPU cost sweep — THE entrypoint for new GPUs.
//!
//! Benchmarks every kernel the solver can pick (cuBLAS + the full CUTLASS
//! tile grid + GEMV at M=1) across a dense (M, N, K) grid, printing a CSV to
//! stdout that becomes `crates/vllm-tk-macros-core/data/cost_<gpu>.csv`.
//!
//! The solver's cost model is keyed by the CSV column names — adding a new
//! CUTLASS config means adding one entry to the `bench_cutlass!` macro below
//! (and the `cutlass_gemm_ffi!` macro in `solver_dispatch.rs`).
//!
//! Running:
//!   CUDA_PATH=/usr/local/cuda-12.9 cargo test -p vllm-tk-test-harness \
//!     --features cuda --test gpu_cost_sweep gpu_cost_sweep \
//!     -- --ignored --nocapture \
//!     2>/dev/null > crates/vllm-tk-macros-core/data/cost_<gpu>.csv

#![cfg(feature = "cuda")]

use cudarc::driver::result;
use vllm_tk_test_harness::ffi;

fn init_cuda() {
    result::init().expect("cuInit failed");
    let device = result::device::get(0).expect("cuDeviceGet failed");
    let ctx = unsafe { result::primary_ctx::retain(device) }.expect("cuCtxRetain failed");
    unsafe { result::ctx::set_current(ctx) }.expect("cuCtxSetCurrent failed");
}

fn gpu_alloc_zeros(bytes: usize) -> u64 {
    unsafe {
        let dptr = result::malloc_sync(bytes).expect("cuMemAlloc failed");
        result::memset_d8_sync(dptr, 0, bytes).expect("cuMemsetD8 failed");
        dptr
    }
}

#[test]
#[ignore = "needs GPU, ~5 min"]
fn gpu_cost_sweep() {
    use cudarc::driver::sys;

    init_cuda();

    let mut handle: ffi::CublasHandle = std::ptr::null_mut();
    unsafe {
        let s = ffi::cublasCreate_v2(&mut handle);
        assert_eq!(s, 0);
        let s = ffi::cublasSetStream_v2(handle, std::ptr::null_mut());
        assert_eq!(s, 0);
    }

    // Dense grid of (N, K) shapes covering LLaMA 1B through 70B.
    let nk_shapes: &[(u32, u32)] = &[
        // Small models (1B-3B)
        (2048, 2048),
        (3072, 2048),
        (3072, 3072),
        (4608, 3072),
        (8192, 2048),
        (8192, 3072),
        (2048, 8192),
        (3072, 8192),
        // Medium models (7B-13B)
        (4096, 4096),
        (6144, 4096),
        (11008, 4096),
        (14336, 4096),
        (4096, 11008),
        (4096, 14336),
        // Large models (30B-70B)
        (8192, 8192),
        (10240, 8192),
        (28672, 8192),
        (8192, 28672),
    ];

    let m_values: &[u32] = &[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096];

    const WARMUP: u32 = 10;
    const ITERS: u32 = 50;

    println!("# GPU cost table — generated by gpu_cost_sweep");
    println!("# To regenerate, see instructions in gpu_cost_sweep.rs");
    println!("kernel,M,N,K,cost_us");

    let stream: sys::CUstream = std::ptr::null_mut();

    for &(n, k) in nk_shapes {
        for &m in m_values {
            let a = gpu_alloc_zeros((m * k) as usize * 2);
            let b = gpu_alloc_zeros((n * k) as usize * 2);
            let c = gpu_alloc_zeros((m * n) as usize * 2);

            let one: f32 = 1.0;
            let zero: f32 = 0.0;
            let m_i = m as i32;
            let n_i = n as i32;
            let k_i = k as i32;

            // ── cuBLAS ──
            let cublas_gemm = || unsafe {
                ffi::cublasGemmEx(
                    handle,
                    ffi::CUBLAS_OP_T,
                    ffi::CUBLAS_OP_N,
                    n_i,
                    m_i,
                    k_i,
                    &one as *const f32,
                    b as *const _,
                    ffi::CUDA_R_16BF,
                    k_i,
                    a as *const _,
                    ffi::CUDA_R_16BF,
                    k_i,
                    &zero as *const f32,
                    c as *mut _,
                    ffi::CUDA_R_16BF,
                    n_i,
                    ffi::CUBLAS_COMPUTE_32F,
                    ffi::CUBLAS_GEMM_DEFAULT,
                );
            };
            let cublas_us = bench_kernel(stream, WARMUP, ITERS, cublas_gemm);
            println!("cublas,{m},{n},{k},{cublas_us:.1}");

            // ── All CUTLASS tile configs ──
            macro_rules! bench_cutlass {
                ($($name:literal => $fn:path),* $(,)?) => {
                    $(
                        let us = bench_kernel(stream, WARMUP, ITERS, || unsafe {
                            $fn(
                                c as *mut u16, a as *const u16, b as *const u16,
                                m_i, n_i, k_i, 1.0, 0.0, stream as u64,
                            );
                        });
                        println!(concat!($name, ",{},{},{},{:.1}"), m, n, k, us);
                    )*
                };
            }
            bench_cutlass!(
                "cutlass_32x64_s4"   => ffi::cutlass_gemm_32x64_s4_launch,
                "cutlass_32x64_s3"   => ffi::cutlass_gemm_32x64_s3_launch,
                "cutlass_32x128_s4"  => ffi::cutlass_gemm_32x128_s4_launch,
                "cutlass_32x128_s3"  => ffi::cutlass_gemm_32x128_s3_launch,
                "cutlass_32x256_s3"  => ffi::cutlass_gemm_32x256_s3_launch,
                "cutlass_64x64_s4"   => ffi::cutlass_gemm_64x64_s4_launch,
                "cutlass_64x64_s3"   => ffi::cutlass_gemm_64x64_s3_launch,
                "cutlass_64x128_s4"  => ffi::cutlass_gemm_64x128_s4_launch,
                "cutlass_64x128_s3"  => ffi::cutlass_gemm_64x128_s3_launch,
                "cutlass_128x64_s4"  => ffi::cutlass_gemm_128x64_s4_launch,
                "cutlass_128x64_s3"  => ffi::cutlass_gemm_128x64_s3_launch,
                "cutlass_128x128_s4" => ffi::cutlass_gemm_128x128_s4_launch,
                "cutlass_128x128_s3" => ffi::cutlass_gemm_128x128_s3_launch,
                "cutlass_128x256_s3" => ffi::cutlass_gemm_128x256_s3_launch,
                "cutlass_256x64_s4"  => ffi::cutlass_gemm_256x64_s4_launch,
                "cutlass_256x64_s3"  => ffi::cutlass_gemm_256x64_s3_launch,
            );

            // GEMV only makes sense at M=1
            if m == 1 {
                let us = bench_kernel(stream, WARMUP, ITERS, || unsafe {
                    ffi::cutlass_gemv_launch(
                        c as *mut u16,
                        a as *const u16,
                        b as *const u16,
                        m_i,
                        n_i,
                        k_i,
                        1.0,
                        0.0,
                        stream as u64,
                    );
                });
                println!("cutlass_gemv,{m},{n},{k},{us:.1}");
            }

            unsafe {
                cudarc::driver::sys::cuMemFree_v2(a);
            }
            unsafe {
                cudarc::driver::sys::cuMemFree_v2(b);
            }
            unsafe {
                cudarc::driver::sys::cuMemFree_v2(c);
            }
        }
    }

    unsafe { ffi::cublasDestroy_v2(handle) };
    eprintln!("gpu_cost_sweep: done");
}

/// Benchmark a GPU kernel: warmup + timed iterations → median µs.
fn bench_kernel(
    stream: cudarc::driver::sys::CUstream,
    warmup: u32,
    iters: u32,
    mut f: impl FnMut(),
) -> f64 {
    use cudarc::driver::sys;
    for _ in 0..warmup {
        f();
    }
    unsafe { result::stream::synchronize(stream).unwrap() };

    let elapsed_ms = unsafe {
        let mut start: sys::CUevent = std::ptr::null_mut();
        let mut stop: sys::CUevent = std::ptr::null_mut();
        sys::cuEventCreate(&mut start, 0);
        sys::cuEventCreate(&mut stop, 0);
        sys::cuEventRecord(start, stream);
        for _ in 0..iters {
            f();
        }
        sys::cuEventRecord(stop, stream);
        sys::cuEventSynchronize(stop);
        let mut ms: f32 = 0.0;
        sys::cuEventElapsedTime(&mut ms, start, stop);
        sys::cuEventDestroy_v2(start);
        sys::cuEventDestroy_v2(stop);
        ms / iters as f32
    };
    (elapsed_ms * 1000.0) as f64
}
