// SPDX-License-Identifier: Apache-2.0
//! Instruction-list IR consumed by the runtime interpreter (and,
//! later, by an on-GPU megakernel).
//!
//! # Why this module exists
//!
//! ferrite-forward's compiler ends at "list of operations to run."
//! Today, that list is materialized as inline Rust calls inside a
//! per-variant forward fn — codegen.rs walks the wave graph and
//! emits a `quote!{}` of `kernels::rms_norm(...); kernels::gemm(...);`
//! for every (subgraph × variant × workload-point). For a 80-layer
//! model with 20 workload points that's ~20 k inlined call sites
//! to compile per variant; rustc spends minutes on that.
//!
//! The instruction-list IR replaces the inlined calls with DATA: a
//! `&'static [Instruction]` per (variant × workload-point). Each
//! `Instruction` is a fixed 32-int row — opcode in the first slot,
//! up to 31 i32 fields after it. The runtime interpreter
//! (generated by the same macro from the Impl library) decodes the
//! opcode at runtime and dispatches to a `ferrite_kernels` call.
//!
//! Two backends consume the same instruction list:
//!
//! 1. **Host interpreter** — a generated `match opcode { 1 => ..., 2 => ... }`
//!    walking each instruction and calling the appropriate
//!    `ferrite_kernels::*` function. One Rust kernel launch per
//!    instruction. Equivalent to the per-launch path ferrite-forward
//!    emits today, except the dispatch is data-driven instead of
//!    being baked into the call sites.
//!
//! 2. **On-GPU megakernel** (e.g. ThunderKittens KVM) — the same
//!    instruction tensor is uploaded to the GPU and consumed by a
//!    persistent-grid megakernel that dispatches each instruction
//!    on-device. No Rust-side per-instruction overhead at all.
//!
//! Both produce the same logical computation; the choice between
//! them is a target-profile decision the solver makes per workload
//! point.
//!
//! # Format
//!
//! [`INTS_PER_INSTRUCTION`] = 32, matching the `tp_throughput` KVM
//! demo's wire format so the same encoded list can feed either
//! backend without translation.
//!
//! Slot 0 is the opcode (low 16 bits used; high 16 bits reserved
//! for future use). Slots 1..32 are opcode-specific fields, layout
//! defined per-opcode by the Impl that emits the instruction.
//!
//! Variable-length fields (e.g. `AttentionDecode`'s list of seq
//! indices, `AttnNorm`'s `local_batch_indices`) are encoded as
//! `(count, items..., zero-padding)` starting at the slot the
//! opcode's encoding specifies. Counts are bounded by the 31-slot
//! envelope; instructions whose payload would exceed that are
//! split into multiple instructions by the Impl's fan-out logic.

#![allow(dead_code)]

/// Width of one instruction in 32-bit words. Matches KVM
/// (`INTS_PER_INSTRUCTION` in `~/Megakernels/megakernels/instructions.py`)
/// so encoded instruction tensors are wire-compatible across
/// host-interpreter and on-GPU-megakernel backends.
pub const INTS_PER_INSTRUCTION: usize = 32;

/// One instruction. Slot 0 is the opcode (read low 16 bits via
/// [`Instruction::opcode`]); slots 1..32 are opcode-defined
/// fields.
///
/// `repr(transparent)` over `[i32; 32]` so a `&[Instruction]`
/// reinterprets bit-for-bit as the `(N, 32)` int32 tensor an
/// on-GPU megakernel expects, without any per-instruction
/// serialization step at runtime.
#[derive(Copy, Clone, Debug)]
#[repr(transparent)]
pub struct Instruction(pub [i32; INTS_PER_INSTRUCTION]);

impl Instruction {
    /// Construct from opcode + a 31-slot field array.
    #[inline]
    pub const fn new(opcode: u16, fields: [i32; INTS_PER_INSTRUCTION - 1]) -> Self {
        let mut arr = [0i32; INTS_PER_INSTRUCTION];
        arr[0] = opcode as i32;
        let mut i = 0;
        while i < INTS_PER_INSTRUCTION - 1 {
            arr[i + 1] = fields[i];
            i += 1;
        }
        Self(arr)
    }

    /// Construct an all-zero (NoOp) instruction.
    #[inline]
    pub const fn noop() -> Self {
        Self([0; INTS_PER_INSTRUCTION])
    }

    /// Read the opcode (low 16 bits of slot 0).
    #[inline]
    pub const fn opcode(&self) -> u16 {
        self.0[0] as u16
    }

    /// Read field N (0-indexed within the 31 opcode-defined slots).
    /// Caller is responsible for staying in range; out-of-range
    /// indexes panic at runtime in debug, return arbitrary in
    /// release. Generated interpreter arms always index by
    /// constants so this is fine.
    #[inline]
    pub const fn field(&self, idx: usize) -> i32 {
        self.0[idx + 1]
    }

    /// View slots `start..start+len` as a slice — used by
    /// variable-length fields (e.g. `AttnNorm::local_batch_indices`).
    #[inline]
    pub fn fields_slice(&self, start: usize, len: usize) -> &[i32] {
        &self.0[start + 1..start + 1 + len]
    }
}

/// Block-size layout the kernels operate at. These values are
/// fixed by the chosen backend (e.g. KVM `tp_throughput` defaults)
/// and inform the Impl's fan-out logic — how many instructions an
/// op decomposes into for a given workload shape.
///
/// The values here match `~/Megakernels/megakernels/demos/tp_throughput/globs.py`
/// so a host-interpreter run and a megakernel run produce
/// identical instruction lists for the same input.
#[derive(Copy, Clone, Debug)]
pub struct Layout {
    /// Token-batch tile size for matmul-bearing ops (qkv, o_proj,
    /// up, gate, down). One `MatMulInstruction` covers a
    /// `(matmul_batch_block_size, matmul_output_block_size)`
    /// output tile.
    pub matmul_batch_block_size: u32,

    /// Output-channel tile size for matmul-bearing ops. The fan-out
    /// emits `ceil(out_dim / matmul_output_block_size)` instructions
    /// per layer per batch tile.
    pub matmul_output_block_size: u32,

    /// Prefill Q-token tile size for `AttentionPrefill`. A sequence
    /// being prefilled with `n` tokens fans out into
    /// `ceil(n / prefill_block_size)` `AttentionPrefill` instructions
    /// per layer per kv head.
    pub prefill_block_size: u32,

    /// Paged KV cache page size. Determines how many tokens fit per
    /// page; `decode_kv_indptr` / `prefill_kv_indptr` are indexed
    /// in units of pages.
    pub page_size: u32,
}

impl Layout {
    /// Defaults from `tp_throughput` (Megakernels open-source
    /// throughput-mode demo). Suitable for the common llama
    /// shapes; arches that need other values override per target
    /// profile.
    pub const TP_THROUGHPUT_DEFAULT: Self = Self {
        matmul_batch_block_size: 128,
        matmul_output_block_size: 256,
        prefill_block_size: 16,
        page_size: 128,
    };
}

/// Llama-family opcode constants. Matches
/// `~/Megakernels/megakernels/demos/tp_throughput/cpp_src/instructions.hpp`
/// so a single instruction list can target either the host
/// interpreter or a tp_throughput megakernel binary.
///
/// Other architectures (deepseek MLA, gemma3 conditional
/// attention, command-r layernorm, …) define their own opcode
/// tables in arch-specific submodules, possibly reusing slots that
/// are semantically the same op.
pub mod opcode {
    /// Filler / padding instruction. Generated when the per-SM
    /// queue length must be aligned to a power of two.
    pub const NOOP: u16 = 0;

    /// rmsnorm before attention (`pre-attn layernorm`). Fields:
    /// `[layer_idx, count, batch_idx_0, batch_idx_1, ...]`.
    pub const ATTN_NORM: u16 = 1;

    /// Fused: qkv gemm + RoPE on q,k + append k,v to paged KV
    /// cache. Fields: matmul-shape (layer_idx, local/global
    /// batch/output block indices). One instruction per output
    /// tile; fans out `num_batch_blocks × num_qkv_blocks` per layer.
    pub const QKV_ROPE_APPEND: u16 = 2;

    /// Per-(seq, q-block, kv-head) prefill attention. Fields:
    /// `[layer_idx, prefill_seq_idx, prefill_block_idx,
    ///   prefill_token_offset, kv_head_idx]`.
    pub const ATTENTION_PREFILL: u16 = 3;

    /// Batched single-token decode attention. Fields:
    /// `[layer_idx, count, seq_or_kv_pair_0, seq_or_kv_pair_1, ...]`.
    /// Encoding of the variable-length `data` field follows
    /// `cpp_src/instructions.hpp::AttentionDecode`.
    pub const ATTENTION_DECODE: u16 = 4;

    /// o_proj gemm + add to residual stream. matmul shape.
    pub const O_PROJ_RESIDUAL: u16 = 5;

    /// rmsnorm before MLP. Same shape as `ATTN_NORM`.
    pub const MLP_NORM: u16 = 6;

    /// gate_proj gemm + silu activation. matmul shape.
    pub const GATE_SILU: u16 = 7;

    /// up_proj gemm; multiplies by gate_silu output as part of the
    /// kernel. matmul shape.
    pub const UP_MATMUL: u16 = 8;

    /// down_proj gemm + add to residual. matmul shape.
    pub const DOWN_PROJ_RESIDUAL: u16 = 9;

    /// final rmsnorm before lm_head. norm shape.
    pub const LM_HEAD_NORM: u16 = 10;

    /// lm_head gemm. matmul shape.
    pub const LM_HEAD: u16 = 11;

    /// Increment a CPU-visible per-step barrier counter — used by
    /// the on-GPU megakernel to signal phase completion. Lowered
    /// to a no-op on the host interpreter (Rust drives the phases
    /// directly).
    pub const INC_BARRIER: u16 = 12;

    /// Cleanly terminate the persistent grid (megakernel only).
    /// Host interpreter ignores it.
    pub const DIE: u16 = 13;

    /// All-device synchronization point (multi-GPU megakernel
    /// only). Host interpreter ignores it for single-device.
    pub const ALL_DEVICE_BARRIER: u16 = 14;

    /// Free a slot in the runtime tile table. Emitted by the
    /// drop-pass after the last reader of a slot. Field 0 = slot
    /// index. The interpreter calls `tiles[slot] = None`, which
    /// drops the `OwnedTensor` (or `View` indirection) and returns
    /// any owned GPU memory to the caching allocator. Megakernel
    /// targets ignore this opcode (memory management is internal
    /// to the persistent kernel).
    ///
    /// 0xFF range reserved for runtime-only opcodes that have no
    /// corresponding compute. Compute opcodes stay in 0..127.
    pub const FREE: u16 = 0xFF;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instruction_layout_matches_kvm() {
        // 32 i32 words = 128 bytes per instruction. Locked by the
        // wire format; a megakernel binary that reads `(N, 32)`
        // int32 tensors must see the same layout.
        assert_eq!(std::mem::size_of::<Instruction>(), 128);
        assert_eq!(std::mem::align_of::<Instruction>(), 4);
        assert_eq!(INTS_PER_INSTRUCTION, 32);
    }

    #[test]
    fn opcode_decodes_from_slot_zero() {
        let instr = Instruction::new(opcode::ATTN_NORM, [0; 31]);
        assert_eq!(instr.opcode(), opcode::ATTN_NORM);
    }

    #[test]
    fn fields_indexed_from_slot_one() {
        let mut fields = [0i32; 31];
        fields[0] = 7; // layer_idx
        fields[1] = 3; // count
        fields[2] = 100; // batch_indices[0]
        fields[3] = 101;
        fields[4] = 102;
        let instr = Instruction::new(opcode::ATTN_NORM, fields);
        assert_eq!(instr.field(0), 7);
        assert_eq!(instr.field(1), 3);
        assert_eq!(instr.fields_slice(2, 3), &[100, 101, 102]);
    }

    #[test]
    fn noop_is_all_zero() {
        let n = Instruction::noop();
        assert_eq!(n.opcode(), opcode::NOOP);
        assert!(n.0.iter().all(|&w| w == 0));
    }

    /// All llama opcode constants are distinct. Trivial check, but
    /// guards against copy-paste collisions when new ones are
    /// added.
    #[test]
    fn opcodes_are_distinct() {
        let codes = [
            opcode::NOOP,
            opcode::ATTN_NORM,
            opcode::QKV_ROPE_APPEND,
            opcode::ATTENTION_PREFILL,
            opcode::ATTENTION_DECODE,
            opcode::O_PROJ_RESIDUAL,
            opcode::MLP_NORM,
            opcode::GATE_SILU,
            opcode::UP_MATMUL,
            opcode::DOWN_PROJ_RESIDUAL,
            opcode::LM_HEAD_NORM,
            opcode::LM_HEAD,
            opcode::INC_BARRIER,
            opcode::DIE,
            opcode::ALL_DEVICE_BARRIER,
            opcode::FREE,
        ];
        let mut seen = std::collections::HashSet::new();
        for c in codes {
            assert!(seen.insert(c), "duplicate opcode {c}");
        }
    }

    /// Layout defaults match KVM tp_throughput so a host run and
    /// megakernel run produce byte-identical instruction lists.
    #[test]
    fn layout_default_matches_tp_throughput() {
        let l = Layout::TP_THROUGHPUT_DEFAULT;
        assert_eq!(l.matmul_batch_block_size, 128);
        assert_eq!(l.matmul_output_block_size, 256);
        assert_eq!(l.prefill_block_size, 16);
        assert_eq!(l.page_size, 128);
    }
}
