[package]
name = "ptx-fusion"
version.workspace = true
edition.workspace = true

[features]
cuda = ["dep:cudarc", "dep:half"]

[dependencies]
ptx-fusion-macros = { path = "../ptx-fusion-macros" }
cudarc = { workspace = true, optional = true, features = ["dynamic-linking", "cublas"] }
half = { workspace = true, optional = true }
