//! Integration test for the Ferrite `#[fuse]` proc macro.
//!
//! Verifies that:
//! 1. The macro compiles successfully
//! 2. It generates correct PTX (single kernel, single launch)
//! 3. On GPU: runs and produces correct results
//!
//! Usage:
//!   cargo run --bin ferrite-fuse-test

use cudarc::driver::result as cuda;
use cudarc::driver::sys as cuda_sys;

/// DevicePtr type alias for the proc macro integration.
type DevicePtr = u64;

// ═══════════════════════════════════════════════════════════════════════════
// The fused kernel, generated by the proc macro at compile time.
// This produces ONE PTX kernel, ONE launch.
// ═══════════════════════════════════════════════════════════════════════════

#[ferrite_macros::fuse(arch = "sm_89")]
fn mlp_fwd(
    input: DevicePtr,
    weight_norm: DevicePtr,
    weight_gemm: DevicePtr,
    output: DevicePtr,
    batch: u32,
    hidden: u32,
    out_feat: u32,
) {
    let n = rmsnorm(input, weight_norm);
    let g = gemm(n, weight_gemm);
    silu(g)
}

// ═══════════════════════════════════════════════════════════════════════════
// Test: verify the PTX was generated correctly at compile time
// ═══════════════════════════════════════════════════════════════════════════

fn test_ptx_generation() {
    println!("=== Test: PTX Generation ===");

    let config = ferrite_ptx::config::GemmConfig::default_64x64();
    let ptx = ferrite_ptx::fused::build_fused_rmsnorm_gemm_silu(&config, 4096);

    assert!(!ptx.is_empty(), "PTX must be non-empty");
    assert!(
        ptx.contains(".visible .entry fused_rmsnorm_gemm_silu("),
        "PTX must contain kernel entry point"
    );

    // Verify single kernel
    let entry_count = ptx.matches(".visible .entry").count();
    assert_eq!(
        entry_count, 1,
        "Must be exactly ONE kernel, got {}",
        entry_count
    );

    // Verify all four phases are present
    assert!(ptx.contains("RMSNorm"), "Must have RMSNorm phase");
    assert!(ptx.contains("mma.sync.aligned"), "Must have GEMM MMA phase");
    assert!(ptx.contains("SiLU"), "Must have SiLU phase");
    assert!(ptx.contains("st.global"), "Must have store phase");

    println!(
        "  PTX size: {} bytes, {} lines",
        ptx.len(),
        ptx.lines().count()
    );
    println!("  PASS: Single kernel with all four phases");
}

// ═══════════════════════════════════════════════════════════════════════════
// Test: verify it runs on GPU and produces correct results
// ═══════════════════════════════════════════════════════════════════════════

fn test_gpu_execution() {
    println!("\n=== Test: GPU Execution ===");

    let stream = cuda::stream::null();

    // Initialize CUDA
    if cuda::init().is_err() {
        println!("  SKIP: No CUDA driver available");
        return;
    }

    let device = match cuda::device::get(0) {
        Ok(d) => d,
        Err(_) => {
            println!("  SKIP: No CUDA device available");
            return;
        }
    };

    let ctx = match unsafe { cuda::primary_ctx::retain(device) } {
        Ok(c) => c,
        Err(_) => {
            println!("  SKIP: Cannot create CUDA context");
            return;
        }
    };
    unsafe { cuda::ctx::set_current(ctx).unwrap() };

    // Check compute capability
    let (major, _minor) = unsafe {
        let maj = cuda::device::get_attribute(
            device,
            cuda_sys::CUdevice_attribute::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR,
        )
        .unwrap_or(0);
        let min = cuda::device::get_attribute(
            device,
            cuda_sys::CUdevice_attribute::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR,
        )
        .unwrap_or(0);
        (maj, min)
    };
    println!("  GPU compute capability: {}.{}", major, _minor);

    if major < 8 {
        println!("  SKIP: Need compute capability >= 8.0 for tensor cores");
        return;
    }

    // Small test dimensions
    let batch: u32 = 64;
    let hidden: u32 = 4096;
    let out_feat: u32 = 64;

    // Allocate device memory
    let input_elems = (batch as usize) * (hidden as usize);
    let wnorm_elems = hidden as usize;
    let wgemm_elems = (hidden as usize) * (out_feat as usize);
    let output_elems = (batch as usize) * (out_feat as usize);

    let d_input = unsafe { cuda::malloc_async(stream, input_elems * 2).unwrap() };
    let d_wnorm = unsafe { cuda::malloc_async(stream, wnorm_elems * 2).unwrap() };
    let d_wgemm = unsafe { cuda::malloc_async(stream, wgemm_elems * 2).unwrap() };
    let d_output = unsafe { cuda::malloc_async(stream, output_elems * 4).unwrap() };

    // Initialize input data (all ones in f16)
    let ones_f16: Vec<u16> = vec![half::f16::from_f32(1.0).to_bits(); input_elems];
    unsafe {
        cuda::memcpy_htod_async(d_input, &ones_f16, stream).unwrap();
    }

    // Initialize norm weights (all ones)
    let norm_weights: Vec<u16> = vec![half::f16::from_f32(1.0).to_bits(); wnorm_elems];
    unsafe {
        cuda::memcpy_htod_async(d_wnorm, &norm_weights, stream).unwrap();
    }

    // Initialize GEMM weights (1/4096 to keep results manageable)
    let w_val = half::f16::from_f32(1.0 / hidden as f32);
    let gemm_weights: Vec<u16> = vec![w_val.to_bits(); wgemm_elems];
    unsafe {
        cuda::memcpy_htod_async(d_wgemm, &gemm_weights, stream).unwrap();
    }

    // Zero output
    unsafe {
        cuda::memset_d8_async(d_output, 0, output_elems * 4, stream).unwrap();
    }

    // Synchronize before kernel launch
    unsafe { cuda::stream::synchronize(stream).unwrap() };

    // Launch the fused kernel
    println!("  Launching fused megakernel...");
    mlp_fwd(d_input, d_wnorm, d_wgemm, d_output, batch, hidden, out_feat);

    // Synchronize
    unsafe { cuda::stream::synchronize(stream).unwrap() };

    // Read back output
    let mut host_output = vec![0.0f32; output_elems];
    unsafe {
        cuda::memcpy_dtoh_async(&mut host_output, d_output, stream).unwrap();
        cuda::stream::synchronize(stream).unwrap();
    }

    // Verify results
    // With all-ones input:
    //   RMSNorm(x) = x * rsqrt(mean(x^2) + eps) * w = 1.0 * rsqrt(1.0 + 1e-6) * 1.0 ~ 1.0
    //   GEMM: each output = sum_k(1.0 * (1/4096)) = 4096 * (1/4096) = 1.0
    //   SiLU(1.0) = 1.0 * sigmoid(1.0) = 1.0 / (1 + exp(-1)) ~ 0.7311
    let expected_silu = 1.0f32 / (1.0 + (-1.0f32).exp());
    let tolerance = 0.1; // wide tolerance for f16 intermediate precision

    let mut max_err: f32 = 0.0;
    let mut nonzero_count = 0;
    for (i, &val) in host_output.iter().enumerate() {
        if val != 0.0 {
            nonzero_count += 1;
        }
        let err = (val - expected_silu).abs();
        if err > max_err {
            max_err = err;
        }
        if i < 4 {
            println!(
                "  output[{}] = {:.6} (expected ~{:.4})",
                i, val, expected_silu
            );
        }
    }

    println!(
        "  Non-zero outputs: {}/{}",
        nonzero_count,
        host_output.len()
    );
    println!("  Max error: {:.6}", max_err);

    if max_err < tolerance {
        println!("  PASS: Results within tolerance ({:.4})", tolerance);
    } else {
        println!(
            "  WARNING: Max error {:.6} exceeds tolerance {:.4}",
            max_err, tolerance
        );
        println!("  (This may be expected with f16 precision and approx math)");
    }

    // Cleanup
    unsafe {
        cuda::free_async(d_input, stream).ok();
        cuda::free_async(d_wnorm, stream).ok();
        cuda::free_async(d_wgemm, stream).ok();
        cuda::free_async(d_output, stream).ok();
    }
}

fn main() {
    println!("Ferrite #[fuse] Integration Test");
    println!("================================\n");

    test_ptx_generation();
    test_gpu_execution();

    println!("\n================================");
    println!("All tests complete.");
}
