// SPDX-License-Identifier: Apache-2.0
//
// Per-canonical `MKGlobals` struct shape. The macro generates the
// concrete struct (with shape const generics pinned at instantiation)
// inside the per-canonical .cu, but the field categories live here so
// every per-IType .cuh can name them uniformly.
//
// The runtime host shim packs this struct from
// `ferrite_forward::wavefront_cuda::dispatch_cuda` and passes it as the
// kernel's `__grid_constant__` argument (well under the 32 KB const-
// memory bound — 25 typed `gl<>` × ~64 bytes each ≈ 1.6 KB).

#pragma once

#include "kittens.cuh"
#include "instruction.cuh"

namespace ferrite_mk {

// Tensor-kind enum — discriminator that `instruction_t::tensor_ref_t::
// tensor_kind` selects on. New ITypes that need new `gl<>` slots add
// entries here; the per-canonical macro emits a switch on this enum
// to pick the right `gl<>` from MKGlobals.
enum TensorKind : uint32_t {
    TK_HIDDEN_RESIDUAL_A   = 0,   // ping-pong residual stream A
    TK_HIDDEN_RESIDUAL_B   = 1,   // ping-pong residual stream B
    TK_RMS_NORM_WEIGHT     = 2,
    TK_LINEAR_WEIGHT_QKV   = 3,
    TK_LINEAR_WEIGHT_O     = 4,
    TK_LINEAR_WEIGHT_GATE  = 5,
    TK_LINEAR_WEIGHT_UP    = 6,
    TK_LINEAR_WEIGHT_DOWN  = 7,
    TK_LINEAR_WEIGHT_LM    = 8,
    TK_EMBEDDING_TABLE     = 9,
    TK_COS_TABLE           = 10,
    TK_SIN_TABLE           = 11,
    TK_KV_CACHE_K          = 12,
    TK_KV_CACHE_V          = 13,
    TK_BLOCK_TABLE         = 14,
    TK_SLOT_MAPPING        = 15,
    TK_POSITIONS           = 16,
    TK_ATTN_PARTIAL        = 17,
    TK_LOGITS_OUT          = 18,
    TK_INSTRUCTIONS        = 19,
    TK_BARRIER_TABLE       = 20,
    TK_KIND_COUNT
};

// `MKGlobals_<canonical>` is generated by Rust codegen.rs per
// canonical. The struct's body contains one typed `kittens::gl<...>`
// member per TensorKind that the canonical's lowered ops actually
// touch. Layout always begins with:
//   kittens::gl<instruction_t, -1 /*sm*/, -1 /*queue_len*/, 1, 1>
//       instructions;
//   uint64_t* barrier_table;  // device-side atomic counters
//   int32_t  num_layers, hidden_size, intermediate_size, ...;
// followed by per-canonical typed weight + activation + KV gl<>s.
//
// Phase 0: this header is #include-able and provides the TensorKind
// enum. Concrete MKGlobals_<canonical> struct bodies land in Phase 4
// when the macro starts emitting fused-IType kernels.

}  // namespace ferrite_mk
