// SPDX-License-Identifier: Apache-2.0
//! `gpu_cost_sweep` — the calibration entrypoint for a new GPU.
//!
//! Emits `kernel,M,N,K,cost_us` rows to stdout. Pipe into
//! `target_profiles/cost_<gpu>.csv` so the ferrite solver's
//! `CostTable` can score the calibrated kernels per workload.
//!
//! Two sweep families run back-to-back from `main`:
//!   1. [`gemm_sweep`] — cuBLAS + every CUTLASS tile variant in
//!      `ferrite_kernels::cutlass::CUTLASS_TILE_ZOO` + GEMV at M=1 +
//!      fused CUTLASS SiLU×Mul, across a dense `(M, N, K)` grid
//!      covering LLaMA 1B through 70B shapes. Ports the pre-refactor
//!      sweep at `ferrite-test-harness/tests/gpu_cost_sweep.rs`
//!      (deleted in commit `5b9fd90ef`, Step G), trimmed to the 17
//!      variants the current `ferrite-forward-macro` solver knows
//!      how to pick.
//!   2. [`attention_sweep`] — stub today; populated in a follow-up
//!      task with the FA2 vs FlashInfer `(M, sk)` sweep feeding the
//!      new `WorkloadPoint { num_tokens, sk_bucket }` solver axis.
//!
//! Usage:
//!   CUDA_PATH=/usr/local/cuda-12.9 \
//!     cargo run -p ferrite-cost-sweep --features cuda --release \
//!     --bin gpu_cost_sweep \
//!     > target_profiles/cost_<gpu>.csv
//!
//! The CSV format is stable (`kernel,M,N,K,cost_us`) and consumed by
//! `ferrite_forward_macro::target::CostTable::load_csv`. New kernel
//! families widen the row space by encoding extra dims into the
//! `kernel` name (e.g. the attention sweep uses names like
//! `flashinfer_attn_decode_bf16_h64_q32_k8`).

#[cfg(not(feature = "cuda"))]
fn main() {
    eprintln!(
        "ferrite-cost-sweep requires the `cuda` feature. Run with: \n\
         cargo run -p ferrite-cost-sweep --features cuda --release --bin gpu_cost_sweep"
    );
    std::process::exit(1);
}

#[cfg(feature = "cuda")]
mod attention_sweep;
#[cfg(feature = "cuda")]
mod gemm_sweep;
#[cfg(feature = "cuda")]
mod util;

#[cfg(feature = "cuda")]
fn main() {
    util::init_cuda();

    // Determine launch-overhead baseline by timing a no-op kernel.
    // All subsequent timings subtract this so each row reports
    // compute-only cost — matches the convention the CSV header
    // documents and the solver's `cost_us_for` expects.
    let launch_overhead_us = util::measure_launch_overhead();

    // CSV header + launch_overhead row. Keep format byte-identical
    // to the pre-refactor sweep so old and new CSVs are mergeable.
    println!("# GPU cost table — generated by gpu_cost_sweep");
    println!("# Launch overhead: {launch_overhead_us:.2} us (subtracted from all timings)");
    println!("# Timings are compute-only. To get wall-clock time for N separate");
    println!("# kernel launches, add N * launch_overhead_us.");
    println!("# Regenerate: cargo run -p ferrite-cost-sweep --features cuda --release");
    println!("kernel,M,N,K,cost_us");
    println!("launch_overhead,0,0,0,{launch_overhead_us:.2}");

    let attn_only = std::env::var("ATTENTION_SWEEP_ONLY").ok().is_some();
    if !attn_only {
        gemm_sweep::run(launch_overhead_us);
    }
    attention_sweep::run(launch_overhead_us);

    eprintln!("gpu_cost_sweep: done");
}
