// SPDX-License-Identifier: Apache-2.0
//! Phase 3a-bsp / Phase 3b-bsp: emit a BSP wave-front megakernel.
//!
//! Layout:
//! ```text
//! constexpr uint32_t NUM_WAVES;
//! constexpr uint32_t NUM_CTAS;
//! constexpr uint32_t NUM_NODES;   // for sizing the validation tick array
//!
//! struct TileOp { phase, layer, row, col };          // 12 B (with padding 16)
//! __device__ const TileOp WAVE_OPS[N_OPS_TOTAL];     // packed: per wave, per CTA, in order
//! __device__ const uint32_t WAVE_CTA_OFFSETS[
//!     NUM_WAVES * (NUM_CTAS + 1)];                   // prefix-sum table
//! __device__ const uint32_t NODE_ID_FOR_OP[N_OPS_TOTAL]; // parallel to WAVE_OPS, for tick stamping
//! ```
//!
//! Per CTA per wave: stream of TileOp records contiguous in WAVE_OPS, indexed
//! via WAVE_CTA_OFFSETS[wave * (NUM_CTAS+1) + cta..+ cta+1]. Sequential read
//! → L1/L2 hot. After each wave, all CTAs participate in one grid barrier
//! (atomic-counter style) before moving to the next.

use std::fmt::Write as _;

use crate::reified_dag::{Phase, ReifiedDag};
use crate::schedule::WaveSchedule;

/// Numeric phase tag matching the C++ enum.
pub fn phase_tag(p: Phase) -> u32 {
    match p {
        Phase::AttnNorm => 0,
        Phase::Qkv => 1,
        Phase::Rope => 2,
        Phase::Attention => 3,
        Phase::OProj => 4,
        Phase::MlpNorm => 5,
        Phase::GateUp => 6,
        Phase::Down => 7,
    }
}

/// Render the wave program as a CUDA include chunk.
pub fn emit_wave_schedule_cpp(dag: &ReifiedDag, sched: &WaveSchedule) -> String {
    let n = dag.nodes.len();
    let num_ctas = sched.num_ctas as usize;
    let num_waves = sched.waves.len();

    // ── Pack the per-wave per-CTA op streams into one flat array. ──
    // Layout order: wave 0 / cta 0, cta 1, ..., cta N-1; wave 1 / cta 0, ...
    let mut ops: Vec<(
        u32, /*phase*/
        u32, /*layer*/
        u32, /*row*/
        u32, /*col*/
    )> = Vec::with_capacity(n);
    let mut node_ids: Vec<u32> = Vec::with_capacity(n);
    let offsets_len = num_waves * (num_ctas + 1);
    let mut wave_cta_offsets: Vec<u32> = Vec::with_capacity(offsets_len);

    let mut cursor: u32 = 0;
    for wave in &sched.waves {
        for cta in 0..num_ctas {
            wave_cta_offsets.push(cursor);
            for nid in &wave.cta_nodes[cta] {
                let nd = &dag.nodes[nid.0 as usize];
                ops.push((
                    phase_tag(nd.phase),
                    nd.layer as u32,
                    nd.row as u32,
                    nd.col as u32,
                ));
                node_ids.push(nid.0);
                cursor += 1;
            }
        }
        // Sentinel "end of last cta in this wave" for clean range queries.
        wave_cta_offsets.push(cursor);
    }
    debug_assert_eq!(cursor as usize, n);
    debug_assert_eq!(
        wave_cta_offsets.len(),
        num_waves * (num_ctas + 1),
        "offset table size"
    );

    // ── Emit ──
    let mut out = String::new();
    writeln!(
        out,
        "// AUTO-GENERATED by scheduled_codegen.rs — do not edit."
    )
    .unwrap();
    writeln!(
        out,
        "// {} nodes, {} waves, {} CTAs",
        n, num_waves, num_ctas
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#pragma once").unwrap();
    writeln!(out, "#include <cstdint>").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "namespace pfl_sched {{").unwrap();
    writeln!(out, "constexpr uint32_t NUM_NODES = {};", n).unwrap();
    writeln!(out, "constexpr uint32_t NUM_WAVES = {};", num_waves).unwrap();
    writeln!(out, "constexpr uint32_t NUM_CTAS  = {};", num_ctas).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Phase tags").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ATTN_NORM = 0;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_QKV       = 1;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ROPE      = 2;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ATTENTION = 3;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_O_PROJ    = 4;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_MLP_NORM  = 5;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_GATE_UP   = 6;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_DOWN      = 7;").unwrap();
    writeln!(out).unwrap();

    // 16-byte TileOp (4 u32s — phase + layer + row + col). u32 layer/row/col
    // is plenty for any model we'll target and keeps the struct nicely aligned.
    writeln!(
        out,
        "struct TileOp {{\n  \
           uint32_t phase;\n  \
           uint32_t layer;\n  \
           uint32_t row;\n  \
           uint32_t col;\n\
         }};\n\
         static_assert(sizeof(TileOp) == 16, \"TileOp layout drifted\");"
    )
    .unwrap();
    writeln!(out).unwrap();

    // WAVE_OPS — flat array of TileOps.
    writeln!(
        out,
        "static __device__ const TileOp WAVE_OPS[NUM_NODES] = {{"
    )
    .unwrap();
    for (phase, layer, row, col) in &ops {
        writeln!(out, "  {{ {}, {}, {}, {} }},", phase, layer, row, col).unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    // NODE_ID_FOR_OP — parallel to WAVE_OPS so each CTA can stamp the right
    // tick slot in the validation array.
    writeln!(
        out,
        "static __device__ const uint32_t NODE_ID_FOR_OP[NUM_NODES] = {{"
    )
    .unwrap();
    emit_u32_chunked(&mut out, &node_ids);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    // WAVE_CTA_OFFSETS — flattened (NUM_WAVES * (NUM_CTAS+1)) prefix table.
    writeln!(
        out,
        "static __device__ const uint32_t WAVE_CTA_OFFSETS[NUM_WAVES * (NUM_CTAS + 1)] = {{"
    )
    .unwrap();
    emit_u32_chunked(&mut out, &wave_cta_offsets);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "}}  // namespace pfl_sched").unwrap();

    out
}

fn emit_u32_chunked(out: &mut String, vals: &[u32]) {
    const PER_LINE: usize = 16;
    for chunk in vals.chunks(PER_LINE) {
        out.push_str("  ");
        for v in chunk {
            write!(out, "{},", v).unwrap();
        }
        out.push('\n');
    }
}

/// Phase 3b-bsp — emit a complete `.cu` file containing the wave program
/// data + tile bodies (real where implemented, placeholder where not) +
/// grid-barrier megakernel + extern "C" launch helper.
///
/// `kv_page_size` is the slots-per-page for the paged KV cache. Pages-per-
/// layer is derived as ceil(seq_len / kv_page_size).
///
/// `name` is appended to the namespace and to all extern "C" symbols so
/// multiple variants can coexist in the same translation-unit batch:
///   namespace pfl_sched_<name>
///   extern "C" void launch_scheduled_megakernel_<name>(...)
///   extern "C" unsigned scheduled_megakernel_<name>_num_nodes()
///   etc.
pub fn emit_scheduled_megakernel_cu(
    dag: &ReifiedDag,
    sched: &WaveSchedule,
    kv_page_size: u32,
    name: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&emit_wave_schedule_cpp(dag, sched));
    // Bake the model dims as compile-time constants so tile bodies can index
    // gmem buffers without an extra struct field per dim.
    writeln!(out, "namespace pfl_sched {{").unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_NUM_LAYERS    = {};",
        dag.dims.num_layers
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_HIDDEN_DIM    = {};",
        dag.dims.hidden_dim
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_INTERMEDIATE  = {};",
        dag.dims.intermediate_dim
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_NUM_ATTN_H    = {};",
        dag.dims.num_attn_heads
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_NUM_KV_H      = {};",
        dag.dims.num_kv_heads
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_HEAD_DIM      = {};",
        dag.dims.head_dim
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_SEQ_LEN       = {};",
        dag.dims.seq_len
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_ROW_TILE      = {};",
        dag.tiles.row_tile
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_QKV_COL_TILE  = {};",
        dag.tiles.qkv_col_tile
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_O_COL_TILE    = {};",
        dag.tiles.o_col_tile
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_GATE_UP_COL_TILE = {};",
        dag.tiles.gate_up_col_tile
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_DOWN_COL_TILE = {};",
        dag.tiles.down_col_tile
    )
    .unwrap();
    let pages_per_layer = dag.dims.seq_len.div_ceil(kv_page_size);
    writeln!(
        out,
        "constexpr uint32_t MODEL_KV_PAGE_SIZE  = {};",
        kv_page_size
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_PAGES_PER_LAYER = {};",
        pages_per_layer
    )
    .unwrap();
    writeln!(out, "}}  // namespace pfl_sched").unwrap();
    out.push_str(KERNEL_BODY);

    // ── Per-variant rename pass ──
    // The kernel template is written with the literal namespace `pfl_sched`
    // and the literal extern-"C" symbol root `scheduled_megakernel`. To make
    // multiple variants coexist in the same translation-unit batch, suffix
    // them with `_<name>`. Order matters: rename the namespace first so the
    // symbol-root rename doesn't accidentally match `pfl_sched_*` substrings.
    let ns_old = "pfl_sched";
    let ns_new = format!("pfl_sched_{name}");
    let sym_old = "scheduled_megakernel";
    let sym_new = format!("scheduled_megakernel_{name}");
    out.replace(ns_old, &ns_new).replace(sym_old, &sym_new)
}

const KERNEL_BODY: &str = r#"
// ──────────────────────────────────────────────────────────────────────
// Phase 3c (in progress): scheduled BSP megakernel.
// Real tile bodies for phases that have been ported. Placeholders elsewhere.
// ──────────────────────────────────────────────────────────────────────

#include <cuda_runtime.h>
#include <cuda_bf16.h>
#include <mma.h>
#include <cstdio>

namespace pfl_sched {

// Activation + weight pointers the tile bodies need. Pointers are typed as
// __nv_bfloat16* because that's what the existing fused kernel uses.
struct globals_t {
    // Activations (all bf16, all [seq_len, dim] row-major unless noted)
    __nv_bfloat16* hidden_states;  // [seq, HIDDEN_DIM]
    __nv_bfloat16* rms_rope;       // [seq, HIDDEN_DIM]  — output of attn_norm
    __nv_bfloat16* qkv;            // [seq, qkv_dim]      — output of qkv gemm
    __nv_bfloat16* q_post_rope;    // [seq, NAH * HEAD_DIM] — Q after rope
    __nv_bfloat16* attn_out;       // [seq, HIDDEN_DIM]
    __nv_bfloat16* rms_gate;       // [seq, HIDDEN_DIM]
    __nv_bfloat16* silu_out;       // [seq, INTERMEDIATE]
    // Paged KV cache. Layout matches the existing fused prefill kernel:
    //   [num_layers * pages_per_layer, page_size, num_kv_heads, head_dim]
    // Indexed as cache[page_idx * page_size * nkh * hd + slot * nkh * hd
    //                  + kv_head * hd + d]
    // where page_idx = prefill_kv_indices[token_pos / page_size]
    //                  + layer * pages_per_layer
    //       slot     = token_pos % page_size
    __nv_bfloat16* k_cache;
    __nv_bfloat16* v_cache;
    // Block table + indptrs (single sequence for the test fixture).
    const int32_t* prefill_kv_indices; // [pages_per_layer]
    const int32_t* prefill_kv_indptr;  // [num_seqs + 1]
    const int32_t* prefill_qo_indptr;  // [num_seqs + 1]
    // Norm weights, per layer.
    __nv_bfloat16* attn_norm_w;    // [num_layers, HIDDEN_DIM]
    __nv_bfloat16* mlp_norm_w;     // [num_layers, HIDDEN_DIM]
    // GEMM weights, per layer.
    __nv_bfloat16* qkv_w;          // [num_layers, qkv_dim, HIDDEN_DIM]
    __nv_bfloat16* o_w;             // [num_layers, HIDDEN_DIM, HIDDEN_DIM]
    __nv_bfloat16* gate_w;          // [num_layers, INTERMEDIATE, HIDDEN_DIM]
    __nv_bfloat16* up_w;            // [num_layers, INTERMEDIATE, HIDDEN_DIM]
    __nv_bfloat16* down_w;          // [num_layers, HIDDEN_DIM, INTERMEDIATE]
    float          eps;
    float          attn_scale;     // = 1 / sqrt(HEAD_DIM)
};

// Per-node validation slot. The kernel writes a monotonic tick into
// `flags[node_id]` at the moment the node executes; the host then checks
// that every node ran exactly once and that ticks respect topological order.
struct SchedRuntime {
    unsigned int* flags;           // [NUM_NODES]
    unsigned int* tick_counter;    // [1]
    unsigned int* barrier_arrived; // [1]
};

// ── tile_attn_norm: real RMS norm. Reads hidden_states, writes rms_rope. ──
//
// Per-row formula: y[c] = x[c] * w[c] / sqrt(mean(x^2) + eps)
//
// Runs on warp 0 only (32 threads). Other warps idle until the next
// __syncthreads. Each row: warp-shuffle reduction over HIDDEN_DIM, then
// writeback. No shmem.
__device__ __forceinline__ void tile_attn_norm(const globals_t& g, uint32_t layer, uint32_t row) {
    if (threadIdx.x >= 32) return;
    constexpr uint32_t HD       = MODEL_HIDDEN_DIM;
    constexpr uint32_t ROW_TILE = MODEL_ROW_TILE;
    const uint32_t row_start = row * ROW_TILE;
    const __nv_bfloat16* w = g.attn_norm_w + (size_t)layer * HD;
    const uint32_t lane = threadIdx.x;  // 0..31

    #pragma unroll 1
    for (uint32_t r = 0; r < ROW_TILE; ++r) {
        const uint32_t row_idx = row_start + r;
        if (row_idx >= MODEL_SEQ_LEN) break;
        const __nv_bfloat16* x = g.hidden_states + (size_t)row_idx * HD;
        __nv_bfloat16*       y = g.rms_rope      + (size_t)row_idx * HD;

        // ── Reduction: sum of squares across HIDDEN_DIM ──
        float my_sum = 0.0f;
        for (uint32_t c = lane; c < HD; c += 32) {
            float v = __bfloat162float(x[c]);
            my_sum += v * v;
        }
        // Warp shuffle reduction.
        for (int offset = 16; offset > 0; offset >>= 1) {
            my_sum += __shfl_xor_sync(0xffffffff, my_sum, offset);
        }
        const float scale = rsqrtf(my_sum / float(HD) + g.eps);

        // ── Writeback: y[c] = x[c] * scale * w[c] ──
        for (uint32_t c = lane; c < HD; c += 32) {
            float xv = __bfloat162float(x[c]);
            float wv = __bfloat162float(w[c]);
            y[c] = __float2bfloat16(xv * scale * wv);
        }
    }
}

// K-block size for shmem-staged wmma. The K dim is processed in chunks of
// this size; each chunk is loaded gmem→shmem cooperatively (256 threads)
// then consumed by 8 warps × (K_BLOCK/WMMA_K) wmma calls. Larger blocks
// amortize the gmem load cost over more compute but cost more shmem.
constexpr uint32_t SHMEM_GEMM_K_BLOCK = 32;

// Single CTA-wide shmem arena reused across tile bodies. Wave scheduling
// guarantees only one tile body runs at a time per CTA, so all tile
// bodies that need shmem share this arena and partition it locally.
//
// Sized for the worst case (tile_gate_up with two B operands + two
// accumulator scratches):
//   a_smem        = M × KB × 2 = 16 × 32 × 2  = 1024 B
//   b_gate_smem   = N × KB × 2 = 128 × 32 × 2 = 8192 B
//   b_up_smem     = N × KB × 2 = 128 × 32 × 2 = 8192 B
//   gate_scratch  = NW × WMMA_M × WMMA_N × 4   = 8192 B
//   up_scratch    = NW × WMMA_M × WMMA_N × 4   = 8192 B
//   total                                       = 33792 B
// Rounded up to 36 KiB for headroom. Still well within the 48 KiB
// default sm89 carveout.
constexpr uint32_t TILE_SHMEM_BYTES = 36 * 1024;

// ── tile_qkv: shmem-staged tensor-core GEMM. ──
//
// M=ROW_TILE=16, N=QKV_COL_TILE=128, K=HIDDEN_DIM.
//
// Each K_BLOCK iteration:
//   1. Cooperative gmem→shmem load of A[0:M, k:k+K_BLOCK] and
//      B[col_start:col_start+N, k:k+K_BLOCK] (256 threads, coalesced).
//   2. Each warp does K_BLOCK/16 wmma calls reading from shmem on its
//      16-col slice of the output.
//
// fp32 accumulator stays in registers across the full K. Per-warp 16×16
// fp32 scratch in shmem stages the bf16 writeback. All shmem comes from
// the kernel-scope arena passed via `tile_smem`.
__device__ __forceinline__ void tile_qkv(
    const globals_t& g, uint32_t layer, uint32_t row, uint32_t col, char* tile_smem)
{
    using namespace nvcuda::wmma;
    constexpr uint32_t M            = MODEL_ROW_TILE;
    constexpr uint32_t K            = MODEL_HIDDEN_DIM;
    constexpr uint32_t N            = MODEL_QKV_COL_TILE;
    constexpr uint32_t QKV_DIM_FULL = (MODEL_NUM_ATTN_H + 2 * MODEL_NUM_KV_H) * MODEL_HEAD_DIM;
    constexpr uint32_t WMMA_M       = 16;
    constexpr uint32_t WMMA_N       = 16;
    constexpr uint32_t WMMA_K       = 16;
    constexpr uint32_t N_WARPS      = 8;
    constexpr uint32_t N_PER_WARP   = N / N_WARPS;
    constexpr uint32_t KB           = SHMEM_GEMM_K_BLOCK;
    static_assert(M == WMMA_M, "tile_qkv assumes M == 16");
    static_assert(N % (WMMA_N * N_WARPS) == 0, "tile_qkv: N must be 8*16 multiple");
    static_assert(K % KB == 0, "tile_qkv: K must be a multiple of KB");
    static_assert(KB % WMMA_K == 0, "tile_qkv: KB must be a multiple of 16");
    static_assert(N_PER_WARP == 16, "tile_qkv: each warp owns one 16-col slice");

    const uint32_t row_start = row * M;
    const uint32_t col_start = col * N;
    if (row_start >= MODEL_SEQ_LEN) return;

    const __nv_bfloat16* A_base = g.rms_rope + (size_t)row_start * K;
    const __nv_bfloat16* B_base = g.qkv_w
        + (size_t)layer * QKV_DIM_FULL * K
        + (size_t)col_start * K;
    __nv_bfloat16* C_base = g.qkv + (size_t)row_start * QKV_DIM_FULL + col_start;

    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t n_warp_start = warp_id * N_PER_WARP;
    const uint32_t lane = threadIdx.x;

    // Partition the kernel-scope shmem arena.
    __nv_bfloat16* a_smem = reinterpret_cast<__nv_bfloat16*>(tile_smem);
    __nv_bfloat16* b_smem = a_smem + M * KB;
    float* qkv_scratch = reinterpret_cast<float*>(b_smem + N * KB);
    float* my_scratch = qkv_scratch + (size_t)warp_id * WMMA_M * WMMA_N;

    fragment<matrix_a, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, row_major> a_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> c_frag;
    fill_fragment(c_frag, 0.0f);

    #pragma unroll 1
    for (uint32_t k_outer = 0; k_outer < K; k_outer += KB) {
        // ── Cooperative gmem→shmem load of A[0:M, k_outer:k_outer+KB] ──
        // M*KB elements, 256 threads → (M*KB/256) per thread.
        for (uint32_t i = lane; i < M * KB; i += 256) {
            const uint32_t m = i / KB;
            const uint32_t k_local = i % KB;
            a_smem[m * KB + k_local] = A_base[m * K + k_outer + k_local];
        }
        // ── Cooperative gmem→shmem load of B[col_start:col_start+N, k_outer:k_outer+KB] ──
        for (uint32_t i = lane; i < N * KB; i += 256) {
            const uint32_t n = i / KB;
            const uint32_t k_local = i % KB;
            b_smem[n * KB + k_local] = B_base[(size_t)n * K + k_outer + k_local];
        }
        __syncthreads();

        // ── wmma over the K_BLOCK from shmem ──
        #pragma unroll
        for (uint32_t k_inner = 0; k_inner < KB; k_inner += WMMA_K) {
            load_matrix_sync(a_frag, a_smem + k_inner, KB);
            load_matrix_sync(b_frag,
                             b_smem + (size_t)n_warp_start * KB + k_inner,
                             KB);
            mma_sync(c_frag, a_frag, b_frag, c_frag);
        }
        __syncthreads();
    }

    store_matrix_sync(my_scratch, c_frag, WMMA_N, mem_row_major);
    __syncthreads();

    // Cooperative bf16 writeback across all 256 threads.
    const uint32_t total = M * N;
    for (uint32_t idx = lane; idx < total; idx += 256) {
        const uint32_t m = idx / N;
        const uint32_t n = idx % N;
        if (row_start + m >= MODEL_SEQ_LEN) continue;
        const uint32_t w = n / N_PER_WARP;
        const uint32_t local_n = n % N_PER_WARP;
        const float v = qkv_scratch[w * WMMA_M * WMMA_N + m * WMMA_N + local_n];
        C_base[m * QKV_DIM_FULL + n] = __float2bfloat16(v);
    }
    __syncthreads();
}


// ── tile_rope: rotate + KV cache append for one ROW_TILE-row tile.
//
// Reads qkv[row, qkv_dim] where qkv_dim = (NAH + 2*NKH) * HEAD_DIM and is
// laid out as [Q (NAH*HDM)][K (NKH*HDM)][V (NKH*HDM)].
//
// Writes:
//   - q_post_rope[row, NAH*HDM]   ← rotated Q heads
//   - k_cache[page_idx, slot, kv_head, d]  ← rotated K heads (paged)
//   - v_cache[page_idx, slot, kv_head, d]  ← passthrough V heads (paged)
//
// page_idx = prefill_kv_indices[row / PAGE_SIZE] + layer * PAGES_PER_LAYER
// slot     = row % PAGE_SIZE
//
// Split-half rotation:
//   x0_new = x0 * cos(θ) - x1 * sin(θ)
//   x1_new = x0 * sin(θ) + x1 * cos(θ)
// where θ = position / 10000^(2c/HDM), c ∈ [0, HDM/2).
//
// 32 threads (one warp). The qkv buffer is NOT modified.
__device__ __forceinline__ void tile_rope(const globals_t& g, uint32_t layer, uint32_t row) {
    if (threadIdx.x >= 32) return;  // warp 0 only
    constexpr uint32_t HDM             = MODEL_HEAD_DIM;
    constexpr uint32_t HALF            = HDM / 2;
    constexpr uint32_t NAH             = MODEL_NUM_ATTN_H;
    constexpr uint32_t NKH             = MODEL_NUM_KV_H;
    constexpr uint32_t QKV_DIM         = (NAH + 2 * NKH) * HDM;
    constexpr uint32_t Q_DIM           = NAH * HDM;
    constexpr uint32_t K_OFF           = NAH * HDM;            // K region offset in qkv row
    constexpr uint32_t V_OFF           = (NAH + NKH) * HDM;    // V region offset in qkv row
    constexpr uint32_t ROW_TILE        = MODEL_ROW_TILE;
    constexpr uint32_t PAGE_SIZE       = MODEL_KV_PAGE_SIZE;
    constexpr uint32_t PAGES_PER_LAYER = MODEL_PAGES_PER_LAYER;
    constexpr uint32_t SLOT_STRIDE     = NKH * HDM;            // bf16 elements
    constexpr uint32_t PAGE_STRIDE     = PAGE_SIZE * NKH * HDM;
    constexpr float    THETA_BASE      = 10000.0f;
    const uint32_t lane = threadIdx.x;
    const uint32_t row_start = row * ROW_TILE;

    #pragma unroll 1
    for (uint32_t r = 0; r < ROW_TILE; ++r) {
        const uint32_t row_idx = row_start + r;
        if (row_idx >= MODEL_SEQ_LEN) break;
        const float pos = float(row_idx);
        const __nv_bfloat16* qkv_row = g.qkv + (size_t)row_idx * QKV_DIM;

        // Paged cache slot for this token.
        const uint32_t logical_page  = row_idx / PAGE_SIZE;
        const uint32_t slot_in_page  = row_idx % PAGE_SIZE;
        const int32_t physical_page  = g.prefill_kv_indices[logical_page]
                                       + (int32_t)layer * (int32_t)PAGES_PER_LAYER;
        const size_t page_off = (size_t)physical_page * PAGE_STRIDE;
        const size_t slot_off = (size_t)slot_in_page * SLOT_STRIDE;
        __nv_bfloat16* k_slot = g.k_cache + page_off + slot_off;
        __nv_bfloat16* v_slot = g.v_cache + page_off + slot_off;

        // ── Q heads: rotate, write to q_post_rope ──
        __nv_bfloat16* q_post = g.q_post_rope + (size_t)row_idx * Q_DIM;
        for (uint32_t h = 0; h < NAH; ++h) {
            const __nv_bfloat16* q_in  = qkv_row + h * HDM;
            __nv_bfloat16*       q_out = q_post  + h * HDM;
            for (uint32_t c = lane; c < HALF; c += 32) {
                const float exp_v   = float(2 * c) / float(HDM);
                const float inv_freq = __powf(THETA_BASE, -exp_v);
                const float ang     = pos * inv_freq;
                float cos_v, sin_v;
                __sincosf(ang, &sin_v, &cos_v);
                const float x0 = __bfloat162float(q_in[c]);
                const float x1 = __bfloat162float(q_in[c + HALF]);
                q_out[c]        = __float2bfloat16(x0 * cos_v - x1 * sin_v);
                q_out[c + HALF] = __float2bfloat16(x0 * sin_v + x1 * cos_v);
            }
        }

        // ── K heads: rotate, write to k_cache[page, slot, kv_head, d] ──
        for (uint32_t h = 0; h < NKH; ++h) {
            const __nv_bfloat16* k_in  = qkv_row + K_OFF + h * HDM;
            __nv_bfloat16*       k_out = k_slot  + h * HDM;
            for (uint32_t c = lane; c < HALF; c += 32) {
                const float exp_v   = float(2 * c) / float(HDM);
                const float inv_freq = __powf(THETA_BASE, -exp_v);
                const float ang     = pos * inv_freq;
                float cos_v, sin_v;
                __sincosf(ang, &sin_v, &cos_v);
                const float x0 = __bfloat162float(k_in[c]);
                const float x1 = __bfloat162float(k_in[c + HALF]);
                k_out[c]        = __float2bfloat16(x0 * cos_v - x1 * sin_v);
                k_out[c + HALF] = __float2bfloat16(x0 * sin_v + x1 * cos_v);
            }
        }

        // ── V heads: passthrough copy to v_cache[page, slot, kv_head, d] ──
        for (uint32_t h = 0; h < NKH; ++h) {
            const __nv_bfloat16* v_in  = qkv_row + V_OFF + h * HDM;
            __nv_bfloat16*       v_out = v_slot  + h * HDM;
            for (uint32_t d = lane; d < HDM; d += 32) {
                v_out[d] = v_in[d];
            }
        }
    }
}
// ── tile_attention: paged FA-2 online softmax for one ROW_TILE-row tile.
//
// Reads Q from q_post_rope[row, NAH * HEAD_DIM], K/V from the paged caches
// via prefill_kv_indices. Causal mask: each query at position p attends to
// keys 0..=p. GQA-aware: kv_head = q_head / GQA_RATIO.
//
// Per (row, q_head) we run a streaming online softmax scan:
//
//   m = -inf, l = 0, O = 0
//   for k in 0..=p:
//     score   = (q · K[k]) * attn_scale
//     m_new   = max(m, score)
//     alpha   = exp(m - m_new)
//     se      = exp(score - m_new)
//     O       = O * alpha + se * V[k]
//     l       = l * alpha + se
//     m       = m_new
//   out       = O / l
//
// 32 threads cooperate on one (row, head) at a time. Each lane owns
// HEAD_DIM/32 elements of the head dimension. Q stays in registers across
// the entire k-loop. K/V are reloaded per k from the paged cache. Score is
// reduced via warp shuffle.
//
// This is correct, paged, masked, and numerically stable. It is NOT fast —
// no shmem K/V staging, no cp.async, no warp-level mma. Phase 4 will swap
// in the FA-2 implementation from the existing kernel's templates.
__device__ __forceinline__ void tile_attention(const globals_t& g, uint32_t layer, uint32_t row) {
    if (threadIdx.x >= 32) return;  // warp 0 only
    constexpr uint32_t HDM             = MODEL_HEAD_DIM;
    constexpr uint32_t NAH             = MODEL_NUM_ATTN_H;
    constexpr uint32_t NKH             = MODEL_NUM_KV_H;
    constexpr uint32_t GQA_RATIO       = NAH / NKH;
    constexpr uint32_t HD_FULL         = NAH * HDM;            // attn_out dim
    constexpr uint32_t Q_DIM           = NAH * HDM;            // q_post_rope row stride
    constexpr uint32_t ROW_TILE        = MODEL_ROW_TILE;
    constexpr uint32_t PAGE_SIZE       = MODEL_KV_PAGE_SIZE;
    constexpr uint32_t PAGES_PER_LAYER = MODEL_PAGES_PER_LAYER;
    constexpr uint32_t SLOT_STRIDE     = NKH * HDM;
    constexpr uint32_t PAGE_STRIDE     = PAGE_SIZE * NKH * HDM;
    constexpr uint32_t D_PER_LANE      = HDM / 32;             // head_dim chunks per thread
    static_assert(HDM % 32 == 0, "tile_attention assumes HEAD_DIM % 32 == 0");
    const uint32_t lane = threadIdx.x;
    const uint32_t row_start = row * ROW_TILE;
    const float attn_scale = g.attn_scale;

    #pragma unroll 1
    for (uint32_t r = 0; r < ROW_TILE; ++r) {
        const uint32_t row_idx = row_start + r;
        if (row_idx >= MODEL_SEQ_LEN) break;
        const uint32_t attend_len = row_idx + 1;  // causal: keys 0..=row_idx

        for (uint32_t h = 0; h < NAH; ++h) {
            const uint32_t kv_head = h / GQA_RATIO;

            // Load Q[row_idx, h, :] into registers (D_PER_LANE elements per lane).
            float q_reg[D_PER_LANE];
            #pragma unroll
            for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                const uint32_t d = dd * 32 + lane;
                q_reg[dd] = __bfloat162float(
                    g.q_post_rope[(size_t)row_idx * Q_DIM + h * HDM + d]);
            }

            // Online softmax state.
            float o_reg[D_PER_LANE];
            #pragma unroll
            for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                o_reg[dd] = 0.0f;
            }
            float m_state = -1e30f;
            float l_state = 0.0f;

            // Stream over keys 0..=row_idx.
            for (uint32_t k_pos = 0; k_pos < attend_len; ++k_pos) {
                // Paged cache offset for this key position.
                const uint32_t logical_page = k_pos / PAGE_SIZE;
                const uint32_t slot = k_pos % PAGE_SIZE;
                const int32_t physical_page = g.prefill_kv_indices[logical_page]
                                              + (int32_t)layer * (int32_t)PAGES_PER_LAYER;
                const size_t slot_base = (size_t)physical_page * PAGE_STRIDE
                                         + (size_t)slot * SLOT_STRIDE
                                         + (size_t)kv_head * HDM;
                const __nv_bfloat16* K_slot = g.k_cache + slot_base;
                const __nv_bfloat16* V_slot = g.v_cache + slot_base;

                // Dot product q · K[k_pos].
                float score_partial = 0.0f;
                #pragma unroll
                for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                    const uint32_t d = dd * 32 + lane;
                    score_partial += q_reg[dd] * __bfloat162float(K_slot[d]);
                }
                // Warp-shuffle reduce → all lanes hold the full dot.
                #pragma unroll
                for (int offset = 16; offset > 0; offset >>= 1) {
                    score_partial += __shfl_xor_sync(0xffffffff, score_partial, offset);
                }
                const float score = score_partial * attn_scale;

                // Online softmax update.
                const float m_new = fmaxf(m_state, score);
                const float alpha = __expf(m_state - m_new);
                const float se    = __expf(score   - m_new);

                #pragma unroll
                for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                    const uint32_t d = dd * 32 + lane;
                    const float vv = __bfloat162float(V_slot[d]);
                    o_reg[dd] = o_reg[dd] * alpha + se * vv;
                }
                l_state = l_state * alpha + se;
                m_state = m_new;
            }

            // Normalize and write out.
            const float inv_l = 1.0f / l_state;
            #pragma unroll
            for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                const uint32_t d = dd * 32 + lane;
                g.attn_out[(size_t)row_idx * HD_FULL + h * HDM + d] =
                    __float2bfloat16(o_reg[dd] * inv_l);
            }
        }
    }
}

// ── tile_o_proj: shmem-staged tensor-core GEMM + residual. ──
//
// hidden_states[m,n] += sum_k attn_out[m,k] * o_w[layer, n, k]
//
// Same shmem-staged wmma structure as tile_qkv. The residual seed is
// folded in during the cooperative writeback (read existing bf16, add
// the wmma fp32 result, store bf16).
__device__ __forceinline__ void tile_o_proj(
    const globals_t& g, uint32_t layer, uint32_t row, uint32_t col, char* tile_smem)
{
    using namespace nvcuda::wmma;
    constexpr uint32_t M          = MODEL_ROW_TILE;
    constexpr uint32_t K          = MODEL_HIDDEN_DIM;
    constexpr uint32_t N          = MODEL_O_COL_TILE;
    constexpr uint32_t HD_FULL    = MODEL_HIDDEN_DIM;
    constexpr uint32_t WMMA_M     = 16;
    constexpr uint32_t WMMA_N     = 16;
    constexpr uint32_t WMMA_K     = 16;
    constexpr uint32_t N_WARPS    = 8;
    constexpr uint32_t N_PER_WARP = N / N_WARPS;
    constexpr uint32_t KB         = SHMEM_GEMM_K_BLOCK;
    static_assert(M == WMMA_M, "tile_o_proj assumes M == 16");
    static_assert(N % (WMMA_N * N_WARPS) == 0, "tile_o_proj: N must be 8*16 multiple");
    static_assert(K % KB == 0, "tile_o_proj: K must be a multiple of KB");
    static_assert(KB % WMMA_K == 0, "tile_o_proj: KB must be a multiple of 16");
    static_assert(N_PER_WARP == 16, "tile_o_proj: each warp owns one 16-col slice");

    const uint32_t row_start = row * M;
    const uint32_t col_start = col * N;
    if (row_start >= MODEL_SEQ_LEN) return;

    const __nv_bfloat16* A_base = g.attn_out + (size_t)row_start * K;
    const __nv_bfloat16* B_base = g.o_w
        + (size_t)layer * HD_FULL * K
        + (size_t)col_start * K;
    __nv_bfloat16* C_base = g.hidden_states + (size_t)row_start * HD_FULL + col_start;

    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t n_warp_start = warp_id * N_PER_WARP;
    const uint32_t lane = threadIdx.x;

    __nv_bfloat16* a_smem = reinterpret_cast<__nv_bfloat16*>(tile_smem);
    __nv_bfloat16* b_smem = a_smem + M * KB;
    float* oproj_scratch = reinterpret_cast<float*>(b_smem + N * KB);
    float* my_scratch = oproj_scratch + (size_t)warp_id * WMMA_M * WMMA_N;

    fragment<matrix_a, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, row_major> a_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> c_frag;
    fill_fragment(c_frag, 0.0f);

    #pragma unroll 1
    for (uint32_t k_outer = 0; k_outer < K; k_outer += KB) {
        for (uint32_t i = lane; i < M * KB; i += 256) {
            const uint32_t m = i / KB;
            const uint32_t k_local = i % KB;
            a_smem[m * KB + k_local] = A_base[m * K + k_outer + k_local];
        }
        for (uint32_t i = lane; i < N * KB; i += 256) {
            const uint32_t n = i / KB;
            const uint32_t k_local = i % KB;
            b_smem[n * KB + k_local] = B_base[(size_t)n * K + k_outer + k_local];
        }
        __syncthreads();

        #pragma unroll
        for (uint32_t k_inner = 0; k_inner < KB; k_inner += WMMA_K) {
            load_matrix_sync(a_frag, a_smem + k_inner, KB);
            load_matrix_sync(b_frag,
                             b_smem + (size_t)n_warp_start * KB + k_inner,
                             KB);
            mma_sync(c_frag, a_frag, b_frag, c_frag);
        }
        __syncthreads();
    }

    store_matrix_sync(my_scratch, c_frag, WMMA_N, mem_row_major);
    __syncthreads();

    // Cooperative residual + writeback.
    const uint32_t total = M * N;
    for (uint32_t idx = lane; idx < total; idx += 256) {
        const uint32_t m = idx / N;
        const uint32_t n = idx % N;
        if (row_start + m >= MODEL_SEQ_LEN) continue;
        const uint32_t w = n / N_PER_WARP;
        const uint32_t local_n = n % N_PER_WARP;
        const float mma_val = oproj_scratch[w * WMMA_M * WMMA_N + m * WMMA_N + local_n];
        const float old_c  = __bfloat162float(C_base[m * HD_FULL + n]);
        C_base[m * HD_FULL + n] = __float2bfloat16(old_c + mma_val);
    }
    __syncthreads();
}


// ── tile_mlp_norm: real RMS norm, same structure as tile_attn_norm but
// reads attn_out and writes rms_gate using mlp_norm_w. ──
// ── tile_gate_up: silu(rms_gate @ gate_w^T) * (rms_gate @ up_w^T). ──
//
// Output:  silu_out[m, n] = silu(g_acc) * u_acc
//   g_acc = sum_k rms_gate[m, k] * gate_w[layer, n, k]
//   u_acc = sum_k rms_gate[m, k] *   up_w[layer, n, k]
//
// Two shmem-staged GEMMs sharing the same A operand (rms_gate), fused
// with the SwiGLU elementwise op. Per K_BLOCK: cooperatively load A, gate
// B, and up B into shmem; each warp issues paired wmma over the K_BLOCK
// for both the gate and up accumulators. The fused silu*mul happens in
// fp32 during the cooperative writeback.
__device__ __forceinline__ void tile_gate_up(
    const globals_t& g, uint32_t layer, uint32_t row, uint32_t col, char* tile_smem)
{
    using namespace nvcuda::wmma;
    constexpr uint32_t M          = MODEL_ROW_TILE;
    constexpr uint32_t K          = MODEL_HIDDEN_DIM;
    constexpr uint32_t N          = MODEL_GATE_UP_COL_TILE;
    constexpr uint32_t ID         = MODEL_INTERMEDIATE;
    constexpr uint32_t WMMA_M     = 16;
    constexpr uint32_t WMMA_N     = 16;
    constexpr uint32_t WMMA_K     = 16;
    constexpr uint32_t N_WARPS    = 8;
    constexpr uint32_t N_PER_WARP = N / N_WARPS;
    constexpr uint32_t KB         = SHMEM_GEMM_K_BLOCK;
    static_assert(M == WMMA_M, "tile_gate_up assumes M == 16");
    static_assert(N % (WMMA_N * N_WARPS) == 0, "tile_gate_up: N must be 8*16 multiple");
    static_assert(K % KB == 0, "tile_gate_up: K must be a multiple of KB");
    static_assert(KB % WMMA_K == 0, "tile_gate_up: KB must be a multiple of 16");
    static_assert(N_PER_WARP == 16, "tile_gate_up: each warp owns one 16-col slice");

    const uint32_t row_start = row * M;
    const uint32_t col_start = col * N;
    if (row_start >= MODEL_SEQ_LEN) return;

    const __nv_bfloat16* A_base      = g.rms_gate + (size_t)row_start * K;
    const __nv_bfloat16* B_gate_base = g.gate_w
        + (size_t)layer * ID * K
        + (size_t)col_start * K;
    const __nv_bfloat16* B_up_base   = g.up_w
        + (size_t)layer * ID * K
        + (size_t)col_start * K;
    __nv_bfloat16* C_base = g.silu_out + (size_t)row_start * ID + col_start;

    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t n_warp_start = warp_id * N_PER_WARP;
    const uint32_t lane = threadIdx.x;

    // Partition shmem: a_smem | b_gate_smem | b_up_smem | gate_scratch | up_scratch
    __nv_bfloat16* a_smem = reinterpret_cast<__nv_bfloat16*>(tile_smem);
    __nv_bfloat16* b_gate_smem = a_smem + M * KB;
    __nv_bfloat16* b_up_smem   = b_gate_smem + N * KB;
    float* gate_scratch = reinterpret_cast<float*>(b_up_smem + N * KB);
    float* up_scratch   = gate_scratch + N_WARPS * WMMA_M * WMMA_N;
    float* my_g_scratch = gate_scratch + (size_t)warp_id * WMMA_M * WMMA_N;
    float* my_u_scratch = up_scratch   + (size_t)warp_id * WMMA_M * WMMA_N;

    fragment<matrix_a, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, row_major> a_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_g_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_u_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> g_acc_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> u_acc_frag;
    fill_fragment(g_acc_frag, 0.0f);
    fill_fragment(u_acc_frag, 0.0f);

    #pragma unroll 1
    for (uint32_t k_outer = 0; k_outer < K; k_outer += KB) {
        // Cooperative loads of A, B_gate, B_up.
        for (uint32_t i = lane; i < M * KB; i += 256) {
            const uint32_t m = i / KB;
            const uint32_t k_local = i % KB;
            a_smem[m * KB + k_local] = A_base[m * K + k_outer + k_local];
        }
        for (uint32_t i = lane; i < N * KB; i += 256) {
            const uint32_t n = i / KB;
            const uint32_t k_local = i % KB;
            b_gate_smem[n * KB + k_local] = B_gate_base[(size_t)n * K + k_outer + k_local];
            b_up_smem[n * KB + k_local]   = B_up_base[(size_t)n * K + k_outer + k_local];
        }
        __syncthreads();

        #pragma unroll
        for (uint32_t k_inner = 0; k_inner < KB; k_inner += WMMA_K) {
            load_matrix_sync(a_frag, a_smem + k_inner, KB);
            load_matrix_sync(b_g_frag, b_gate_smem + (size_t)n_warp_start * KB + k_inner, KB);
            load_matrix_sync(b_u_frag, b_up_smem   + (size_t)n_warp_start * KB + k_inner, KB);
            mma_sync(g_acc_frag, a_frag, b_g_frag, g_acc_frag);
            mma_sync(u_acc_frag, a_frag, b_u_frag, u_acc_frag);
        }
        __syncthreads();
    }

    store_matrix_sync(my_g_scratch, g_acc_frag, WMMA_N, mem_row_major);
    store_matrix_sync(my_u_scratch, u_acc_frag, WMMA_N, mem_row_major);
    __syncthreads();

    // Cooperative SwiGLU writeback: silu(g) * u → bf16
    const uint32_t total = M * N;
    for (uint32_t idx = lane; idx < total; idx += 256) {
        const uint32_t m = idx / N;
        const uint32_t n = idx % N;
        if (row_start + m >= MODEL_SEQ_LEN) continue;
        const uint32_t w = n / N_PER_WARP;
        const uint32_t local_n = n % N_PER_WARP;
        const uint32_t off = w * WMMA_M * WMMA_N + m * WMMA_N + local_n;
        const float gv = gate_scratch[off];
        const float uv = up_scratch[off];
        const float silu_g = gv / (1.0f + __expf(-gv));
        C_base[m * ID + n] = __float2bfloat16(silu_g * uv);
    }
    __syncthreads();
}

__device__ __forceinline__ void tile_mlp_norm(const globals_t& g, uint32_t layer, uint32_t row) {
    if (threadIdx.x >= 32) return;  // warp 0 only
    constexpr uint32_t HD       = MODEL_HIDDEN_DIM;
    constexpr uint32_t ROW_TILE = MODEL_ROW_TILE;
    const uint32_t row_start = row * ROW_TILE;
    const __nv_bfloat16* w = g.mlp_norm_w + (size_t)layer * HD;
    const uint32_t lane = threadIdx.x;

    #pragma unroll 1
    for (uint32_t r = 0; r < ROW_TILE; ++r) {
        const uint32_t row_idx = row_start + r;
        if (row_idx >= MODEL_SEQ_LEN) break;
        const __nv_bfloat16* x = g.attn_out + (size_t)row_idx * HD;
        __nv_bfloat16*       y = g.rms_gate + (size_t)row_idx * HD;

        float my_sum = 0.0f;
        for (uint32_t c = lane; c < HD; c += 32) {
            float v = __bfloat162float(x[c]);
            my_sum += v * v;
        }
        for (int offset = 16; offset > 0; offset >>= 1) {
            my_sum += __shfl_xor_sync(0xffffffff, my_sum, offset);
        }
        const float scale = rsqrtf(my_sum / float(HD) + g.eps);

        for (uint32_t c = lane; c < HD; c += 32) {
            float xv = __bfloat162float(x[c]);
            float wv = __bfloat162float(w[c]);
            y[c] = __float2bfloat16(xv * scale * wv);
        }
    }
}

// ── tile_down: shmem-staged tensor-core GEMM + residual.
//
// hidden_states[m,n] += sum_k silu_out[m,k] * down_w[layer, n, k]
//
// Same shmem-staged wmma + residual writeback as tile_o_proj. K is the
// intermediate dim, which is the largest K of the four GEMMs.
__device__ __forceinline__ void tile_down(
    const globals_t& g, uint32_t layer, uint32_t row, uint32_t col, char* tile_smem)
{
    using namespace nvcuda::wmma;
    constexpr uint32_t M          = MODEL_ROW_TILE;
    constexpr uint32_t K          = MODEL_INTERMEDIATE;
    constexpr uint32_t N          = MODEL_DOWN_COL_TILE;
    constexpr uint32_t HD_FULL    = MODEL_HIDDEN_DIM;
    constexpr uint32_t WMMA_M     = 16;
    constexpr uint32_t WMMA_N     = 16;
    constexpr uint32_t WMMA_K     = 16;
    constexpr uint32_t N_WARPS    = 8;
    constexpr uint32_t N_PER_WARP = N / N_WARPS;
    constexpr uint32_t KB         = SHMEM_GEMM_K_BLOCK;
    static_assert(M == WMMA_M, "tile_down assumes M == 16");
    static_assert(N % (WMMA_N * N_WARPS) == 0, "tile_down: N must be 8*16 multiple");
    static_assert(K % KB == 0, "tile_down: K must be a multiple of KB");
    static_assert(KB % WMMA_K == 0, "tile_down: KB must be a multiple of 16");
    static_assert(N_PER_WARP == 16, "tile_down: each warp owns one 16-col slice");

    const uint32_t row_start = row * M;
    const uint32_t col_start = col * N;
    if (row_start >= MODEL_SEQ_LEN) return;

    const __nv_bfloat16* A_base = g.silu_out + (size_t)row_start * K;
    const __nv_bfloat16* B_base = g.down_w
        + (size_t)layer * HD_FULL * K
        + (size_t)col_start * K;
    __nv_bfloat16* C_base = g.hidden_states + (size_t)row_start * HD_FULL + col_start;

    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t n_warp_start = warp_id * N_PER_WARP;
    const uint32_t lane = threadIdx.x;

    __nv_bfloat16* a_smem = reinterpret_cast<__nv_bfloat16*>(tile_smem);
    __nv_bfloat16* b_smem = a_smem + M * KB;
    float* down_scratch = reinterpret_cast<float*>(b_smem + N * KB);
    float* my_scratch = down_scratch + (size_t)warp_id * WMMA_M * WMMA_N;

    fragment<matrix_a, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, row_major> a_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> c_frag;
    fill_fragment(c_frag, 0.0f);

    #pragma unroll 1
    for (uint32_t k_outer = 0; k_outer < K; k_outer += KB) {
        for (uint32_t i = lane; i < M * KB; i += 256) {
            const uint32_t m = i / KB;
            const uint32_t k_local = i % KB;
            a_smem[m * KB + k_local] = A_base[m * K + k_outer + k_local];
        }
        for (uint32_t i = lane; i < N * KB; i += 256) {
            const uint32_t n = i / KB;
            const uint32_t k_local = i % KB;
            b_smem[n * KB + k_local] = B_base[(size_t)n * K + k_outer + k_local];
        }
        __syncthreads();

        #pragma unroll
        for (uint32_t k_inner = 0; k_inner < KB; k_inner += WMMA_K) {
            load_matrix_sync(a_frag, a_smem + k_inner, KB);
            load_matrix_sync(b_frag,
                             b_smem + (size_t)n_warp_start * KB + k_inner,
                             KB);
            mma_sync(c_frag, a_frag, b_frag, c_frag);
        }
        __syncthreads();
    }

    store_matrix_sync(my_scratch, c_frag, WMMA_N, mem_row_major);
    __syncthreads();

    const uint32_t total = M * N;
    for (uint32_t idx = lane; idx < total; idx += 256) {
        const uint32_t m = idx / N;
        const uint32_t n = idx % N;
        if (row_start + m >= MODEL_SEQ_LEN) continue;
        const uint32_t w = n / N_PER_WARP;
        const uint32_t local_n = n % N_PER_WARP;
        const float mma_val = down_scratch[w * WMMA_M * WMMA_N + m * WMMA_N + local_n];
        const float old_c  = __bfloat162float(C_base[m * HD_FULL + n]);
        C_base[m * HD_FULL + n] = __float2bfloat16(old_c + mma_val);
    }
    __syncthreads();
}


// Grid-wide barrier via a single global counter. Every CTA's thread 0 bumps
// the counter once per wave; all CTAs spin until the counter reaches the
// expected (wave_idx + 1) * NUM_CTAS value. Requires the launch to fit all
// CTAs concurrently — true for us at num_ctas == num_sms with 1 CTA/SM.
__device__ __forceinline__ void grid_barrier(unsigned int* counter, unsigned int wave_idx) {
    __syncthreads();
    if (threadIdx.x == 0) {
        const unsigned int target = (wave_idx + 1u) * NUM_CTAS;
        atomicAdd(counter, 1u);
        __threadfence();
        while (atomicAdd(counter, 0u) < target) {
            // spin
        }
    }
    __syncthreads();
}

__global__ void scheduled_megakernel(globals_t g, SchedRuntime rt) {
    const uint32_t cta_id = blockIdx.x;
    const uint32_t tid    = threadIdx.x;
    if (cta_id >= NUM_CTAS) return;

    // Single CTA-wide shmem arena reused across tile bodies. Wave scheduling
    // means only one tile body runs at a time per CTA, so they can share.
    __shared__ alignas(16) char tile_smem[TILE_SHMEM_BYTES];

    for (uint32_t w = 0; w < NUM_WAVES; ++w) {
        const uint32_t off = WAVE_CTA_OFFSETS[w * (NUM_CTAS + 1) + cta_id];
        const uint32_t end = WAVE_CTA_OFFSETS[w * (NUM_CTAS + 1) + cta_id + 1];

        // Execute every tile assigned to this CTA in this wave.
        for (uint32_t i = off; i < end; ++i) {
            const TileOp op = WAVE_OPS[i];
            switch (op.phase) {
                case PHASE_ATTN_NORM: tile_attn_norm(g, op.layer, op.row); break;
                case PHASE_QKV:       tile_qkv      (g, op.layer, op.row, op.col, tile_smem); break;
                case PHASE_ROPE:      tile_rope     (g, op.layer, op.row); break;
                case PHASE_ATTENTION: tile_attention(g, op.layer, op.row); break;
                case PHASE_O_PROJ:    tile_o_proj   (g, op.layer, op.row, op.col, tile_smem); break;
                case PHASE_MLP_NORM:  tile_mlp_norm (g, op.layer, op.row); break;
                case PHASE_GATE_UP:   tile_gate_up  (g, op.layer, op.row, op.col, tile_smem); break;
                case PHASE_DOWN:      tile_down     (g, op.layer, op.row, op.col, tile_smem); break;
                default: break;
            }
            // Stamp validation tick. Single-threaded.
            __syncthreads();
            if (tid == 0) {
                const uint32_t tick = atomicAdd(rt.tick_counter, 1u) + 1u;
                const uint32_t node_id = NODE_ID_FOR_OP[i];
                rt.flags[node_id] = tick;
            }
            __syncthreads();
        }

        // One grid barrier per wave.
        grid_barrier(rt.barrier_arrived, w);
    }
}

}  // namespace pfl_sched

extern "C" void launch_scheduled_megakernel(
    // Activation buffers (bf16, [seq, dim] row-major)
    void* hidden_states,
    void* rms_rope,
    void* qkv,
    void* q_post_rope,
    void* attn_out,
    void* rms_gate,
    void* silu_out,
    // Paged KV cache (bf16)
    void* k_cache,
    void* v_cache,
    // Block table + indptrs (i32)
    const int* prefill_kv_indices,
    const int* prefill_kv_indptr,
    const int* prefill_qo_indptr,
    // Norm weights (bf16, [num_layers, hidden_dim])
    void* attn_norm_w,
    void* mlp_norm_w,
    // GEMM weights (bf16)
    void* qkv_w,
    void* o_w,
    void* gate_w,
    void* up_w,
    void* down_w,
    float eps,
    float attn_scale,
    // Validation buffers
    unsigned int* flags,
    unsigned int* tick_counter,
    unsigned int* barrier_arrived,
    cudaStream_t stream) {
    pfl_sched::globals_t g{
        reinterpret_cast<__nv_bfloat16*>(hidden_states),
        reinterpret_cast<__nv_bfloat16*>(rms_rope),
        reinterpret_cast<__nv_bfloat16*>(qkv),
        reinterpret_cast<__nv_bfloat16*>(q_post_rope),
        reinterpret_cast<__nv_bfloat16*>(attn_out),
        reinterpret_cast<__nv_bfloat16*>(rms_gate),
        reinterpret_cast<__nv_bfloat16*>(silu_out),
        reinterpret_cast<__nv_bfloat16*>(k_cache),
        reinterpret_cast<__nv_bfloat16*>(v_cache),
        prefill_kv_indices,
        prefill_kv_indptr,
        prefill_qo_indptr,
        reinterpret_cast<__nv_bfloat16*>(attn_norm_w),
        reinterpret_cast<__nv_bfloat16*>(mlp_norm_w),
        reinterpret_cast<__nv_bfloat16*>(qkv_w),
        reinterpret_cast<__nv_bfloat16*>(o_w),
        reinterpret_cast<__nv_bfloat16*>(gate_w),
        reinterpret_cast<__nv_bfloat16*>(up_w),
        reinterpret_cast<__nv_bfloat16*>(down_w),
        eps,
        attn_scale,
    };
    pfl_sched::SchedRuntime rt{flags, tick_counter, barrier_arrived};
    dim3 grid(pfl_sched::NUM_CTAS);
    // 256 threads = 8 warps. Warp-shuffle phases (norms, rope, attention)
    // are gated to warp 0 inside their bodies; GEMM phases use all 256
    // threads cooperatively via per-thread output partitioning.
    dim3 block(256);
    pfl_sched::scheduled_megakernel<<<grid, block, 0, stream>>>(g, rt);
}

extern "C" unsigned int scheduled_megakernel_num_nodes() {
    return pfl_sched::NUM_NODES;
}

extern "C" unsigned int scheduled_megakernel_num_ctas() {
    return pfl_sched::NUM_CTAS;
}

extern "C" unsigned int scheduled_megakernel_num_waves() {
    return pfl_sched::NUM_WAVES;
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reified_dag::{LlamaDims, TileSizes};
    use crate::schedule::{CostModel, partition_into_waves};

    fn tiny_dims() -> LlamaDims {
        LlamaDims {
            num_layers: 2,
            hidden_dim: 256,
            intermediate_dim: 512,
            num_attn_heads: 4,
            num_kv_heads: 2,
            head_dim: 64,
            seq_len: 32,
        }
    }

    #[test]
    fn emit_smoke() {
        let dag = ReifiedDag::reify_llama(tiny_dims(), TileSizes::default_v1());
        let cost = CostModel::from_dag(&dag);
        let sched = partition_into_waves(&dag, 4, &cost, 100);
        let cpp = emit_scheduled_megakernel_cu(&dag, &sched, 16, "tiny");

        assert!(cpp.contains("namespace pfl_sched"));
        assert!(cpp.contains("WAVE_OPS"));
        assert!(cpp.contains("WAVE_CTA_OFFSETS"));
        assert!(cpp.contains("NODE_ID_FOR_OP"));
        assert!(cpp.contains("static_assert(sizeof(TileOp) == 16"));
        let n = dag.nodes.len();
        assert!(cpp.contains(&format!("NUM_NODES = {n}")));
        let w = sched.waves.len();
        assert!(cpp.contains(&format!("NUM_WAVES = {w}")));
    }

    #[test]
    fn op_count_matches_node_count() {
        let dag = ReifiedDag::reify_llama(tiny_dims(), TileSizes::default_v1());
        let cost = CostModel::from_dag(&dag);
        let sched = partition_into_waves(&dag, 4, &cost, 100);

        let mut total = 0u32;
        for w in &sched.waves {
            for c in &w.cta_nodes {
                total += c.len() as u32;
            }
        }
        assert_eq!(total as usize, dag.nodes.len());
    }
}
