// SPDX-License-Identifier: Apache-2.0
//! Phase 3a-bsp / Phase 3b-bsp: emit a BSP wave-front megakernel.
//!
//! The kernel body lives in `templates/scheduled/megakernel.cu` and is
//! rendered through askama. Per-variant suffixing (`pfl_sched_<name>`,
//! `scheduled_megakernel_<name>`) is handled by the template substitution
//! `{{ name }}`. Subsequent commits will split the body into smaller
//! per-tile templates so each tile body can be parametrized on its own
//! axes (`M_TILE`, `KB`, `STAGES`, GEMM variant).
//
// Template context structs are defined inline at the bottom of this file
// rather than in a sibling templates.rs, since there is currently only
// one template. Move them out when the template fan-out grows.
//!
//! Layout:
//! ```text
//! constexpr uint32_t NUM_WAVES;
//! constexpr uint32_t NUM_CTAS;
//! constexpr uint32_t NUM_NODES;   // for sizing the validation tick array
//!
//! struct TileOp { phase, layer, row, col };          // 12 B (with padding 16)
//! __device__ const TileOp WAVE_OPS[N_OPS_TOTAL];     // packed: per wave, per CTA, in order
//! __device__ const uint32_t WAVE_CTA_OFFSETS[
//!     NUM_WAVES * (NUM_CTAS + 1)];                   // prefix-sum table
//! __device__ const uint32_t NODE_ID_FOR_OP[N_OPS_TOTAL]; // parallel to WAVE_OPS, for tick stamping
//! ```
//!
//! Per CTA per wave: stream of TileOp records contiguous in WAVE_OPS, indexed
//! via WAVE_CTA_OFFSETS[wave * (NUM_CTAS+1) + cta..+ cta+1]. Sequential read
//! → L1/L2 hot. After each wave, all CTAs participate in one grid barrier
//! (atomic-counter style) before moving to the next.

use std::fmt::Write as _;

use askama::Template;

use crate::reified_dag::{Phase, ReifiedDag};
use crate::schedule::WaveSchedule;

/// Askama context for the scheduled megakernel body template
/// (`templates/scheduled/megakernel.cu`).
///
/// Currently the only knob is `name` (the per-variant suffix that gets
/// woven into the namespace and the extern "C" symbol root). All the
/// per-variant model dims are still emitted as raw `MODEL_*` constants
/// before the template body, by `emit_scheduled_megakernel_cu`. The
/// next refactor step will lift those into template fields too, and
/// then the step after will start splitting the body per tile.
#[derive(Template)]
#[template(path = "scheduled/megakernel.cu", escape = "none")]
struct MegakernelBodyCtx<'a> {
    name: &'a str,
}

/// Numeric phase tag matching the C++ enum.
pub fn phase_tag(p: Phase) -> u32 {
    match p {
        Phase::AttnNorm => 0,
        Phase::Qkv => 1,
        Phase::Rope => 2,
        Phase::Attention => 3,
        Phase::OProj => 4,
        Phase::MlpNorm => 5,
        Phase::GateUp => 6,
        Phase::Down => 7,
    }
}

/// Render the wave program as a CUDA include chunk.
pub fn emit_wave_schedule_cpp(dag: &ReifiedDag, sched: &WaveSchedule) -> String {
    let n = dag.nodes.len();
    let num_ctas = sched.num_ctas as usize;
    let num_waves = sched.waves.len();

    // ── Pack the per-wave per-CTA op streams into one flat array. ──
    // Layout order: wave 0 / cta 0, cta 1, ..., cta N-1; wave 1 / cta 0, ...
    let mut ops: Vec<(
        u32, /*phase*/
        u32, /*layer*/
        u32, /*row*/
        u32, /*col*/
    )> = Vec::with_capacity(n);
    let mut node_ids: Vec<u32> = Vec::with_capacity(n);
    let offsets_len = num_waves * (num_ctas + 1);
    let mut wave_cta_offsets: Vec<u32> = Vec::with_capacity(offsets_len);

    let mut cursor: u32 = 0;
    for wave in &sched.waves {
        for cta in 0..num_ctas {
            wave_cta_offsets.push(cursor);
            for nid in &wave.cta_nodes[cta] {
                let nd = &dag.nodes[nid.0 as usize];
                ops.push((
                    phase_tag(nd.phase),
                    nd.layer as u32,
                    nd.row as u32,
                    nd.col as u32,
                ));
                node_ids.push(nid.0);
                cursor += 1;
            }
        }
        // Sentinel "end of last cta in this wave" for clean range queries.
        wave_cta_offsets.push(cursor);
    }
    debug_assert_eq!(cursor as usize, n);
    debug_assert_eq!(
        wave_cta_offsets.len(),
        num_waves * (num_ctas + 1),
        "offset table size"
    );

    // ── Emit ──
    let mut out = String::new();
    writeln!(
        out,
        "// AUTO-GENERATED by scheduled_codegen.rs — do not edit."
    )
    .unwrap();
    writeln!(
        out,
        "// {} nodes, {} waves, {} CTAs",
        n, num_waves, num_ctas
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#pragma once").unwrap();
    writeln!(out, "#include <cstdint>").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "namespace pfl_sched {{").unwrap();
    writeln!(out, "constexpr uint32_t NUM_NODES = {};", n).unwrap();
    writeln!(out, "constexpr uint32_t NUM_WAVES = {};", num_waves).unwrap();
    writeln!(out, "constexpr uint32_t NUM_CTAS  = {};", num_ctas).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Phase tags").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ATTN_NORM = 0;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_QKV       = 1;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ROPE      = 2;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ATTENTION = 3;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_O_PROJ    = 4;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_MLP_NORM  = 5;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_GATE_UP   = 6;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_DOWN      = 7;").unwrap();
    writeln!(out).unwrap();

    // 16-byte TileOp (4 u32s — phase + layer + row + col). u32 layer/row/col
    // is plenty for any model we'll target and keeps the struct nicely aligned.
    writeln!(
        out,
        "struct TileOp {{\n  \
           uint32_t phase;\n  \
           uint32_t layer;\n  \
           uint32_t row;\n  \
           uint32_t col;\n\
         }};\n\
         static_assert(sizeof(TileOp) == 16, \"TileOp layout drifted\");"
    )
    .unwrap();
    writeln!(out).unwrap();

    // WAVE_OPS — flat array of TileOps.
    writeln!(
        out,
        "static __device__ const TileOp WAVE_OPS[NUM_NODES] = {{"
    )
    .unwrap();
    for (phase, layer, row, col) in &ops {
        writeln!(out, "  {{ {}, {}, {}, {} }},", phase, layer, row, col).unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    // NODE_ID_FOR_OP — parallel to WAVE_OPS so each CTA can stamp the right
    // tick slot in the validation array.
    writeln!(
        out,
        "static __device__ const uint32_t NODE_ID_FOR_OP[NUM_NODES] = {{"
    )
    .unwrap();
    emit_u32_chunked(&mut out, &node_ids);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    // WAVE_CTA_OFFSETS — flattened (NUM_WAVES * (NUM_CTAS+1)) prefix table.
    writeln!(
        out,
        "static __device__ const uint32_t WAVE_CTA_OFFSETS[NUM_WAVES * (NUM_CTAS + 1)] = {{"
    )
    .unwrap();
    emit_u32_chunked(&mut out, &wave_cta_offsets);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "}}  // namespace pfl_sched").unwrap();

    out
}

fn emit_u32_chunked(out: &mut String, vals: &[u32]) {
    const PER_LINE: usize = 16;
    for chunk in vals.chunks(PER_LINE) {
        out.push_str("  ");
        for v in chunk {
            write!(out, "{},", v).unwrap();
        }
        out.push('\n');
    }
}

/// Phase 3b-bsp — emit a complete `.cu` file containing the wave program
/// data + tile bodies (real where implemented, placeholder where not) +
/// grid-barrier megakernel + extern "C" launch helper.
///
/// `kv_page_size` is the slots-per-page for the paged KV cache. Pages-per-
/// layer is derived as ceil(seq_len / kv_page_size).
///
/// `name` is appended to the namespace and to all extern "C" symbols so
/// multiple variants can coexist in the same translation-unit batch:
///   namespace pfl_sched_<name>
///   extern "C" void launch_scheduled_megakernel_<name>(...)
///   extern "C" unsigned scheduled_megakernel_<name>_num_nodes()
///   etc.
pub fn emit_scheduled_megakernel_cu(
    dag: &ReifiedDag,
    sched: &WaveSchedule,
    kv_page_size: u32,
    name: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&emit_wave_schedule_cpp(dag, sched));
    // Bake the model dims as compile-time constants so tile bodies can index
    // gmem buffers without an extra struct field per dim.
    writeln!(out, "namespace pfl_sched {{").unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_NUM_LAYERS    = {};",
        dag.dims.num_layers
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_HIDDEN_DIM    = {};",
        dag.dims.hidden_dim
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_INTERMEDIATE  = {};",
        dag.dims.intermediate_dim
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_NUM_ATTN_H    = {};",
        dag.dims.num_attn_heads
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_NUM_KV_H      = {};",
        dag.dims.num_kv_heads
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_HEAD_DIM      = {};",
        dag.dims.head_dim
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_SEQ_LEN       = {};",
        dag.dims.seq_len
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_ROW_TILE      = {};",
        dag.tiles.row_tile
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_QKV_COL_TILE  = {};",
        dag.tiles.qkv_col_tile
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_O_COL_TILE    = {};",
        dag.tiles.o_col_tile
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_GATE_UP_COL_TILE = {};",
        dag.tiles.gate_up_col_tile
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_DOWN_COL_TILE = {};",
        dag.tiles.down_col_tile
    )
    .unwrap();
    let pages_per_layer = dag.dims.seq_len.div_ceil(kv_page_size);
    writeln!(
        out,
        "constexpr uint32_t MODEL_KV_PAGE_SIZE  = {};",
        kv_page_size
    )
    .unwrap();
    writeln!(
        out,
        "constexpr uint32_t MODEL_PAGES_PER_LAYER = {};",
        pages_per_layer
    )
    .unwrap();
    writeln!(out, "}}  // namespace pfl_sched").unwrap();

    // The kernel body template is written with `pfl_sched_{{ name }}` and
    // `scheduled_megakernel_{{ name }}`, so per-variant suffixing happens
    // at render time rather than via a post-hoc string replace. The
    // pre-template prelude above (the namespace block we just emitted with
    // raw MODEL_* constants) still uses the literal `pfl_sched` namespace,
    // which gets retroactively suffixed by the same `_<name>` pass below
    // — that part will be folded into the template in the next refactor
    // step.
    let body = MegakernelBodyCtx { name }
        .render()
        .expect("scheduled megakernel body template render");
    out.push_str(&body);

    // The MODEL_* constants block above still emits the literal
    // `pfl_sched` namespace name. Suffix it to match the templated body.
    // This is the only remaining string-rewrite step; it goes away once
    // the prelude moves into the template.
    let ns_old = "namespace pfl_sched {";
    let ns_new = format!("namespace pfl_sched_{name} {{");
    let ns_close_old = "}  // namespace pfl_sched";
    let ns_close_new = format!("}}  // namespace pfl_sched_{name}");
    out.replace(ns_old, &ns_new)
        .replace(ns_close_old, &ns_close_new)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reified_dag::{LlamaDims, TileSizes};
    use crate::schedule::{CostModel, partition_into_waves};

    fn tiny_dims() -> LlamaDims {
        LlamaDims {
            num_layers: 2,
            hidden_dim: 256,
            intermediate_dim: 512,
            num_attn_heads: 4,
            num_kv_heads: 2,
            head_dim: 64,
            seq_len: 32,
        }
    }

    #[test]
    fn emit_smoke() {
        let dag = ReifiedDag::reify_llama(tiny_dims(), TileSizes::default_v1());
        let cost = CostModel::from_dag(&dag);
        let sched = partition_into_waves(&dag, 4, &cost, 100);
        let cpp = emit_scheduled_megakernel_cu(&dag, &sched, 16, "tiny");

        assert!(cpp.contains("namespace pfl_sched"));
        assert!(cpp.contains("WAVE_OPS"));
        assert!(cpp.contains("WAVE_CTA_OFFSETS"));
        assert!(cpp.contains("NODE_ID_FOR_OP"));
        assert!(cpp.contains("static_assert(sizeof(TileOp) == 16"));
        let n = dag.nodes.len();
        assert!(cpp.contains(&format!("NUM_NODES = {n}")));
        let w = sched.waves.len();
        assert!(cpp.contains(&format!("NUM_WAVES = {w}")));
    }

    #[test]
    fn op_count_matches_node_count() {
        let dag = ReifiedDag::reify_llama(tiny_dims(), TileSizes::default_v1());
        let cost = CostModel::from_dag(&dag);
        let sched = partition_into_waves(&dag, 4, &cost, 100);

        let mut total = 0u32;
        for w in &sched.waves {
            for c in &w.cta_nodes {
                total += c.len() as u32;
            }
        }
        assert_eq!(total as usize, dag.nodes.len());
    }
}
