// SPDX-License-Identifier: Apache-2.0
//! Phase 3a: serialize a `Schedule` into C++ const arrays.
//!
//! Emits a header-only chunk of CUDA that the scheduled megakernel pulls
//! into its `__global__`. Layout:
//!
//! ```text
//! static __device__ const uint32_t SCHED_ALL_DEPS[N_EDGES] = { ... };
//! static __device__ const NodeRecord SCHED_NODES[N_NODES] = { ... };
//! static __device__ const uint32_t SCHED_CTA_OFFSETS[NUM_CTAS+1] = { ... };
//! static __device__ const uint32_t SCHED_CTA_NODES[N_NODES] = { ... };
//! ```
//!
//! - `SCHED_ALL_DEPS`: flat array of dep NodeIds, indexed by `(dep_off, dep_count)`.
//! - `SCHED_NODES[i]`: the i-th node in canonical (NodeId) order. Holds phase tag,
//!   coordinates (layer, row, col), and `(dep_off, dep_count)` into `SCHED_ALL_DEPS`.
//! - `SCHED_CTA_OFFSETS[c..c+1]`: range into `SCHED_CTA_NODES` listing the NodeIds
//!   that CTA `c` should execute, in schedule order (start time ascending).
//!
//! This module does **only** the Rust→C++ string emission. No CUDA side effects,
//! no kernel changes — pure Phase 3a so we can validate before touching the
//! megakernel itself.

use std::fmt::Write as _;

use crate::reified_dag::{Phase, ReifiedDag};
use crate::schedule::Schedule;

/// Numeric phase tag matching the C++ enum the scheduled kernel will use.
pub fn phase_tag(p: Phase) -> u32 {
    match p {
        Phase::AttnNorm => 0,
        Phase::Qkv => 1,
        Phase::Rope => 2,
        Phase::Attention => 3,
        Phase::OProj => 4,
        Phase::MlpNorm => 5,
        Phase::GateUp => 6,
        Phase::Down => 7,
    }
}

/// Render the dispatch table as a CUDA include chunk.
pub fn emit_schedule_cpp(dag: &ReifiedDag, sched: &Schedule) -> String {
    let n = dag.nodes.len();
    let num_ctas = sched.num_ctas as usize;

    // ── Step 1: build SCHED_ALL_DEPS by concatenating each node's deps. ──
    let mut all_deps: Vec<u32> = Vec::new();
    let mut node_dep_off: Vec<u32> = Vec::with_capacity(n);
    let mut node_dep_cnt: Vec<u32> = Vec::with_capacity(n);
    for nd in &dag.nodes {
        node_dep_off.push(all_deps.len() as u32);
        node_dep_cnt.push(nd.deps.len() as u32);
        for d in &nd.deps {
            all_deps.push(d.0);
        }
    }

    // ── Step 2: per-CTA node lists, sorted by start time ascending. ──
    let mut per_cta: Vec<Vec<(u64, u32)>> = vec![Vec::new(); num_ctas];
    for p in &sched.placements {
        per_cta[p.cta as usize].push((p.start, p.node.0));
    }
    for v in &mut per_cta {
        v.sort_by_key(|&(t, _)| t);
    }

    let mut cta_offsets: Vec<u32> = Vec::with_capacity(num_ctas + 1);
    let mut cta_nodes: Vec<u32> = Vec::with_capacity(n);
    cta_offsets.push(0);
    for v in &per_cta {
        for &(_, node) in v {
            cta_nodes.push(node);
        }
        cta_offsets.push(cta_nodes.len() as u32);
    }
    debug_assert_eq!(cta_nodes.len(), n);

    // ── Step 3: emit ──
    let mut out = String::new();
    writeln!(
        out,
        "// AUTO-GENERATED by scheduled_codegen.rs — do not edit."
    )
    .unwrap();
    writeln!(
        out,
        "// {} nodes, {} edges, {} CTAs",
        n,
        all_deps.len(),
        num_ctas
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "#pragma once").unwrap();
    writeln!(out, "#include <cstdint>").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "namespace pfl_sched {{").unwrap();
    writeln!(out, "constexpr uint32_t NUM_NODES = {};", n).unwrap();
    writeln!(out, "constexpr uint32_t NUM_EDGES = {};", all_deps.len()).unwrap();
    writeln!(out, "constexpr uint32_t NUM_CTAS  = {};", num_ctas).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// Phase tags").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ATTN_NORM = 0;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_QKV       = 1;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ROPE      = 2;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_ATTENTION = 3;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_O_PROJ    = 4;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_MLP_NORM  = 5;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_GATE_UP   = 6;").unwrap();
    writeln!(out, "constexpr uint32_t PHASE_DOWN      = 7;").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "struct NodeRecord {{\n  uint32_t phase;\n  uint16_t layer;\n  uint16_t row;\n  uint16_t col;\n  uint16_t dep_count;\n  uint32_t dep_off;\n}};"
    ).unwrap();
    writeln!(out).unwrap();

    // SCHED_NODES
    writeln!(
        out,
        "static __device__ const NodeRecord SCHED_NODES[NUM_NODES] = {{"
    )
    .unwrap();
    for nd in &dag.nodes {
        writeln!(
            out,
            "  {{ {}, {}, {}, {}, {}, {} }},",
            phase_tag(nd.phase),
            nd.layer,
            nd.row,
            nd.col,
            node_dep_cnt[nd.id.0 as usize],
            node_dep_off[nd.id.0 as usize],
        )
        .unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    // SCHED_ALL_DEPS — emit as raw u32 array. May be very large; chunk per line.
    writeln!(
        out,
        "static __device__ const uint32_t SCHED_ALL_DEPS[NUM_EDGES] = {{"
    )
    .unwrap();
    emit_u32_chunked(&mut out, &all_deps);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    // CTA offset prefix table
    writeln!(
        out,
        "static __device__ const uint32_t SCHED_CTA_OFFSETS[NUM_CTAS + 1] = {{"
    )
    .unwrap();
    emit_u32_chunked(&mut out, &cta_offsets);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    // Per-CTA node-id list, ordered by schedule
    writeln!(
        out,
        "static __device__ const uint32_t SCHED_CTA_NODES[NUM_NODES] = {{"
    )
    .unwrap();
    emit_u32_chunked(&mut out, &cta_nodes);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "}}  // namespace pfl_sched").unwrap();

    out
}

fn emit_u32_chunked(out: &mut String, vals: &[u32]) {
    const PER_LINE: usize = 16;
    for chunk in vals.chunks(PER_LINE) {
        out.push_str("  ");
        for v in chunk {
            write!(out, "{},", v).unwrap();
        }
        out.push('\n');
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reified_dag::{LlamaDims, TileSizes};
    use crate::schedule::{CostModel, schedule};

    fn tiny_dims() -> LlamaDims {
        // 2-layer, seq=32 toy model — keeps the emitted text small enough to
        // sanity-check by eye.
        LlamaDims {
            num_layers: 2,
            hidden_dim: 256,
            intermediate_dim: 512,
            num_attn_heads: 4,
            num_kv_heads: 2,
            head_dim: 64,
            seq_len: 32,
        }
    }

    #[test]
    fn emit_smoke() {
        let dag = ReifiedDag::reify_llama(tiny_dims(), TileSizes::default_v1());
        let cost = CostModel::from_dag(&dag);
        let sched = schedule(&dag, 4, &cost);
        let cpp = emit_schedule_cpp(&dag, &sched);

        assert!(cpp.contains("namespace pfl_sched"));
        assert!(cpp.contains("constexpr uint32_t NUM_NODES ="));
        assert!(cpp.contains("SCHED_NODES"));
        assert!(cpp.contains("SCHED_ALL_DEPS"));
        assert!(cpp.contains("SCHED_CTA_OFFSETS"));
        assert!(cpp.contains("SCHED_CTA_NODES"));
        // Sanity: NUM_NODES line matches actual node count.
        let n = dag.nodes.len();
        assert!(cpp.contains(&format!("NUM_NODES = {n}")));
    }

    #[test]
    fn cta_offsets_partition_all_nodes() {
        // Every node must appear in exactly one CTA's slice.
        let dag = ReifiedDag::reify_llama(tiny_dims(), TileSizes::default_v1());
        let cost = CostModel::from_dag(&dag);
        let sched = schedule(&dag, 4, &cost);

        // Re-build the same per-CTA grouping the emitter does and verify.
        let mut per_cta: Vec<Vec<u32>> = vec![Vec::new(); sched.num_ctas as usize];
        for p in &sched.placements {
            per_cta[p.cta as usize].push(p.node.0);
        }
        let total: usize = per_cta.iter().map(|v| v.len()).sum();
        assert_eq!(total, dag.nodes.len());

        // No node id appears twice across CTAs.
        let mut seen = vec![false; dag.nodes.len()];
        for v in &per_cta {
            for &nid in v {
                assert!(!seen[nid as usize], "node {nid} placed twice");
                seen[nid as usize] = true;
            }
        }
        assert!(seen.iter().all(|&b| b));
    }

    #[test]
    fn schedule_order_within_cta_is_monotonic_in_start_time() {
        // The emitter sorts each CTA's nodes by start time. Verify that the
        // resulting order also respects topological order (no node appears
        // before all its CTA-local deps).
        let dag = ReifiedDag::reify_llama(tiny_dims(), TileSizes::default_v1());
        let cost = CostModel::from_dag(&dag);
        let sched = schedule(&dag, 4, &cost);

        let mut per_cta: Vec<Vec<(u64, u32)>> = vec![Vec::new(); sched.num_ctas as usize];
        for p in &sched.placements {
            per_cta[p.cta as usize].push((p.start, p.node.0));
        }
        for v in &mut per_cta {
            v.sort_by_key(|&(t, _)| t);
            for window in v.windows(2) {
                assert!(window[0].0 <= window[1].0);
            }
        }
    }
}
