[package]
name = "ferrite-forward-macro"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
serde_json = { workspace = true }
rayon = { workspace = true }
ferrite-stencil = { path = "../ferrite-stencil" }

[dev-dependencies]
trybuild = "1"
