// SPDX-License-Identifier: Apache-2.0
//! FFI bindings to the compiled static megakernel (decode + prefill).
//!
//! Uses the same flat `TkTensorArg` calling convention as `tk_llama_1b_launch`
//! in vllm-tk. The C-side wrappers construct the TK `globals` struct from these
//! flat args, then call the static kernel (no VM dispatch).

// Re-use the TkTensorArg generated by the megakernel! proc-macro.
// Same #[repr(C)] layout as the C-side TkTensorArg struct.
use super::TkTensorArg;

// The FFI signatures match the generated C launch wrappers in the compiled .cu file.
// Both take the same flat args as tk_llama_1b_launch (same globals construction),
// but call the static decode/prefill kernels instead of the KVM.
unsafe extern "C" {
    /// Static decode kernel: 1 token per sequence, batch_size sequences.
    /// No VM instruction dispatch — calls TK ops directly in compiled order.
    /// Static decode kernel: 1 token per sequence, batch_size sequences.
    /// Returns 0 on success, CUDA error code on failure, -1 on C++ exception.
    pub fn llama_sm89_decode_static_launch(
        bar: TkTensorArg,
        instructions: TkTensorArg,
        timings: TkTensorArg,
        qkv_w: TkTensorArg,
        attn_norm_w: TkTensorArg,
        o_w: TkTensorArg,
        mlp_norm_w: TkTensorArg,
        up_w: TkTensorArg,
        gate_w: TkTensorArg,
        down_w: TkTensorArg,
        lm_norm_w: TkTensorArg,
        lm_w: TkTensorArg,
        k_cache: TkTensorArg,
        v_cache: TkTensorArg,
        rope_cos: TkTensorArg,
        rope_sin: TkTensorArg,
        hidden: TkTensorArg,
        rms_rope: TkTensorArg,
        rms_gate: TkTensorArg,
        q_post: TkTensorArg,
        attn_out: TkTensorArg,
        silu: TkTensorArg,
        rms_lm: TkTensorArg,
        logits: TkTensorArg,
        pos_ids: TkTensorArg,
        kv_indptr: TkTensorArg,
        kv_indices: TkTensorArg,
        kv_last_page: TkTensorArg,
        kv_append: TkTensorArg,
        prefill_qo_indptr: TkTensorArg,
        prefill_kv_indptr: TkTensorArg,
        prefill_kv_indices: TkTensorArg,
        prefill_kv_last_page_len: TkTensorArg,
        attn_scale: f32,
        rms_norm_eps: f32,
        num_pages: i32,
        batch_size: i32,
        num_prefill_tokens: i32,
        stream: u64,
    ) -> i32;

    /// Static prefill kernel: variable-length sequences.
    /// Returns 0 on success, CUDA error code on failure, -1 on C++ exception.
    pub fn llama_sm89_prefill_static_launch(
        bar: TkTensorArg,
        instructions: TkTensorArg,
        timings: TkTensorArg,
        qkv_w: TkTensorArg,
        attn_norm_w: TkTensorArg,
        o_w: TkTensorArg,
        mlp_norm_w: TkTensorArg,
        up_w: TkTensorArg,
        gate_w: TkTensorArg,
        down_w: TkTensorArg,
        lm_norm_w: TkTensorArg,
        lm_w: TkTensorArg,
        k_cache: TkTensorArg,
        v_cache: TkTensorArg,
        rope_cos: TkTensorArg,
        rope_sin: TkTensorArg,
        hidden: TkTensorArg,
        rms_rope: TkTensorArg,
        rms_gate: TkTensorArg,
        q_post: TkTensorArg,
        attn_out: TkTensorArg,
        silu: TkTensorArg,
        rms_lm: TkTensorArg,
        logits: TkTensorArg,
        pos_ids: TkTensorArg,
        kv_indptr: TkTensorArg,
        kv_indices: TkTensorArg,
        kv_last_page: TkTensorArg,
        kv_append: TkTensorArg,
        prefill_qo_indptr: TkTensorArg,
        prefill_kv_indptr: TkTensorArg,
        prefill_kv_indices: TkTensorArg,
        prefill_kv_last_page_len: TkTensorArg,
        attn_scale: f32,
        rms_norm_eps: f32,
        num_pages: i32,
        batch_size: i32,
        num_prefill_tokens: i32,
        stream: u64,
    ) -> i32;
}
