// SPDX-License-Identifier: Apache-2.0
//! FFI bindings to the compiled static megakernel variants (decode + prefill).
//!
//! Each variant is compiled for a specific (HD, ID, HDM, NAH, NKH) tuple.
//! NL (num_layers) is a runtime parameter passed to every launch.
//!
//! To add a new variant: add extern declarations here matching the symbol
//! names generated by build.rs (pattern: `{name}_decode_static_launch`).

use super::TkTensorArg;

/// Common launch signature type (decode). All variants share this signature.
pub type DecodeLaunchFn = unsafe extern "C" fn(
    TkTensorArg,
    TkTensorArg,
    TkTensorArg, // bar, instructions, timings
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg, // qkv, attn_norm, o, mlp_norm
    TkTensorArg,
    TkTensorArg,
    TkTensorArg, // up, gate, down
    TkTensorArg,
    TkTensorArg, // lm_norm, lm
    TkTensorArg,
    TkTensorArg, // k_cache, v_cache
    TkTensorArg,
    TkTensorArg, // rope_cos, rope_sin
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg, // hidden, rms_rope, rms_gate, q_post
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg, // attn_out, silu, rms_lm, logits
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg, // pos, kv_indptr, kv_idx, kv_last, kv_app
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg, // pfx_qo, pfx_kv_ind, pfx_kv_idx, pfx_kv_last
    f32,
    f32, // attn_scale, rms_norm_eps
    i32,
    i32,
    i32,
    i32, // num_pages, batch_size, num_prefill_tokens, num_layers
    u64, // stream
) -> i32;

/// Common launch signature type (prefill). Same as decode + seq metadata.
pub type PrefillLaunchFn = unsafe extern "C" fn(
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    TkTensorArg,
    f32,
    f32,
    i32,
    i32,
    i32,
    i32,
    u64,
    *const i32,
    *const i32, // seq_chunk_lens, seq_extend_offsets
) -> i32;

/// Declare decode + prefill extern "C" symbols for a variant.
/// The symbol names match those generated by build.rs / cuda_codegen.rs:
///   `{name}_decode_static_launch` and `{name}_prefill_static_launch`.
macro_rules! declare_variant {
    ($decode:ident, $prefill:ident) => {
        pub fn $decode(
            bar: TkTensorArg,
            instructions: TkTensorArg,
            timings: TkTensorArg,
            qkv_w: TkTensorArg,
            attn_norm_w: TkTensorArg,
            o_w: TkTensorArg,
            mlp_norm_w: TkTensorArg,
            up_w: TkTensorArg,
            gate_w: TkTensorArg,
            down_w: TkTensorArg,
            lm_norm_w: TkTensorArg,
            lm_w: TkTensorArg,
            k_cache: TkTensorArg,
            v_cache: TkTensorArg,
            rope_cos: TkTensorArg,
            rope_sin: TkTensorArg,
            hidden: TkTensorArg,
            rms_rope: TkTensorArg,
            rms_gate: TkTensorArg,
            q_post: TkTensorArg,
            attn_out: TkTensorArg,
            silu: TkTensorArg,
            rms_lm: TkTensorArg,
            logits: TkTensorArg,
            pos_ids: TkTensorArg,
            kv_indptr: TkTensorArg,
            kv_indices: TkTensorArg,
            kv_last_page: TkTensorArg,
            kv_append: TkTensorArg,
            pfx_qo_indptr: TkTensorArg,
            pfx_kv_indptr: TkTensorArg,
            pfx_kv_indices: TkTensorArg,
            pfx_kv_last_page_len: TkTensorArg,
            attn_scale: f32,
            rms_norm_eps: f32,
            num_pages: i32,
            batch_size: i32,
            num_prefill_tokens: i32,
            num_layers: i32,
            stream: u64,
        ) -> i32;

        pub fn $prefill(
            bar: TkTensorArg,
            instructions: TkTensorArg,
            timings: TkTensorArg,
            qkv_w: TkTensorArg,
            attn_norm_w: TkTensorArg,
            o_w: TkTensorArg,
            mlp_norm_w: TkTensorArg,
            up_w: TkTensorArg,
            gate_w: TkTensorArg,
            down_w: TkTensorArg,
            lm_norm_w: TkTensorArg,
            lm_w: TkTensorArg,
            k_cache: TkTensorArg,
            v_cache: TkTensorArg,
            rope_cos: TkTensorArg,
            rope_sin: TkTensorArg,
            hidden: TkTensorArg,
            rms_rope: TkTensorArg,
            rms_gate: TkTensorArg,
            q_post: TkTensorArg,
            attn_out: TkTensorArg,
            silu: TkTensorArg,
            rms_lm: TkTensorArg,
            logits: TkTensorArg,
            pos_ids: TkTensorArg,
            kv_indptr: TkTensorArg,
            kv_indices: TkTensorArg,
            kv_last_page: TkTensorArg,
            kv_append: TkTensorArg,
            pfx_qo_indptr: TkTensorArg,
            pfx_kv_indptr: TkTensorArg,
            pfx_kv_indices: TkTensorArg,
            pfx_kv_last_page_len: TkTensorArg,
            attn_scale: f32,
            rms_norm_eps: f32,
            num_pages: i32,
            batch_size: i32,
            num_prefill_tokens: i32,
            num_layers: i32,
            stream: u64,
            seq_chunk_lens: *const i32,
            seq_extend_offsets: *const i32,
        ) -> i32;
    };
}

unsafe extern "C" {
    // Llama 1B (HD=2048, HDM=64)
    declare_variant!(
        llama_sm89_hd2048_hdm64_decode_static_launch,
        llama_sm89_hd2048_hdm64_prefill_static_launch
    );
    // NOTE: Llama 3B (HD=3072) has GQA_RATIO=3, not supported by attention kernel.
    // Llama 8B (HD=4096, HDM=128)
    declare_variant!(
        llama_sm89_hd4096_hdm128_decode_static_launch,
        llama_sm89_hd4096_hdm128_prefill_static_launch
    );
    // NOTE: 70B (HD=8192) and 405B (HD=16384) exceed sm89 shared memory budget.
}
