// SPDX-License-Identifier: Apache-2.0
//! Static megakernel for LLaMA decode/prefill (sm89), with multi-variant support.
//!
//! Multiple model dimension variants are compiled at build time.
//! At runtime, `KernelVariant::from_dims()` selects the correct compiled kernel
//! based on the model's (HD, ID, HDM, NAH, NKH) dimensions.
//!
//! NL (num_layers) is a runtime parameter — models with different layer counts
//! but the same dimension tuple share a kernel variant.

// The megakernel! proc-macro generates:
// - Typed handles, TkTensorArg, newtypes, LaunchArgs (from default dims)
// - KernelVariant enum, FFI declarations, from_dims(), dispatch (from variants block)
vllm_tk_macros::megakernel! {
    kernel llama_sm89<NL=16, HD=2048, ID=8192, HDM=64, NAH=32, NKH=8, VS=128256> {
        for layer in 0..NL {
            let normed = rmsnorm(hidden_states, attn_norm[layer]);
            let qkv = gemm(normed, qkv_weights[layer]);
            let (q, k, v) = rope_append(qkv, positions, kv_cache[layer]);
            let attn = attention_decode(q, k, v, kv_cache[layer], block_table);
            hidden_states = gemm_add(attn, o_proj[layer], hidden_states);

            let normed2 = rmsnorm(hidden_states, mlp_norm[layer]);
            let gate = silu(gemm(normed2, gate_weights[layer]));
            let up = gemm(normed2, up_weights[layer]);
            hidden_states = gemm_add(gate * up, down_proj[layer], hidden_states);
        }
        let normed = rmsnorm(hidden_states, lm_head_norm);
        logits = gemm(normed, lm_head);
    }
    variants {
        Hd2048Hdm64:  { HD=2048, ID=8192,  HDM=64,  NAH=32, NKH=8 },
        Hd4096Hdm128: { HD=4096, ID=14336, HDM=128, NAH=32, NKH=8 },
    }
}

// KernelVariant enum, FFI declarations, from_dims(), and dispatch methods
// are all generated by the megakernel! macro's `variants` block above.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn struct_exists_with_correct_dims() {
        assert_eq!(MegakernelLlamaSm89::NL, 16);
        assert_eq!(MegakernelLlamaSm89::HD, 2048);
        assert_eq!(MegakernelLlamaSm89::ID, 8192);
        assert_eq!(MegakernelLlamaSm89::QKV_DIM, 3072);
        assert_eq!(MegakernelLlamaSm89::NUM_OPS, 13);
    }

    #[test]
    fn pipeline_diagram_not_empty() {
        assert!(!MegakernelLlamaSm89::PIPELINE_DIAGRAM.is_empty());
    }

    #[test]
    fn cuda_source_has_both_kernels() {
        let src = MegakernelLlamaSm89::CUDA_SOURCE;
        assert!(src.contains("llama_sm89_decode_static"));
        assert!(src.contains("llama_sm89_prefill_static"));
        assert!(src.contains("OPCODE_GQA_AttentionDecode"));
        assert!(src.contains("OPCODE_GQA_AttentionPrefill"));
    }

    #[test]
    fn kernel_variant_from_dims() {
        // 1B
        assert!(matches!(
            KernelVariant::from_dims(2048, 8192, 64, 32, 8),
            Ok(KernelVariant::Hd2048Hdm64)
        ));
        // 3B — GQA_RATIO=3 not supported by attention kernel
        assert!(KernelVariant::from_dims(3072, 8192, 128, 24, 8).is_err());
        // 8B
        assert!(matches!(
            KernelVariant::from_dims(4096, 14336, 128, 32, 8),
            Ok(KernelVariant::Hd4096Hdm128)
        ));
        // 70B — exceeds sm89 shared memory, should fail
        assert!(KernelVariant::from_dims(8192, 28672, 128, 64, 8).is_err());
        // Unsupported
        let err = KernelVariant::from_dims(1024, 4096, 64, 16, 4);
        assert!(err.is_err());
        assert!(err.unwrap_err().contains("no compiled TK kernel variant"));
    }

    #[test]
    fn typed_handles_exist() {
        let _: fn(&GpuActivation<2048>) = |_| {};
        let _: fn(&GpuActivationBig<8192>) = |_| {};
        let _: fn(&GpuWeight<3072, 2048>) = |_| {};
        let _: fn(&GpuWeightBig<2048, 8192>) = |_| {};
        let _: fn(&GpuNormWeight<2048>) = |_| {};
        let _: fn(&GpuLogits<128256>) = |_| {};
        let _: fn(&GpuKvCache) = |_| {};
        let _: fn(&GpuRopeTable<64>) = |_| {};
        let _: fn(&GpuMetaVec) = |_| {};
        let _: fn(&GpuBarrier) = |_| {};
        let _: fn(&GpuVmLayout) = |_| {};
    }

    #[test]
    fn tk_tensor_arg_new() {
        let arg1d = TkTensorArg::new(0xDEAD, &[128]);
        assert_eq!(arg1d.ptr, 0xDEAD);
        assert_eq!((arg1d.b, arg1d.d, arg1d.r, arg1d.c), (1, 1, 1, 128));

        let arg2d = TkTensorArg::new(0xBEEF, &[32, 2048]);
        assert_eq!((arg2d.b, arg2d.d, arg2d.r, arg2d.c), (1, 1, 32, 2048));
    }

    #[test]
    fn cuda_source_has_runtime_num_layers() {
        let src = MegakernelLlamaSm89::CUDA_SOURCE;
        // NL should NOT be a constexpr
        assert!(!src.contains("static constexpr int NL"));
        // Loop should use runtime num_layers
        assert!(src.contains("for (int layer = 0; layer < num_layers; layer++)"));
        // Launch wrapper should accept num_layers
        assert!(src.contains("int num_layers"));
    }
}
