// SPDX-License-Identifier: Apache-2.0
//! `cuda_emit` — pure literal transcription of a typed [`MegaTape`]
//! into a complete `.cu` translation unit, calling **TK 2.0
//! primitives only** (`third_party/thunderkittens/include/`).
//!
//! See `MEGA_IR_PLAN.md` §0 / §8.0 / §8.0a + `CUDA_EMIT_TK20_AUDIT.md`
//! at the worktree root for the contract. The DOD for any variant
//! shipping is **the emitted `.cu` compiles against TK 2.0 on the
//! pod** — Rust unit tests are not the ground truth.
//!
//! Module layout:
//!
//! - [`cu`] — emitted-CUDA AST: [`CuExpr`] / [`CuStmt`] /
//!   [`CuBlock`] / [`CuVariant`].
//! - [`handles`] — typed handles ([`Sv`], [`Rv`], [`Semaphore`],
//!   [`GmemPtrRaw`], [`ScratchPtr`]) and ferrite substrate
//!   accessors (page_ready_sem, page_as_sv_bf, scratch_as,
//!   gmem_*_raw).
//! - [`tk20`] — Rust API surface mirroring TK 2.0's C++ primitive
//!   surface. Each fn cites its TK 2.0 source line.
//! - [`roles`] — per-`MegaNode` role-body emit.
//!
//! [`Sv`]: handles::Sv
//! [`Rv`]: handles::Rv
//! [`Semaphore`]: handles::Semaphore
//! [`GmemPtrRaw`]: handles::GmemPtrRaw
//! [`ScratchPtr`]: handles::ScratchPtr

pub mod cu;
pub mod handles;
pub mod roles;
pub mod tk20;

use crate::tape::{MegaTape, TapeBudget};

pub use cu::{CuBlock, CuExpr, CuStmt, CuVariant};

/// Lower a typed [`MegaTape`] to a complete `.cu` translation unit
/// for the named canonical, against TK 2.0 primitives only.
pub fn lower_to_cuda(canonical: &str, tape: &MegaTape) -> CuVariant {
    let budget = tape.budget();

    let mut loader_block = CuBlock::new();
    let mut launcher_block = CuBlock::new();
    let mut consumer_block = CuBlock::new();
    let mut storer_block = CuBlock::new();
    let mut skipped: Vec<String> = Vec::new();

    for (idx, node) in tape.nodes().iter().enumerate() {
        let bodies = roles::emit_role_bodies(node, budget);
        if let Some(variant) = bodies.skipped {
            skipped.push(variant.to_string());
            let marker = CuStmt::new(format!("// SKIPPED node[{idx}]: {variant}"));
            loader_block.push(marker.clone());
            launcher_block.push(marker.clone());
            consumer_block.push(marker.clone());
            storer_block.push(marker);
            continue;
        }
        loader_block.extend(bodies.loader);
        launcher_block.extend(bodies.launcher);
        consumer_block.extend(bodies.consumer);
        storer_block.extend(bodies.storer);
    }

    let source = render_source(
        canonical,
        &budget,
        &loader_block,
        &launcher_block,
        &consumer_block,
        &storer_block,
    );

    CuVariant {
        canonical: canonical.to_string(),
        source,
        skipped_variants: skipped,
    }
}

/// Render the full `.cu` text. Substrate scaffolding (includes,
/// per-canonical Config struct, role-body fns, kernel entry) wraps
/// the four role blocks emitted from per-MegaNode bodies.
fn render_source(
    canonical: &str,
    budget: &TapeBudget,
    loader: &CuBlock,
    launcher: &CuBlock,
    consumer: &CuBlock,
    storer: &CuBlock,
) -> String {
    // Register budgets — substrate-implementation values matching
    // the ferrite-side `set_consumer_registers<Config>` /
    // `set_non_consumer_registers<Config>` wrappers in
    // `ferrite_warp_roles.cuh`. Promoting these to per-canonical
    // values is a future sprint.
    const CONSUMER_REGISTERS: u32 = 240;
    const NON_CONSUMER_REGISTERS: u32 = 24;
    const INSTRUCTION_PIPE_STAGES: u32 = 4;

    let kernel_name = format!("ferrite_{canonical}_launch");
    let cfg_name = format!("Config_{canonical}");

    let mut s = String::new();
    s.push_str("// SPDX-License-Identifier: Apache-2.0\n");
    s.push_str(&format!(
        "// Auto-generated by ferrite-mega-ir::cuda_emit for canonical \"{canonical}\".\n"
    ));
    s.push_str("// DO NOT EDIT — regenerate by re-running the proc-macro.\n\n");

    // Includes: ferrite substrate + ferrite barrier (cross-CTA gmem
    // counters). The substrate `.cuh`s pull in `kittens.cuh`
    // transitively (see ferrite_substrate.cuh:31).
    s.push_str("#include \"ferrite_substrate.cuh\"\n");
    s.push_str("#include \"ferrite_globals.cuh\"\n");
    s.push_str("#include \"ferrite_warp_roles.cuh\"\n");
    s.push_str("#include \"ferrite_barrier.cuh\"\n\n");

    s.push_str("namespace {\n\n");

    // Per-canonical Config struct.
    s.push_str(&format!("struct {cfg_name} {{\n"));
    s.push_str(&format!(
        "    static constexpr int NUM_CONSUMER_WARPS = {};\n",
        budget.num_consumer_warps
    ));
    s.push_str(&format!(
        "    static constexpr int NON_CONSUMER_REGISTERS = {NON_CONSUMER_REGISTERS};\n"
    ));
    s.push_str(&format!(
        "    static constexpr int CONSUMER_REGISTERS = {CONSUMER_REGISTERS};\n"
    ));
    s.push_str(&format!(
        "    static constexpr int NUM_PAGES = {};\n",
        budget.num_pages
    ));
    s.push_str(&format!(
        "    static constexpr int PAGE_SIZE = {};\n",
        budget.page_size
    ));
    s.push_str(&format!(
        "    static constexpr int SCRATCH_BYTES = {};\n",
        budget.scratch_bytes
    ));
    s.push_str(&format!(
        "    static constexpr int INSTRUCTION_PIPE_STAGES = {INSTRUCTION_PIPE_STAGES};\n"
    ));
    s.push_str("};\n");
    s.push_str(&format!("using ConfigT = {cfg_name};\n\n"));

    // Globals struct — kernel-internal aggregation of the host
    // ABI's positional args, packaged so role-body fns take a
    // single-arg reference.
    s.push_str("struct Globals {\n");
    s.push_str("    __nv_bfloat16* const*       act_ptrs;\n");
    s.push_str("    const __nv_bfloat16* const* weight_ptrs;\n");
    s.push_str("    int32_t*                    barrier_slots;\n");
    s.push_str("    int32_t                     trace_level;\n");
    s.push_str("};\n\n");

    // Role-body fns (forward-declared as `__device__
    // __forceinline__` so the kernel can dispatch by warp role).
    s.push_str(
        "__device__ __forceinline__ void loader_body(const Globals& g, ferrite::SharedState<ConfigT>& ss) {\n",
    );
    s.push_str(&loader.render(4));
    s.push_str("}\n\n");

    s.push_str(
        "__device__ __forceinline__ void launcher_body(const Globals& g, ferrite::SharedState<ConfigT>& ss) {\n",
    );
    s.push_str(&launcher.render(4));
    s.push_str("}\n\n");

    s.push_str(
        "__device__ __forceinline__ void consumer_body(const Globals& g, ferrite::SharedState<ConfigT>& ss) {\n",
    );
    s.push_str(&consumer.render(4));
    s.push_str("}\n\n");

    s.push_str(
        "__device__ __forceinline__ void storer_body(const Globals& g, ferrite::SharedState<ConfigT>& ss) {\n",
    );
    s.push_str(&storer.render(4));
    s.push_str("}\n\n");

    // Kernel entry. Signature matches the host-side base-tier
    // `LaunchFn` ABI in `crates/ferrite-forward/src/interpreter/
    // mega/mod.rs:370`.
    s.push_str(&format!("extern \"C\" __global__ void {kernel_name}(\n"));
    s.push_str("    __nv_bfloat16* const*       act_ptrs,\n");
    s.push_str("    const __nv_bfloat16* const* weight_ptrs,\n");
    s.push_str("    int32_t*                    barrier_slots,\n");
    s.push_str("    int32_t                     trace_level\n");
    s.push_str(") {\n");
    s.push_str("    extern __shared__ uint8_t shmem_buf[];\n");
    s.push_str("    auto& ss = *reinterpret_cast<ferrite::SharedState<ConfigT>*>(shmem_buf);\n");
    s.push_str("    ferrite::init_shared_state<ConfigT>(ss);\n");
    s.push_str(
        "    Globals g{act_ptrs, weight_ptrs, barrier_slots, trace_level};\n",
    );
    s.push_str("    int wid = kittens::warpid();\n");
    s.push_str("    if (wid < ConfigT::NUM_CONSUMER_WARPS) {\n");
    s.push_str("        ferrite::set_consumer_registers<ConfigT>();\n");
    s.push_str("        consumer_body(g, ss);\n");
    s.push_str("    } else {\n");
    s.push_str("        ferrite::set_non_consumer_registers<ConfigT>();\n");
    s.push_str("        switch (wid - ConfigT::NUM_CONSUMER_WARPS) {\n");
    s.push_str(
        "            case ferrite::kLoaderSlot:   loader_body(g, ss); break;\n",
    );
    s.push_str(
        "            case ferrite::kLauncherSlot: launcher_body(g, ss); break;\n",
    );
    s.push_str(
        "            case ferrite::kStorerSlot:   storer_body(g, ss); break;\n",
    );
    s.push_str("        }\n");
    s.push_str("    }\n");
    s.push_str("}\n\n");

    s.push_str("} // namespace\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lower::MegaTapeBuilder;
    use crate::nodes::LayerIndex;
    use crate::substrate::{
        ActSlotConst, ArrivesCount, BarSyncId, BarSyncPair, HiddenDim, MbarrierPhase,
        NumTokensConst, PageId, RmsNormScope, ScratchRegion, WeightAccessorConst,
    };

    type BuilderD = MegaTapeBuilder<8, 8, 32_768, 32_768, 4>;

    /// Sprint 1: Rust-side smoke. Verifies the emit walks without
    /// panicking AND that key TK 2.0 primitive calls land in the
    /// emitted source. The REAL DOD is `nvcc` compiling this on
    /// the pod — see CUDA_EMIT_TK20_AUDIT.md §15.
    #[test]
    fn rms_norm_emits_tk20_calls() {
        let mut b = BuilderD::new();
        b.push_rms_norm(
            ArrivesCount::<0>::new(),
            PageId::<0, 8>::new(),
            PageId::<1, 8>::new(),
            ScratchRegion::<0, 32, 32_768, RmsNormScope>::new(),
            MbarrierPhase::<0>::new(),
            MbarrierPhase::<1>::new(),
            LayerIndex::<0, 16>::new(),
            HiddenDim::<2048>::new(),
            NumTokensConst::<1>::new(),
            ActSlotConst::<0, { u32::MAX }>::new(),
            ActSlotConst::<1, { u32::MAX }>::new(),
            WeightAccessorConst::<7, { u32::MAX }>::new(),
            BarSyncId::<3>::new(),
            BarSyncId::<4>::new(),
            BarSyncPair::<3, 4>::new(),
            "W::rms".to_string(),
            1.0e-5_f32,
        );
        let tape = b.finish(16);
        let cu = lower_to_cuda("test_rms", &tape);
        assert!(cu.skipped_variants.is_empty());

        // Dump for visual inspection / pod compile.
        std::fs::write("/tmp/rms_norm_emit.cu", &cu.source).ok();

        // Substrate scaffolding present.
        for needle in [
            "#include \"ferrite_substrate.cuh\"",
            "#include \"ferrite_warp_roles.cuh\"",
            "struct Config_test_rms",
            "static constexpr int NUM_CONSUMER_WARPS = 8;",
            "extern \"C\" __global__ void ferrite_test_rms_launch(",
            "ferrite::set_consumer_registers<ConfigT>();",
        ] {
            assert!(
                cu.source.contains(needle),
                "expected {needle:?} in source, got:\n{}",
                cu.source
            );
        }

        // TK 2.0 primitive calls (every `kittens::group<N>::*` call
        // from the per-variant emit must be a TK 2.0 surface
        // citation; see roles.rs::emit_rms_norm comment block).
        for needle in [
            "kittens::group<1>::wait(",
            "kittens::group<1>::tma::expect_bytes(",
            "kittens::group<1>::tma::load_async(",
            "kittens::group<1>::tma::store_async(",
            "kittens::group<1>::tma::store_async_wait();",
            "kittens::group<1>::arrive(",
            "kittens::group<8>::load(__rms_act_rv,",
            "kittens::group<8>::store(",
            "kittens::group<8>::sync(3);",
            "kittens::group<8>::sync(4);",
            "kittens::warp::copy(__rms_sq_rv, __rms_act_rv);",
            "kittens::warp::mul(__rms_sq_rv, __rms_sq_rv, __rms_sq_rv);",
            "kittens::warp::sum(__rms_partial_sum, __rms_sq_rv);",
            "kittens::warp::mul(__rms_act_rv, __rms_act_rv, __rms_scale);",
            "kittens::warp::mul(__rms_act_rv, __rms_act_rv, __rms_weight_rv);",
            "kittens::rv_fl<256> __rms_act_rv;",
            "rsqrtf(__rms_full_sum / 2048.0f + 1e-5f)",
        ] {
            assert!(
                cu.source.contains(needle),
                "expected TK 2.0 call {needle:?} in source, got:\n{}",
                cu.source
            );
        }

        // (S2 negative shared with rms_norm's NEGATIVE block below.)

        // NEGATIVE: must NOT contain any TK 1.0 / VM-reference
        // patterns or pre-existing ferrite_tk_helpers.cuh wrappers.
        for forbidden in [
            // TK 1.0 free-function pattern.
            "kittens::wait(",
            "kittens::arrive(",
            "kittens::tma::load_async(",
            "kittens::tma::expect_bytes(",
            // Manual per-warp slice carving (the nuked emit's pattern).
            "kittens::warpid() * ",
            "* sizeof(__nv_bfloat16))",
            // ferrite::tk wrappers (Sprint 1 = TK 2.0 only).
            "ferrite::tk::rms_norm_vec",
            "ferrite::tk::rms_norm_scale_from_rv",
        ] {
            assert!(
                !cu.source.contains(forbidden),
                "FORBIDDEN pattern {forbidden:?} found in source — TK 1.0 pollution. Source:\n{}",
                cu.source
            );
        }
    }

    /// Sprint 5: FusedAddRmsNorm — residual+=delta, then RmsNorm,
    /// in-place to residual page.
    #[test]
    fn fused_add_rms_norm_emits_tk20_calls() {
        use crate::substrate::RmsNormScope;
        let mut b = BuilderD::new();
        b.push_fused_add_rms_norm(
            ArrivesCount::<0>::new(),
            PageId::<0, 8>::new(), // delta
            PageId::<1, 8>::new(), // residual
            PageId::<2, 8>::new(), // weight
            ScratchRegion::<0, 32, 32_768, RmsNormScope>::new(),
            MbarrierPhase::<0>::new(),
            MbarrierPhase::<1>::new(),
            LayerIndex::<3, 16>::new(),
            HiddenDim::<2048>::new(),
            NumTokensConst::<1>::new(),
            ActSlotConst::<0, { u32::MAX }>::new(),
            ActSlotConst::<1, { u32::MAX }>::new(),
            WeightAccessorConst::<5, { u32::MAX }>::new(),
            BarSyncId::<1>::new(),
            BarSyncId::<2>::new(),
            BarSyncPair::<1, 2>::new(),
            "W::farn".to_string(),
            1.0e-5_f32,
        );
        let tape = b.finish(16);
        let cu = lower_to_cuda("test_farn", &tape);
        assert!(cu.skipped_variants.is_empty());
        std::fs::write("/tmp/fused_add_rms_norm_emit.cu", &cu.source).ok();

        for needle in [
            "kittens::group<8>::load(__farn_delta_rv,",
            "kittens::group<8>::load(__farn_res_rv,",
            "kittens::warp::add(__farn_res_rv, __farn_res_rv, __farn_delta_rv);",
            "kittens::warp::sum(__farn_partial_sum, __farn_sq_rv);",
            "kittens::group<8>::sync(1);",
            "kittens::group<8>::sync(2);",
            "rsqrtf(__farn_full_sum / 2048.0f + 1e-5f)",
            "kittens::warp::mul(__farn_res_rv, __farn_res_rv, __farn_scale);",
            "kittens::warp::mul(__farn_res_rv, __farn_res_rv, __farn_weight_rv);",
            "kittens::group<8>::store(",
            "g.weight_ptrs[5 * 16 + 3]",
        ] {
            assert!(
                cu.source.contains(needle),
                "expected {needle:?}, got:\n{}",
                cu.source
            );
        }
    }

    /// Sprint 4: TanhSoftCap via `kittens::warp::apply` lambda.
    #[test]
    fn tanh_soft_cap_emits_tk20_apply_lambda() {
        let mut b = BuilderD::new();
        b.push_tanh_soft_cap(
            ArrivesCount::<0>::new(),
            PageId::<6, 8>::new(),
            PageId::<7, 8>::new(),
            MbarrierPhase::<0>::new(),
            MbarrierPhase::<1>::new(),
            HiddenDim::<2048>::new(),
            NumTokensConst::<1>::new(),
            ActSlotConst::<2, { u32::MAX }>::new(),
            ActSlotConst::<3, { u32::MAX }>::new(),
            BarSyncId::<2>::new(),
            30.0_f32,
        );
        let tape = b.finish(16);
        let cu = lower_to_cuda("test_softcap", &tape);
        assert!(cu.skipped_variants.is_empty());
        std::fs::write("/tmp/tanh_soft_cap_emit.cu", &cu.source).ok();

        for needle in [
            "kittens::rv_fl<256> __tanh_rv;",
            "kittens::warp::apply(__tanh_rv, __tanh_rv,",
            "[] __device__ (int /*idx*/, float x) { return tanhf(x * (1.0f / 3e1f)) * 3e1f; }",
            "kittens::group<8>::sync(2);",
            "kittens::group<1>::tma::store_async(",
        ] {
            assert!(
                cu.source.contains(needle),
                "expected {needle:?}, got:\n{}",
                cu.source
            );
        }
    }

    /// Sprint 3: ScalarMul (in→out path; in==out exercised at user
    /// build time when the proc-macro emits a tape with aliasing).
    #[test]
    fn scalar_mul_emits_tk20_calls() {
        let mut b = BuilderD::new();
        b.push_scalar_mul(
            ArrivesCount::<0>::new(),
            PageId::<4, 8>::new(),
            PageId::<5, 8>::new(),
            MbarrierPhase::<0>::new(),
            MbarrierPhase::<1>::new(),
            HiddenDim::<2048>::new(),
            NumTokensConst::<1>::new(),
            ActSlotConst::<2, { u32::MAX }>::new(),
            ActSlotConst::<3, { u32::MAX }>::new(),
            BarSyncId::<2>::new(),
            0.5_f32,
        );
        let tape = b.finish(16);
        let cu = lower_to_cuda("test_smul", &tape);
        assert!(cu.skipped_variants.is_empty());
        std::fs::write("/tmp/scalar_mul_emit.cu", &cu.source).ok();

        for needle in [
            "kittens::rv_fl<256> __smul_rv;",
            "kittens::group<8>::load(__smul_rv,",
            "kittens::warp::mul(__smul_rv, __smul_rv, 5e-1f);",
            "kittens::group<8>::sync(2);",
            "kittens::group<1>::arrive(ss.page_done[5]);",
            "kittens::group<1>::arrive(ss.page_consumed[4]);",
            "kittens::group<1>::tma::store_async(",
        ] {
            assert!(
                cu.source.contains(needle),
                "expected {needle:?}, got:\n{}",
                cu.source
            );
        }
    }

    /// Sprint 2: Add. Same DOD pattern — Rust check + nvcc on pod.
    #[test]
    fn add_emits_tk20_calls() {
        let mut b = BuilderD::new();
        b.push_add(
            ArrivesCount::<0>::new(),
            PageId::<2, 8>::new(),
            PageId::<3, 8>::new(),
            MbarrierPhase::<0>::new(),
            MbarrierPhase::<1>::new(),
            HiddenDim::<2048>::new(),
            NumTokensConst::<1>::new(),
            ActSlotConst::<5, { u32::MAX }>::new(),
            ActSlotConst::<6, { u32::MAX }>::new(),
            BarSyncId::<2>::new(),
        );
        let tape = b.finish(16);
        let cu = lower_to_cuda("test_add", &tape);
        assert!(cu.skipped_variants.is_empty());

        std::fs::write("/tmp/add_emit.cu", &cu.source).ok();

        for needle in [
            "kittens::group<1>::tma::expect_bytes(ss.page_ready[2], 4096);",
            "kittens::group<1>::tma::expect_bytes(ss.page_ready[3], 4096);",
            "kittens::rv_fl<256> __add_delta_rv;",
            "kittens::rv_fl<256> __add_res_rv;",
            "kittens::group<8>::load(__add_delta_rv,",
            "kittens::group<8>::load(__add_res_rv,",
            "kittens::warp::add(__add_res_rv, __add_res_rv, __add_delta_rv);",
            "kittens::group<8>::store(",
            "kittens::group<8>::sync(2);",
            "kittens::group<1>::arrive(ss.page_done[3]);",
            "kittens::group<1>::arrive(ss.page_consumed[2]);",
            "kittens::group<1>::tma::store_async(",
            "kittens::group<1>::tma::store_async_wait();",
        ] {
            assert!(
                cu.source.contains(needle),
                "expected TK 2.0 call {needle:?}, got:\n{}",
                cu.source
            );
        }
    }
}
