// SPDX-License-Identifier: Apache-2.0
//! Bridges the typed weight thunks carried by `Instruction<W>` (and
//! preserved on `LoweredMetalTape` via [`Binding::Weight`]) onto live
//! `metal::Buffer` pointers the worker can bake into an ICB.
//!
//! `Instruction<W>` and the lowering pass are agnostic to whether the
//! backing weight tensor lives in CUDA device memory or a Metal
//! buffer. The worker (Phase 5.C) is the first place this distinction
//! matters: it must hand `record_compute_dispatch` a `&metal::Buffer`
//! per binding. [`MetalModelMeta`] is the trait the model loader
//! implements (eventually emitted by the `#[forward]` macro in Phase
//! 5.F) to do that lookup. The worker holds an `Arc<dyn …>` and calls
//! [`MetalModelMeta::weight_buffer`] once per `Binding::Weight` while
//! recording.
//!
//! The trait also exposes [`MetalModelMeta::kernel_extras_for`]: the
//! per-`(kernel, layer)` scalar extras (per-layer `RmsNorm.eps`, MLA
//! attention scale, partial-rope rotation dim) that the
//! `SpecializedPipelineCache` consumes. Recording loops these in
//! before `pipelines.pipeline_for(...)` to pick up the correctly
//! specialized pipeline.

#![cfg(feature = "metal")]

use ferrite_metal_kernels::metal::Buffer;

use super::lowered::{WeightBundleKind, WeightTensor};
use crate::CanonicalParams;

/// Where a weight tensor's bytes live, plus the offset into that
/// buffer. Layouts that pack many tensors into a single arena (e.g.
/// embedded weights at offsets) use the `offset` field; per-layer
/// `&Buffer` returns set `offset = 0`.
///
/// Lifetime is borrowed from the [`MetalModelMeta`] impl — typically
/// the model loader's owned weight storage. The worker holds the meta
/// in `Arc`, so the buffer outlives every recorded ICB.
pub struct BufferRef<'a> {
    pub buffer: &'a Buffer,
    pub offset: u64,
}

/// Model-side weight + scalar lookup the [`MetalWorker`](super::worker::MetalWorker)
/// uses while baking ICBs.
///
/// Implementations are typically generated by the `#[forward]` macro
/// (Phase 5.F) and back the lookup with a flat table keyed on
/// `(WtFn` function pointer, layer, [`WeightTensor`]`)`. For the
/// pre-macro Phase 5.C smoke test, hand-rolled implementations live
/// alongside the test; see [`super::worker::tests`].
pub trait MetalModelMeta<W: CanonicalParams>: Send + Sync {
    /// Resolve a single weight binding to a live Metal buffer.
    ///
    /// Called once per `Binding::Weight` while recording each bucket's
    /// ICB. Implementations should panic (with a descriptive message)
    /// when asked for a `(kind, layer, which)` triple they don't
    /// expose — the macro is supposed to make malformed lookups
    /// impossible at the type level.
    fn weight_buffer(
        &self,
        kind: &WeightBundleKind<W>,
        layer: u32,
        which: WeightTensor,
    ) -> BufferRef<'_>;
}
