#!/usr/bin/env python3
"""Generate Marlin W4A16 kernel instantiation files for vllm-rs.

Only generates INT4 weight (kU4B8 for GPTQ, kU4 for AWQ) with FP16/BF16
activations, SM80+ (stages=4).

Usage: python3 generate_w4a16_kernels.py
"""

import os
import itertools

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

FILE_HEAD_COMMENT = """\
// Auto-generated by generate_w4a16_kernels.py — W4A16 only
// clang-format off
"""

FILE_HEAD = FILE_HEAD_COMMENT + """
#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {

"""

THREAD_CONFIGS = [(128, 128, 256), (64, 256, 256), (64, 128, 128), (128, 64, 128)]
THREAD_M_BLOCKS_RAW = [0.5, 1, 2, 3, 4]

# W4A16 quant configs only
QUANT_CONFIGS = [
    # AWQ-INT4 (kU4, zero-point)
    {"b_type": "kU4", "group_blocks": [-1, 2, 4, 8]},
    # GPTQ-INT4 (kU4B8, no zero-point, bias=8)
    {"b_type": "kU4B8", "group_blocks": [-1, 0, 2, 4, 8]},
]

A_TYPES = ["kFloat16", "kBFloat16"]


def get_filtered_configs(b_type, group_blocks_list):
    """Generate all valid (threads, m_blocks, k_blocks, n_blocks, m8, group_blocks) combos."""
    configs = []
    for m_raw in THREAD_M_BLOCKS_RAW:
        thread_m_blocks = max(int(m_raw), 1)
        m_block_size_8 = m_raw == 0.5

        for thread_k, thread_n, threads in THREAD_CONFIGS:
            # Filter: 256-thread configs are restricted
            if threads == 256:
                if m_raw <= 1 and (thread_k, thread_n) != (128, 128):
                    continue
                if m_raw > 1 and (thread_k, thread_n) != (64, 256):
                    continue

            for gb in group_blocks_list:
                configs.append({
                    "threads": threads,
                    "thread_m_blocks": thread_m_blocks,
                    "thread_k_blocks": thread_k // 16,
                    "thread_n_blocks": thread_n // 16,
                    "m_block_size_8": "true" if m_block_size_8 else "false",
                    "stages": 4,
                    "group_blocks": gb,
                    "is_zp_float": "false",
                })
    return configs


def make_instantiation(a_type, b_type, c_type, s_type, cfg):
    return (
        f"template __global__ void Marlin<"
        f"vllm::{a_type}.id(), "
        f"vllm::{b_type}.id(), "
        f"vllm::{c_type}.id(), "
        f"vllm::{s_type}.id(), "
        f"{cfg['threads']}, "
        f"{cfg['thread_m_blocks']}, "
        f"{cfg['thread_n_blocks']}, "
        f"{cfg['thread_k_blocks']}, "
        f"{cfg['m_block_size_8']}, "
        f"{cfg['stages']}, "
        f"{cfg['group_blocks']}, "
        f"{cfg['is_zp_float']}>"
        f"( MARLIN_KERNEL_PARAMS );"
    )


def make_selector_entry(a_type, b_type, c_type, s_type, cfg):
    conditions = [
        f"a_type == vllm::{a_type}",
        f"b_type == vllm::{b_type}",
        f"c_type == vllm::{c_type}",
        f"s_type == vllm::{s_type}",
        f"threads == {cfg['threads']}",
        f"thread_m_blocks == {cfg['thread_m_blocks']}",
        f"thread_n_blocks == {cfg['thread_n_blocks']}",
        f"thread_k_blocks == {cfg['thread_k_blocks']}",
        f"m_block_size_8 == {cfg['m_block_size_8']}",
        f"stages == {cfg['stages']}",
        f"group_blocks == {cfg['group_blocks']}",
        f"is_zp_float == {cfg['is_zp_float']}",
    ]
    cond_str = " && ".join(conditions)

    kernel_name = (
        f"Marlin<"
        f"vllm::{a_type}.id(), "
        f"vllm::{b_type}.id(), "
        f"vllm::{c_type}.id(), "
        f"vllm::{s_type}.id(), "
        f"{cfg['threads']}, "
        f"{cfg['thread_m_blocks']}, "
        f"{cfg['thread_n_blocks']}, "
        f"{cfg['thread_k_blocks']}, "
        f"{cfg['m_block_size_8']}, "
        f"{cfg['stages']}, "
        f"{cfg['group_blocks']}, "
        f"{cfg['is_zp_float']}>"
    )

    return cond_str, kernel_name


def main():
    selector_entries = []
    total_instantiations = 0

    for qcfg in QUANT_CONFIGS:
        b_type = qcfg["b_type"]
        configs = get_filtered_configs(b_type, qcfg["group_blocks"])

        for a_type in A_TYPES:
            c_type = a_type  # W4A16: output type matches activation type
            s_type = c_type  # Scale type matches output type

            instantiations = []
            for cfg in configs:
                instantiations.append(make_instantiation(a_type, b_type, c_type, s_type, cfg))
                cond, kname = make_selector_entry(a_type, b_type, c_type, s_type, cfg)
                selector_entries.append((cond, kname))

            # Write kernel file
            fname = f"sm80_kernel_{a_type[1:].lower()}_{b_type[1:].lower()}_{c_type[1:].lower()}.cu"
            fpath = os.path.join(SCRIPT_DIR, fname)
            content = FILE_HEAD + "\n\n".join(instantiations) + "\n\n}\n"
            with open(fpath, "w") as f:
                f.write(content)
            total_instantiations += len(instantiations)
            print(f"  {fname}: {len(instantiations)} instantiations")

    # Write kernel_selector.h
    selector_str = FILE_HEAD_COMMENT
    first = True
    for cond, kname in selector_entries:
        prefix = "if" if first else "else if"
        selector_str += f"{prefix} ({cond})\n  kernel = {kname};\n"
        first = False

    sel_path = os.path.join(SCRIPT_DIR, "kernel_selector.h")
    with open(sel_path, "w") as f:
        f.write(selector_str)

    print(f"\n  kernel_selector.h: {len(selector_entries)} entries")
    print(f"  Total: {total_instantiations} kernel instantiations across all files")


if __name__ == "__main__":
    main()
