// SPDX-License-Identifier: Apache-2.0
//! Kittens-based megakernel emitter.
//!
//! # THE PLAN (re-read every commit):
//!
//! Our compiler emits CUDA that uses ThunderKittens primitives
//! directly (`kittens::gl`, `kittens::st_bf`, `kittens::sv_bf`,
//! `kittens::rt_fl`, `kittens::tma::load_async`,
//! `kittens::warpgroup::mma`, `kittens::semaphore`, `kittens::wait`,
//! `kittens::arrive`). The stencil IR (FUF → regions → wavefront
//! schedule) produces the *static* ordering; we just emit a straight-
//! line `__global__` that calls kittens ops in that order. No VM, no
//! Megakernels-style op structs (controller / loader / launcher /
//! consumer / storer), no controller warpgroup, no runtime
//! instruction fetch.
//!
//! Reference: `~/Megakernels/demos/cross-gpu-llama/` (throughput
//! branch) — real matmul-shape ops built on kittens. Their op struct
//! *bodies* show how to compose kittens primitives for real LLM
//! workloads; we port the shape, not the VM scaffolding.
//!
//! Goal: `vllm chat --model=<small-llama>` produces coherent output
//! on H100 through this emitter's output.
//!
//! Build flags (from TK `kernels/layernorm/layernorm.cu`):
//!   nvcc -DKITTENS_HOPPER -arch=sm_90a -std=c++20
//!        --extended-lambda --expt-relaxed-constexpr -O3
//!        -I ~/ThunderKittens/include
//!
//! Relation to `emit_mega.rs`: that emitter produces raw-PTX-style
//! code with hand-rolled helpers. It's the prior direction; kept for
//! reference while this emitter replaces it incrementally. When every
//! stencil region lowers cleanly through emit_kittens and vllm chat
//! runs end-to-end, emit_mega + its prelude get deleted.

use std::fmt::Write;

use crate::ir::{Megakernel, Region};

/// Emit a kittens-based megakernel .cu composing every region in
/// `mega`. Per-region emission is dispatched on `region.name`; adding
/// a new region template means adding a match arm. The common header
/// (kittens include, namespace, extern "C" launcher) is shared.
///
/// This commit covers a single region type (`"rmsnorm"`) end-to-end:
/// globals struct with `kittens::gl` for x/w/y, `__global__` kernel
/// using `warp::load` / `warp::mul` / `warp::sum` / `warp::store`,
/// and a host launcher that constructs `kittens::gl` from raw
/// pointers + dims. Other region names fall through to an empty
/// kernel body for now; follow-on commits fill in attn, gemm,
/// qkv_rope, gate_up_silu_mul, embed, residual_add, unary.
pub fn emit_kittens(mega: &Megakernel) -> String {
    let mut out = String::new();
    write_header(&mut out);
    for region in &mega.regions {
        match region.name {
            "rmsnorm" => write_rmsnorm_region(&mut out, region),
            _ => write_stub_region(&mut out, region),
        }
    }
    out
}

fn write_header(out: &mut String) {
    writeln!(out, "// AUTO-GENERATED by ferrite-stencil::emit_kittens.").unwrap();
    writeln!(
        out,
        "// Static wavefront → kittens primitives. No VM, no op structs.",
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#define KITTENS_HOPPER").unwrap();
    writeln!(out, "#include \"kittens.cuh\"").unwrap();
    writeln!(out, "#include <cuda_runtime.h>").unwrap();
    writeln!(out, "#include <cstdint>").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "using namespace kittens;").unwrap();
    writeln!(out).unwrap();
}

/// RMSNorm region: `y = x * rsqrt(mean(x^2) + eps) * w`, per-token.
/// One warp per token (blockIdx.x = token idx); hidden-dim is templated
/// on `D` so the launcher picks the right instantiation per model.
///
/// Uses the TK `kernels/layernorm/layernorm.cu` shape: `sv_bf<D>`
/// shared vectors, `warp::load` / `warp::mul` / `warp::sum` /
/// `warp::store`, warp-wide reduction via `warp::sum` writing a
/// scalar.
fn write_rmsnorm_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: rmsnorm ──").unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "struct rmsnorm_globals {{").unwrap();
    writeln!(out, "    using vec_t = sv_bf<D>;").unwrap();
    // All runtime dims (-1) so the gl constructor takes `size_t` for
    // every axis. Compile-time `D` lives in the attached `vec_t` TMA
    // descriptor; mirrors TK's layernorm.cu pattern.
    writeln!(out, "    using x_gl_t = gl<bf16, -1, -1, -1, -1, vec_t>;").unwrap();
    writeln!(out, "    using w_gl_t = gl<bf16, -1, -1, -1, -1, vec_t>;").unwrap();
    writeln!(out, "    x_gl_t x;").unwrap();
    writeln!(out, "    w_gl_t w;").unwrap();
    writeln!(out, "    x_gl_t y;").unwrap();
    writeln!(out, "    float eps;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "__global__ __launch_bounds__(32, 1)").unwrap();
    writeln!(
        out,
        "void rmsnorm_kernel(const __grid_constant__ rmsnorm_globals<D> g) {{",
    )
    .unwrap();
    writeln!(out, "    const int token = blockIdx.x;").unwrap();
    // `__shared__` aggregates must be default-constructible through a
    // shared_allocator. For the minimum PoC, use static shared.
    writeln!(out, "    __shared__ sv_bf<D> x_s;").unwrap();
    writeln!(out, "    __shared__ sv_bf<D> w_s;").unwrap();
    writeln!(out, "    __shared__ sv_bf<D> sq_s;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::load(x_s, g.x, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "    warp::load(w_s, g.w, {{0, 0, 0, 0}});").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::mul(sq_s, x_s, x_s);").unwrap();
    writeln!(out, "    bf16 sum_sq;").unwrap();
    writeln!(out, "    warp::sum(sum_sq, sq_s);").unwrap();
    writeln!(
        out,
        "    float rsqrt_val = rsqrtf(__bfloat162float(sum_sq) / D + g.eps);",
    )
    .unwrap();
    writeln!(out, "    bf16 rsqrt_bf = __float2bfloat16(rsqrt_val);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::mul(x_s, x_s, rsqrt_bf);").unwrap();
    writeln!(out, "    warp::mul(x_s, x_s, w_s);").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::store(g.y, x_s, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // Host launcher — generic over D via an inner helper. Callers pass
    // D explicitly until the launcher layer knows how to dispatch.
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_rmsnorm(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(out, "    const bf16* x, const bf16* w, bf16* y,",).unwrap();
    writeln!(
        out,
        "    uint32_t num_tokens, uint32_t hidden_dim, float eps) {{"
    )
    .unwrap();
    // Llama-3-8B hidden_dim=4096 is the PoC target. A dispatch table
    // over the hidden_dims we need (4096 / 3072 / 2048 / 1024 / 896)
    // lands alongside the remaining regions.
    writeln!(out, "    constexpr int D = 4096;").unwrap();
    writeln!(
        out,
        "    if (hidden_dim != D) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(out, "    using globals_t = rmsnorm_globals<D>;").unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(x), (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(w), (size_t)1, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{y, (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(out, "        eps").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(
        out,
        "    rmsnorm_kernel<D><<<dim3(num_tokens), dim3(32), 0, stream>>>(g);",
    )
    .unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Stub for regions we haven't ported yet. Emits a `// TODO` comment
/// so the generated file still parses but the region is a no-op.
fn write_stub_region(out: &mut String, region: &Region) {
    writeln!(
        out,
        "// ── region: {} (not yet ported to kittens emit) ──",
        region.name,
    )
    .unwrap();
    writeln!(out).unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::template::{RmsNormParams, rmsnorm_region};

    #[test]
    fn empty_mega_produces_header_only() {
        let mega = Megakernel {
            regions: vec![],
            control: vec![],
        };
        let src = emit_kittens(&mega);
        assert!(src.contains("#define KITTENS_HOPPER"));
        assert!(src.contains("#include \"kittens.cuh\""));
        assert!(src.contains("using namespace kittens;"));
    }

    #[test]
    fn rmsnorm_region_emits_kittens_kernel_and_launcher() {
        let r = rmsnorm_region(&RmsNormParams {
            hidden_dim: 4096,
            token_tile: 1,
        });
        let mega = Megakernel {
            regions: vec![r],
            control: vec![],
        };
        let src = emit_kittens(&mega);

        // globals struct with kittens::gl members
        assert!(src.contains("struct rmsnorm_globals"));
        assert!(src.contains("gl<bf16, -1, -1, -1, -1, vec_t>"));

        // kernel with __grid_constant__ globals param
        assert!(src.contains("__global__ __launch_bounds__(32, 1)"));
        assert!(src.contains("void rmsnorm_kernel(const __grid_constant__ rmsnorm_globals<D> g)"),);

        // kittens primitives in the body
        assert!(src.contains("warp::load(x_s, g.x"));
        assert!(src.contains("warp::load(w_s, g.w"));
        assert!(src.contains("warp::mul(sq_s, x_s, x_s)"));
        assert!(src.contains("warp::sum(sum_sq, sq_s)"));
        assert!(src.contains("warp::store(g.y, x_s"));

        // extern "C" launcher present
        assert!(src.contains("extern \"C\" cudaError_t launch_rmsnorm"));
    }
}
