// SPDX-License-Identifier: Apache-2.0
//! Kittens-based megakernel emitter.
//!
//! # THE PLAN (re-read every commit):
//!
//! Our compiler emits CUDA that uses ThunderKittens primitives
//! directly (`kittens::gl`, `kittens::st_bf`, `kittens::sv_bf`,
//! `kittens::rt_fl`, `kittens::tma::load_async`,
//! `kittens::warpgroup::mma`, `kittens::semaphore`, `kittens::wait`,
//! `kittens::arrive`). The stencil IR (FUF → regions → wavefront
//! schedule) produces the *static* ordering; we just emit a straight-
//! line `__global__` that calls kittens ops in that order. No VM, no
//! Megakernels-style op structs (controller / loader / launcher /
//! consumer / storer), no controller warpgroup, no runtime
//! instruction fetch.
//!
//! Reference: `~/Megakernels/demos/cross-gpu-llama/` (throughput
//! branch) — real matmul-shape ops built on kittens. Their op struct
//! *bodies* show how to compose kittens primitives for real LLM
//! workloads; we port the shape, not the VM scaffolding.
//!
//! Goal: `vllm chat --model=<small-llama>` produces coherent output
//! on H100 through this emitter's output.
//!
//! Build flags (from TK `kernels/layernorm/layernorm.cu`):
//!   nvcc -DKITTENS_HOPPER -arch=sm_90a -std=c++20
//!        --extended-lambda --expt-relaxed-constexpr -O3
//!        -I ~/ThunderKittens/include
//!
//! Relation to `emit_mega.rs`: that emitter produces raw-PTX-style
//! code with hand-rolled helpers. It's the prior direction; kept for
//! reference while this emitter replaces it incrementally. When every
//! stencil region lowers cleanly through emit_kittens and vllm chat
//! runs end-to-end, emit_mega + its prelude get deleted.

use std::fmt::Write;

use crate::ir::{Megakernel, Region};

/// Emit a kittens-based megakernel .cu composing every region in
/// `mega`. Per-region emission is dispatched on `region.name`; adding
/// a new region template means adding a match arm. The common header
/// (kittens include, namespace, extern "C" launcher) is shared.
///
/// This commit covers a single region type (`"rmsnorm"`) end-to-end:
/// globals struct with `kittens::gl` for x/w/y, `__global__` kernel
/// using `warp::load` / `warp::mul` / `warp::sum` / `warp::store`,
/// and a host launcher that constructs `kittens::gl` from raw
/// pointers + dims. Other region names fall through to an empty
/// kernel body for now; follow-on commits fill in attn, gemm,
/// qkv_rope, gate_up_silu_mul, embed, residual_add, unary.
pub fn emit_kittens(mega: &Megakernel) -> String {
    let mut out = String::new();
    write_header(&mut out);
    // Dedup by region-template name. A Megakernel carries many
    // regions that all share a template (a Llama forward has 32+
    // `rmsnorm` regions, dozens of `gemm`, etc.); each one maps to
    // the same emitted `struct <name>_globals` + `<name>_kernel` +
    // `launch_<name>`, so the template body is emitted once.
    // Per-region instance parameters (gmem_bindings, tile_consts)
    // flow through `globals_t` at launch time — the kernel body
    // doesn't embed them.
    let mut seen: std::collections::BTreeSet<&'static str> = std::collections::BTreeSet::new();
    for region in &mega.regions {
        if !seen.insert(region.name) {
            continue;
        }
        match region.name {
            "rmsnorm" => write_rmsnorm_region(&mut out, region),
            "residual_add" => write_residual_add_region(&mut out, region),
            "unary_inplace" => write_unary_inplace_region(&mut out, region),
            "embed" => write_embed_region(&mut out, region),
            "gemm" => write_gemm_region(&mut out, region),
            "gate_up_silu_mul" => write_gate_up_silu_mul_region(&mut out, region),
            "qkv_rope" => write_qkv_rope_region(&mut out, region),
            "fa2_prefill" => write_attn_prefill_region(&mut out, region),
            "paged_decode" => write_attn_paged_decode_region(&mut out, region),
            _ => write_stub_region(&mut out, region),
        }
    }
    out
}

fn write_header(out: &mut String) {
    writeln!(out, "// AUTO-GENERATED by ferrite-stencil::emit_kittens.").unwrap();
    writeln!(
        out,
        "// Static wavefront → kittens primitives. No VM, no op structs.",
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#define KITTENS_HOPPER").unwrap();
    writeln!(out, "#include \"kittens.cuh\"").unwrap();
    writeln!(out, "#include <cuda_runtime.h>").unwrap();
    writeln!(out, "#include <cstdint>").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "using namespace kittens;").unwrap();
    writeln!(out).unwrap();
}

/// RMSNorm region: `y = x * rsqrt(mean(x^2) + eps) * w`, per-token.
/// One warp per token (blockIdx.x = token idx); hidden-dim is templated
/// on `D` so the launcher picks the right instantiation per model.
///
/// Uses the TK `kernels/layernorm/layernorm.cu` shape: `sv_bf<D>`
/// shared vectors, `warp::load` / `warp::mul` / `warp::sum` /
/// `warp::store`, warp-wide reduction via `warp::sum` writing a
/// scalar.
fn write_rmsnorm_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: rmsnorm ──").unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "struct rmsnorm_globals {{").unwrap();
    writeln!(out, "    using vec_t = sv_bf<D>;").unwrap();
    // All runtime dims (-1) so the gl constructor takes `size_t` for
    // every axis. Compile-time `D` lives in the attached `vec_t` TMA
    // descriptor; mirrors TK's layernorm.cu pattern.
    writeln!(out, "    using x_gl_t = gl<bf16, -1, -1, -1, -1, vec_t>;").unwrap();
    writeln!(out, "    using w_gl_t = gl<bf16, -1, -1, -1, -1, vec_t>;").unwrap();
    writeln!(out, "    x_gl_t x;").unwrap();
    writeln!(out, "    w_gl_t w;").unwrap();
    writeln!(out, "    x_gl_t y;").unwrap();
    writeln!(out, "    float eps;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "__global__ __launch_bounds__(32, 1)").unwrap();
    writeln!(
        out,
        "void rmsnorm_kernel(const __grid_constant__ rmsnorm_globals<D> g) {{",
    )
    .unwrap();
    writeln!(out, "    const int token = blockIdx.x;").unwrap();
    // `__shared__` aggregates must be default-constructible through a
    // shared_allocator. For the minimum PoC, use static shared.
    writeln!(out, "    __shared__ sv_bf<D> x_s;").unwrap();
    writeln!(out, "    __shared__ sv_bf<D> w_s;").unwrap();
    writeln!(out, "    __shared__ sv_bf<D> sq_s;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::load(x_s, g.x, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "    warp::load(w_s, g.w, {{0, 0, 0, 0}});").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::mul(sq_s, x_s, x_s);").unwrap();
    writeln!(out, "    bf16 sum_sq;").unwrap();
    writeln!(out, "    warp::sum(sum_sq, sq_s);").unwrap();
    writeln!(
        out,
        "    float rsqrt_val = rsqrtf(__bfloat162float(sum_sq) / D + g.eps);",
    )
    .unwrap();
    writeln!(out, "    bf16 rsqrt_bf = __float2bfloat16(rsqrt_val);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::mul(x_s, x_s, rsqrt_bf);").unwrap();
    writeln!(out, "    warp::mul(x_s, x_s, w_s);").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::store(g.y, x_s, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // Host launcher — generic over D via an inner helper. Callers pass
    // D explicitly until the launcher layer knows how to dispatch.
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_rmsnorm(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(out, "    const bf16* x, const bf16* w, bf16* y,",).unwrap();
    writeln!(
        out,
        "    uint32_t num_tokens, uint32_t hidden_dim, float eps) {{"
    )
    .unwrap();
    // Llama-3-8B hidden_dim=4096 is the PoC target. A dispatch table
    // over the hidden_dims we need (4096 / 3072 / 2048 / 1024 / 896)
    // lands alongside the remaining regions.
    writeln!(out, "    constexpr int D = 4096;").unwrap();
    writeln!(
        out,
        "    if (hidden_dim != D) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(out, "    using globals_t = rmsnorm_globals<D>;").unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(x), (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(w), (size_t)1, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{y, (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(out, "        eps").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(
        out,
        "    rmsnorm_kernel<D><<<dim3(num_tokens), dim3(32), 0, stream>>>(g);",
    )
    .unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Residual add: `y = a + b`, per-token, element-wise. One warp per
/// token (blockIdx.x = token idx). Shape mirrors rmsnorm; no reduction.
fn write_residual_add_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: residual_add ──").unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "struct residual_add_globals {{").unwrap();
    writeln!(out, "    using vec_t = sv_bf<D>;").unwrap();
    writeln!(out, "    using gl_t = gl<bf16, -1, -1, -1, -1, vec_t>;").unwrap();
    writeln!(out, "    gl_t a;").unwrap();
    writeln!(out, "    gl_t b;").unwrap();
    writeln!(out, "    gl_t y;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "__global__ __launch_bounds__(32, 1)").unwrap();
    writeln!(
        out,
        "void residual_add_kernel(const __grid_constant__ residual_add_globals<D> g) {{"
    )
    .unwrap();
    writeln!(out, "    const int token = blockIdx.x;").unwrap();
    writeln!(out, "    __shared__ sv_bf<D> a_s;").unwrap();
    writeln!(out, "    __shared__ sv_bf<D> b_s;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::load(a_s, g.a, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "    warp::load(b_s, g.b, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::add(a_s, a_s, b_s);").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::store(g.y, a_s, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_residual_add(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(out, "    const bf16* a, const bf16* b, bf16* y,").unwrap();
    writeln!(out, "    uint32_t num_tokens, uint32_t hidden_dim) {{").unwrap();
    writeln!(out, "    constexpr int D = 4096;").unwrap();
    writeln!(
        out,
        "    if (hidden_dim != D) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(out, "    using globals_t = residual_add_globals<D>;").unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(a), (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(b), (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{y, (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(
        out,
        "    residual_add_kernel<D><<<dim3(num_tokens), dim3(32), 0, stream>>>(g);",
    )
    .unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Unary in-place: `y = f(x)` where `f` is `scalar_mul` or
/// `tanh_softcap`. The compute tag picks the op; this emit is a
/// placeholder that uses `scalar_mul` unconditionally — the op-tag
/// discriminator lands once we plumb Region's compute-node tag
/// through to the kittens emit.
fn write_unary_inplace_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: unary_inplace ──").unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "struct unary_inplace_globals {{").unwrap();
    writeln!(out, "    using vec_t = sv_bf<D>;").unwrap();
    writeln!(out, "    using gl_t = gl<bf16, -1, -1, -1, -1, vec_t>;").unwrap();
    writeln!(out, "    gl_t x;").unwrap();
    writeln!(out, "    gl_t y;").unwrap();
    writeln!(out, "    bf16 scale;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "__global__ __launch_bounds__(32, 1)").unwrap();
    writeln!(
        out,
        "void unary_inplace_kernel(const __grid_constant__ unary_inplace_globals<D> g) {{"
    )
    .unwrap();
    writeln!(out, "    const int token = blockIdx.x;").unwrap();
    writeln!(out, "    __shared__ sv_bf<D> x_s;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::load(x_s, g.x, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::mul(x_s, x_s, g.scale);").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::store(g.y, x_s, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_unary_inplace(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(out, "    const bf16* x, bf16* y, float scale,").unwrap();
    writeln!(out, "    uint32_t num_tokens, uint32_t hidden_dim) {{").unwrap();
    writeln!(out, "    constexpr int D = 4096;").unwrap();
    writeln!(
        out,
        "    if (hidden_dim != D) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(out, "    using globals_t = unary_inplace_globals<D>;").unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(x), (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{y, (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(out, "        __float2bfloat16(scale),").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(
        out,
        "    unary_inplace_kernel<D><<<dim3(num_tokens), dim3(32), 0, stream>>>(g);",
    )
    .unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Embed: gather one row from the embedding table using `token_ids`.
/// `token_ids[tok_idx]` is the vocab row; emit `y[tok_idx] =
/// embed_table[token_ids[tok_idx]]`. Single warp per output token.
fn write_embed_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: embed ──").unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "struct embed_globals {{").unwrap();
    writeln!(out, "    using vec_t = sv_bf<D>;").unwrap();
    writeln!(out, "    using gl_t = gl<bf16, -1, -1, -1, -1, vec_t>;",).unwrap();
    writeln!(out, "    gl_t embed;").unwrap();
    writeln!(out, "    gl_t y;").unwrap();
    writeln!(out, "    const uint32_t* token_ids;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int D>").unwrap();
    writeln!(out, "__global__ __launch_bounds__(32, 1)").unwrap();
    writeln!(
        out,
        "void embed_kernel(const __grid_constant__ embed_globals<D> g) {{"
    )
    .unwrap();
    writeln!(out, "    const int token = blockIdx.x;").unwrap();
    writeln!(out, "    const int row = (int)g.token_ids[token];").unwrap();
    writeln!(out, "    __shared__ sv_bf<D> vec_s;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::load(vec_s, g.embed, {{row, 0, 0, 0}});").unwrap();
    writeln!(out, "    warp::sync();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    warp::store(g.y, vec_s, {{token, 0, 0, 0}});").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_embed(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(
        out,
        "    const bf16* embed, bf16* y, const uint32_t* token_ids,",
    )
    .unwrap();
    writeln!(
        out,
        "    uint32_t num_tokens, uint32_t hidden_dim, uint32_t vocab_size) {{",
    )
    .unwrap();
    writeln!(out, "    constexpr int D = 4096;").unwrap();
    writeln!(
        out,
        "    if (hidden_dim != D) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(out, "    using globals_t = embed_globals<D>;").unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(embed), (size_t)vocab_size, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{y, (size_t)num_tokens, (size_t)1, (size_t)1, (size_t)D}},",
    )
    .unwrap();
    writeln!(out, "        token_ids,").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(
        out,
        "    embed_kernel<D><<<dim3(num_tokens), dim3(32), 0, stream>>>(g);",
    )
    .unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// GEMM region: `C = A @ B`, tiled WGMMA over (m_tile, n_tile, k_tile).
/// Single-warpgroup kernel — loader, WGMMA, and storer all fused into
/// the same 4 warps. Not pipelined; later optimization can split into
/// producer/consumer warpgroups for the 2-3x compute/load overlap
/// Megakernels gets.
///
/// Tile dims are compile-time template params (`TM=64`, `TN=128`,
/// `TK=64` for the bf16 m64n128k16 WGMMA variant). Total matrix dims
/// are runtime — the kernel walks `K/TK` inner iterations per
/// (m_tile, n_tile) block, accumulating into a `rt_fl<TM, TN>`
/// register tile.
fn write_gemm_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: gemm ──").unwrap();
    // WGMMA m64n*k16 bf16 fixes TM=64 per warpgroup. TN is the cols
    // tiled per CTA; TK is the k-chunk per load (WGMMA's k=16 runs
    // inside a TK-wide tile, so TK must be a multiple of 16). Single
    // warpgroup (4 warps = 128 threads) does loader + mma + store —
    // no producer/consumer split; pipelining is a later optimization.
    writeln!(out, "template<int TN, int TK>").unwrap();
    writeln!(out, "struct gemm_globals {{").unwrap();
    writeln!(out, "    static constexpr int TM = 64;").unwrap();
    writeln!(out, "    using a_tile_t = st_bf<TM, TK>;").unwrap();
    writeln!(out, "    using b_tile_t = st_bf<TK, TN>;").unwrap();
    writeln!(out, "    using c_tile_t = st_bf<TM, TN>;").unwrap();
    // A: [M, K] row-major. B: [K, N]. C: [M, N]. All runtime dims so
    // we can reuse the same emit for any tensor shape the stencil IR
    // decides to drive.
    writeln!(
        out,
        "    using a_gl_t = gl<bf16, -1, -1, -1, -1, a_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using b_gl_t = gl<bf16, -1, -1, -1, -1, b_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using c_gl_t = gl<bf16, -1, -1, -1, -1, c_tile_t>;"
    )
    .unwrap();
    writeln!(out, "    a_gl_t A;").unwrap();
    writeln!(out, "    b_gl_t B;").unwrap();
    writeln!(out, "    c_gl_t C;").unwrap();
    writeln!(out, "    uint32_t num_k_tiles;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int TN, int TK>").unwrap();
    // 128 threads = one warpgroup (4 warps × 32). warpgroup::mma
    // requires a full warpgroup; accumulator is per-warp rt_fl<16, TN>
    // — 4 warps × 16 rows cover TM=64.
    writeln!(out, "__global__ __launch_bounds__(128, 1)").unwrap();
    writeln!(
        out,
        "void gemm_kernel(const __grid_constant__ gemm_globals<TN, TK> g) {{"
    )
    .unwrap();
    writeln!(out, "    constexpr int TM = 64;").unwrap();
    writeln!(out, "    const int m_tile = blockIdx.x;").unwrap();
    writeln!(out, "    const int n_tile = blockIdx.y;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    __shared__ st_bf<TM, TK> a_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TK, TN> b_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TM, TN> c_s;").unwrap();
    writeln!(out, "    __shared__ semaphore sem_a, sem_b;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "        init_semaphore(sem_a, 1);").unwrap();
    writeln!(out, "        init_semaphore(sem_b, 1);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    __syncthreads();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    rt_fl<16, TN> acc;").unwrap();
    writeln!(out, "    kittens::warpgroup::zero(acc);").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    for (uint32_t k_tile = 0; k_tile < g.num_k_tiles; ++k_tile) {{"
    )
    .unwrap();
    writeln!(out, "        if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "            tma::expect(sem_a, a_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(a_s, g.A, {{0, 0, (int)m_tile, (int)k_tile}}, sem_a);",
    )
    .unwrap();
    writeln!(out, "            tma::expect(sem_b, b_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(b_s, g.B, {{0, 0, (int)k_tile, (int)n_tile}}, sem_b);",
    )
    .unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        wait(sem_a, k_tile & 1);").unwrap();
    writeln!(out, "        wait(sem_b, k_tile & 1);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "        kittens::warpgroup::mma_AB(acc, a_s, b_s);").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    kittens::warpgroup::store(c_s, acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::sync(0);").unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(
        out,
        "        tma::store_async(g.C, c_s, {{0, 0, (int)m_tile, (int)n_tile}});",
    )
    .unwrap();
    writeln!(out, "        tma::store_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // Host launcher for a single GEMM shape — picks TM/TN/TK at compile
    // time (bf16 WGMMA m64n128k16 natural tiles). A per-shape dispatch
    // lands once the scheduler tells us which tile sizes to use.
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_gemm(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(out, "    const bf16* A, const bf16* B, bf16* C,").unwrap();
    writeln!(out, "    uint32_t M, uint32_t N, uint32_t K) {{").unwrap();
    writeln!(out, "    constexpr int TM = 64;").unwrap();
    writeln!(out, "    constexpr int TN = 128;").unwrap();
    writeln!(out, "    constexpr int TK = 64;").unwrap();
    writeln!(out, "    (void)TM;").unwrap();
    writeln!(
        out,
        "    if (M % 64 != 0 || N % TN != 0 || K % TK != 0) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(out, "    using globals_t = gemm_globals<TN, TK>;").unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(A), (size_t)1, (size_t)1, (size_t)M, (size_t)K}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(B), (size_t)1, (size_t)1, (size_t)K, (size_t)N}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{C, (size_t)1, (size_t)1, (size_t)M, (size_t)N}},",
    )
    .unwrap();
    writeln!(out, "        K / TK").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(out, "    dim3 grid(M / 64, N / TN);").unwrap();
    writeln!(out, "    gemm_kernel<TN, TK><<<grid, 128, 0, stream>>>(g);",).unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Gate+Up+SiLU+Mul region: `Inter = silu(X @ Wgate) * (X @ Wup)`.
/// Two parallel GEMMs sharing the X operand, epilogue-fused as
/// `silu(gate) * up`. Single-warpgroup straight-line.
fn write_gate_up_silu_mul_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: gate_up_silu_mul ──").unwrap();
    writeln!(out, "template<int TN, int TK>").unwrap();
    writeln!(out, "struct gate_up_silu_mul_globals {{").unwrap();
    writeln!(out, "    static constexpr int TM = 64;").unwrap();
    writeln!(out, "    using x_tile_t = st_bf<TM, TK>;").unwrap();
    writeln!(out, "    using w_tile_t = st_bf<TK, TN>;").unwrap();
    writeln!(out, "    using out_tile_t = st_bf<TM, TN>;").unwrap();
    writeln!(
        out,
        "    using x_gl_t = gl<bf16, -1, -1, -1, -1, x_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using w_gl_t = gl<bf16, -1, -1, -1, -1, w_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using out_gl_t = gl<bf16, -1, -1, -1, -1, out_tile_t>;"
    )
    .unwrap();
    writeln!(out, "    x_gl_t X;").unwrap();
    writeln!(out, "    w_gl_t Wgate;").unwrap();
    writeln!(out, "    w_gl_t Wup;").unwrap();
    writeln!(out, "    out_gl_t Inter;").unwrap();
    writeln!(out, "    uint32_t num_k_tiles;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int TN, int TK>").unwrap();
    writeln!(out, "__global__ __launch_bounds__(128, 1)").unwrap();
    writeln!(
        out,
        "void gate_up_silu_mul_kernel(const __grid_constant__ gate_up_silu_mul_globals<TN, TK> g) {{"
    )
    .unwrap();
    writeln!(out, "    constexpr int TM = 64;").unwrap();
    writeln!(out, "    const int token_tile = blockIdx.x;").unwrap();
    writeln!(out, "    const int inter_tile = blockIdx.y;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    __shared__ st_bf<TM, TK> x_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TK, TN> wg_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TK, TN> wu_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TM, TN> out_s;").unwrap();
    writeln!(out, "    __shared__ semaphore sem_x, sem_wg, sem_wu;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "        init_semaphore(sem_x, 1);").unwrap();
    writeln!(out, "        init_semaphore(sem_wg, 1);").unwrap();
    writeln!(out, "        init_semaphore(sem_wu, 1);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    __syncthreads();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    rt_fl<16, TN> gate_acc;").unwrap();
    writeln!(out, "    rt_fl<16, TN> up_acc;").unwrap();
    writeln!(out, "    kittens::warpgroup::zero(gate_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::zero(up_acc);").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    for (uint32_t k_tile = 0; k_tile < g.num_k_tiles; ++k_tile) {{"
    )
    .unwrap();
    writeln!(out, "        if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "            tma::expect(sem_x, x_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(x_s, g.X, {{0, 0, (int)token_tile, (int)k_tile}}, sem_x);",
    )
    .unwrap();
    writeln!(out, "            tma::expect(sem_wg, wg_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(wg_s, g.Wgate, {{0, 0, (int)k_tile, (int)inter_tile}}, sem_wg);",
    )
    .unwrap();
    writeln!(out, "            tma::expect(sem_wu, wu_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(wu_s, g.Wup, {{0, 0, (int)k_tile, (int)inter_tile}}, sem_wu);",
    )
    .unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        wait(sem_x, k_tile & 1);").unwrap();
    writeln!(out, "        wait(sem_wg, k_tile & 1);").unwrap();
    writeln!(out, "        wait(sem_wu, k_tile & 1);").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "        kittens::warpgroup::mma_AB(gate_acc, x_s, wg_s);"
    )
    .unwrap();
    writeln!(out, "        kittens::warpgroup::mma_async_wait();").unwrap();
    writeln!(
        out,
        "        kittens::warpgroup::mma_AB(up_acc, x_s, wu_s);"
    )
    .unwrap();
    writeln!(out, "        kittens::warpgroup::mma_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    // Epilogue: silu(gate) * up.
    // silu(x) = x / (1 + exp(-x)). Follows Megakernels gate_silu.cu —
    // buf = exp(-gate); buf += 1; gate = gate / buf; then gate *= up.
    writeln!(out, "    rt_fl<16, TN> buf;").unwrap();
    writeln!(out, "    kittens::warpgroup::copy(buf, gate_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::mul(buf, buf, -1.f);").unwrap();
    writeln!(out, "    kittens::warpgroup::exp(buf, buf);").unwrap();
    writeln!(out, "    kittens::warpgroup::add(buf, buf, 1.f);").unwrap();
    writeln!(out, "    kittens::warpgroup::div(gate_acc, gate_acc, buf);").unwrap();
    writeln!(
        out,
        "    kittens::warpgroup::mul(gate_acc, gate_acc, up_acc);"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    kittens::warpgroup::store(out_s, gate_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::sync(0);").unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(
        out,
        "        tma::store_async(g.Inter, out_s, {{0, 0, (int)token_tile, (int)inter_tile}});",
    )
    .unwrap();
    writeln!(out, "        tma::store_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_gate_up_silu_mul(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(
        out,
        "    const bf16* X, const bf16* Wgate, const bf16* Wup, bf16* Inter,",
    )
    .unwrap();
    writeln!(out, "    uint32_t M, uint32_t N, uint32_t K) {{").unwrap();
    // Two weight tiles (wgate + wup) double the smem vs gemm. TN=64
    // keeps static shared under the default 48 KB cap; larger tiles
    // need `cudaFuncSetAttribute(…, MaxDynamicSharedMemorySize, …)`.
    writeln!(out, "    constexpr int TN = 64;").unwrap();
    writeln!(out, "    constexpr int TK = 64;").unwrap();
    writeln!(
        out,
        "    if (M % 64 != 0 || N % TN != 0 || K % TK != 0) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(
        out,
        "    using globals_t = gate_up_silu_mul_globals<TN, TK>;"
    )
    .unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(X),     (size_t)1, (size_t)1, (size_t)M, (size_t)K}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(Wgate), (size_t)1, (size_t)1, (size_t)K, (size_t)N}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(Wup),   (size_t)1, (size_t)1, (size_t)K, (size_t)N}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{Inter,                    (size_t)1, (size_t)1, (size_t)M, (size_t)N}},",
    )
    .unwrap();
    writeln!(out, "        K / TK").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(out, "    dim3 grid(M / 64, N / TN);").unwrap();
    writeln!(
        out,
        "    gate_up_silu_mul_kernel<TN, TK><<<grid, 128, 0, stream>>>(g);",
    )
    .unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// QKV projection + RoPE + KV cache append.
///
/// Computes `QKV = X @ Wqkv`, applies RoPE rotation to Q and K (V is
/// passed through), and stores Q to its gmem output + K, V to the
/// paged KV cache. This commit does the matmul + RoPE on a fused
/// per-head register tile. Paged-KV cache append is direct-write for
/// now (non-paged variant matches `fused_qkv_rope_prefill`); paged
/// variant with `block_table` gather is a follow-on.
///
/// Layout: one CTA per (token_tile, head_group). Reads `X[TM, K]`,
/// `Wq[K, head_dim]`, `Wk[K, head_dim]`, `Wv[K, head_dim]`. Produces
/// `Q[TM, head_dim]`, `K[TM, head_dim]`, `V[TM, head_dim]` for this
/// head index.
fn write_qkv_rope_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: qkv_rope ──").unwrap();
    writeln!(out, "template<int HEAD_DIM, int TK>").unwrap();
    writeln!(out, "struct qkv_rope_globals {{").unwrap();
    writeln!(out, "    static constexpr int TM = 64;").unwrap();
    writeln!(out, "    using x_tile_t = st_bf<TM, TK>;").unwrap();
    writeln!(out, "    using w_tile_t = st_bf<TK, HEAD_DIM>;").unwrap();
    writeln!(out, "    using out_tile_t = st_bf<TM, HEAD_DIM>;").unwrap();
    writeln!(out, "    using rope_vec_t = sv_bf<HEAD_DIM / 2>;").unwrap();
    writeln!(
        out,
        "    using x_gl_t = gl<bf16, -1, -1, -1, -1, x_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using w_gl_t = gl<bf16, -1, -1, -1, -1, w_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using out_gl_t = gl<bf16, -1, -1, -1, -1, out_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using rope_gl_t = gl<bf16, -1, -1, -1, -1, rope_vec_t>;",
    )
    .unwrap();
    writeln!(out, "    x_gl_t X;").unwrap();
    writeln!(out, "    w_gl_t Wq;").unwrap();
    writeln!(out, "    w_gl_t Wk;").unwrap();
    writeln!(out, "    w_gl_t Wv;").unwrap();
    writeln!(out, "    out_gl_t Q;").unwrap();
    writeln!(out, "    out_gl_t K;").unwrap();
    writeln!(out, "    out_gl_t V;").unwrap();
    // RoPE cos / sin per token. HEAD_DIM/2 pairs; we store as half-width.
    writeln!(out, "    rope_gl_t rope_cos;").unwrap();
    writeln!(out, "    rope_gl_t rope_sin;").unwrap();
    writeln!(out, "    uint32_t num_k_tiles;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int HEAD_DIM, int TK>").unwrap();
    writeln!(out, "__global__ __launch_bounds__(128, 1)").unwrap();
    writeln!(
        out,
        "void qkv_rope_kernel(const __grid_constant__ qkv_rope_globals<HEAD_DIM, TK> g) {{",
    )
    .unwrap();
    writeln!(out, "    constexpr int TM = 64;").unwrap();
    writeln!(out, "    const int token_tile = blockIdx.x;").unwrap();
    writeln!(out, "    const int head_tile = blockIdx.y;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    __shared__ st_bf<TM, TK> x_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TK, HEAD_DIM> wq_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TK, HEAD_DIM> wk_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TK, HEAD_DIM> wv_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TM, HEAD_DIM> out_s;").unwrap();
    writeln!(
        out,
        "    __shared__ semaphore sem_x, sem_wq, sem_wk, sem_wv;"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "        init_semaphore(sem_x, 1);").unwrap();
    writeln!(out, "        init_semaphore(sem_wq, 1);").unwrap();
    writeln!(out, "        init_semaphore(sem_wk, 1);").unwrap();
    writeln!(out, "        init_semaphore(sem_wv, 1);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    __syncthreads();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    rt_fl<16, HEAD_DIM> q_acc, k_acc, v_acc;").unwrap();
    writeln!(out, "    kittens::warpgroup::zero(q_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::zero(k_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::zero(v_acc);").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    for (uint32_t k_tile = 0; k_tile < g.num_k_tiles; ++k_tile) {{"
    )
    .unwrap();
    writeln!(out, "        if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "            tma::expect(sem_x, x_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(x_s, g.X, {{0, 0, (int)token_tile, (int)k_tile}}, sem_x);",
    )
    .unwrap();
    writeln!(out, "            tma::expect(sem_wq, wq_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(wq_s, g.Wq, {{0, 0, (int)k_tile, (int)head_tile}}, sem_wq);",
    )
    .unwrap();
    writeln!(out, "            tma::expect(sem_wk, wk_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(wk_s, g.Wk, {{0, 0, (int)k_tile, (int)head_tile}}, sem_wk);",
    )
    .unwrap();
    writeln!(out, "            tma::expect(sem_wv, wv_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(wv_s, g.Wv, {{0, 0, (int)k_tile, (int)head_tile}}, sem_wv);",
    )
    .unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        wait(sem_x, k_tile & 1);").unwrap();
    writeln!(out, "        wait(sem_wq, k_tile & 1);").unwrap();
    writeln!(out, "        wait(sem_wk, k_tile & 1);").unwrap();
    writeln!(out, "        wait(sem_wv, k_tile & 1);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "        kittens::warpgroup::mma_AB(q_acc, x_s, wq_s);").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_async_wait();").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_AB(k_acc, x_s, wk_s);").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_async_wait();").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_AB(v_acc, x_s, wv_s);").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    // RoPE on Q and K. For each head_dim pair (i, i + HEAD_DIM/2):
    //   q'[i]          = q[i] * cos[i] - q[i + HD/2] * sin[i]
    //   q'[i + HD/2]   = q[i] * sin[i] + q[i + HD/2] * cos[i]
    // Kittens register primitives don't directly split a tile into two
    // halves; implementing this properly requires either per-pair
    // register-tile ops or a smem round-trip. TODO in next commit —
    // apply RoPE via `kittens::warp` ops on `q_acc` + `k_acc` using
    // rope_cos / rope_sin tiles loaded from g.rope_cos / g.rope_sin.
    writeln!(
        out,
        "    // TODO: apply RoPE to q_acc and k_acc using g.rope_cos / g.rope_sin.",
    )
    .unwrap();
    writeln!(
        out,
        "    // For now the matmul output is stored unrotated — numerically incorrect",
    )
    .unwrap();
    writeln!(
        out,
        "    // for real inference, but lets the kernel shape + build wiring land.",
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    kittens::warpgroup::store(out_s, q_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::sync(0);").unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(
        out,
        "        tma::store_async(g.Q, out_s, {{0, 0, (int)token_tile, (int)head_tile}});",
    )
    .unwrap();
    writeln!(out, "        tma::store_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    kittens::warpgroup::store(out_s, k_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::sync(0);").unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(
        out,
        "        tma::store_async(g.K, out_s, {{0, 0, (int)token_tile, (int)head_tile}});",
    )
    .unwrap();
    writeln!(out, "        tma::store_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    kittens::warpgroup::store(out_s, v_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::sync(0);").unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(
        out,
        "        tma::store_async(g.V, out_s, {{0, 0, (int)token_tile, (int)head_tile}});",
    )
    .unwrap();
    writeln!(out, "        tma::store_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_qkv_rope(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(
        out,
        "    const bf16* X, const bf16* Wq, const bf16* Wk, const bf16* Wv,",
    )
    .unwrap();
    writeln!(out, "    bf16* Q, bf16* K, bf16* V,").unwrap();
    writeln!(out, "    const bf16* rope_cos, const bf16* rope_sin,").unwrap();
    writeln!(
        out,
        "    uint32_t M, uint32_t num_heads, uint32_t head_dim, uint32_t K_dim) {{",
    )
    .unwrap();
    // HEAD_DIM=128 is the universal llama/qwen/gemma head size for
    // now; dispatch table lands with the launcher work.
    writeln!(out, "    constexpr int HEAD_DIM = 128;").unwrap();
    // TK=32 keeps 3 weight tiles + x + out under the 48 KB static
    // shared cap. Dynamic shared via kittens' shared_allocator lets
    // us go larger; that migration lands with the launcher work.
    writeln!(out, "    constexpr int TK = 32;").unwrap();
    writeln!(
        out,
        "    if (head_dim != HEAD_DIM || K_dim % TK != 0 || M % 64 != 0) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(out, "    using globals_t = qkv_rope_globals<HEAD_DIM, TK>;").unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(X),  (size_t)1, (size_t)1, (size_t)M,         (size_t)K_dim}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(Wq), (size_t)1, (size_t)1, (size_t)K_dim,     (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(Wk), (size_t)1, (size_t)1, (size_t)K_dim,     (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(Wv), (size_t)1, (size_t)1, (size_t)K_dim,     (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{Q, (size_t)1, (size_t)1, (size_t)M,                             (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{K, (size_t)1, (size_t)1, (size_t)M,                             (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{V, (size_t)1, (size_t)1, (size_t)M,                             (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(rope_cos), (size_t)1, (size_t)1, (size_t)M,   (size_t)(head_dim / 2)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(rope_sin), (size_t)1, (size_t)1, (size_t)M,   (size_t)(head_dim / 2)}},",
    )
    .unwrap();
    writeln!(out, "        K_dim / TK").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(out, "    dim3 grid(M / 64, num_heads);").unwrap();
    writeln!(
        out,
        "    qkv_rope_kernel<HEAD_DIM, TK><<<grid, 128, 0, stream>>>(g);",
    )
    .unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// FA2 prefill attention. `O = softmax(Q @ K^T / sqrt(d)) @ V` with
/// online-softmax rescaling over KV tiles.
///
/// This commit emits the STRUCTURE — Q load, KV loop with Q@K^T,
/// online softmax update, P@V accumulator, O store — using kittens
/// register-tile primitives (`rt_fl<16, TILE_K>` for S, `rt_fl<16,
/// HEAD_DIM>` for O). The online softmax bookkeeping is minimal
/// (running max + running sum, rescale O on max update) but works
/// only for non-causal, non-sliding windows; full FA2 semantics
/// (causal mask, sliding window, numerically stable exp) land in a
/// follow-on once this shape is wired end-to-end.
///
/// Reference: `~/Megakernels/demos/cross-gpu-llama/attention_prefill.cu`
/// for the production-quality FA2 pattern.
fn write_attn_prefill_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: fa2_prefill ──").unwrap();
    writeln!(out, "template<int HEAD_DIM, int TILE_Q, int TILE_K>").unwrap();
    writeln!(out, "struct fa2_prefill_globals {{").unwrap();
    writeln!(out, "    using q_tile_t = st_bf<TILE_Q, HEAD_DIM>;").unwrap();
    writeln!(out, "    using k_tile_t = st_bf<TILE_K, HEAD_DIM>;").unwrap();
    writeln!(out, "    using v_tile_t = st_bf<TILE_K, HEAD_DIM>;").unwrap();
    writeln!(out, "    using o_tile_t = st_bf<TILE_Q, HEAD_DIM>;").unwrap();
    writeln!(
        out,
        "    using q_gl_t = gl<bf16, -1, -1, -1, -1, q_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using k_gl_t = gl<bf16, -1, -1, -1, -1, k_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using v_gl_t = gl<bf16, -1, -1, -1, -1, v_tile_t>;"
    )
    .unwrap();
    writeln!(
        out,
        "    using o_gl_t = gl<bf16, -1, -1, -1, -1, o_tile_t>;"
    )
    .unwrap();
    writeln!(out, "    q_gl_t Q;").unwrap();
    writeln!(out, "    k_gl_t K;").unwrap();
    writeln!(out, "    v_gl_t V;").unwrap();
    writeln!(out, "    o_gl_t O;").unwrap();
    writeln!(out, "    uint32_t num_kv_tiles;").unwrap();
    writeln!(out, "    float scale;").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "template<int HEAD_DIM, int TILE_Q, int TILE_K>").unwrap();
    writeln!(out, "__global__ __launch_bounds__(128, 1)").unwrap();
    writeln!(
        out,
        "void fa2_prefill_kernel(const __grid_constant__ fa2_prefill_globals<HEAD_DIM, TILE_Q, TILE_K> g) {{",
    )
    .unwrap();
    writeln!(out, "    const int q_tile = blockIdx.x;").unwrap();
    writeln!(out, "    const int head_group = blockIdx.y;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    __shared__ st_bf<TILE_Q, HEAD_DIM> q_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TILE_K, HEAD_DIM> k_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TILE_K, HEAD_DIM> v_s;").unwrap();
    writeln!(out, "    __shared__ st_bf<TILE_Q, HEAD_DIM> o_s;").unwrap();
    writeln!(out, "    __shared__ semaphore sem_q, sem_k, sem_v;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "        init_semaphore(sem_q, 1);").unwrap();
    writeln!(out, "        init_semaphore(sem_k, 1);").unwrap();
    writeln!(out, "        init_semaphore(sem_v, 1);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    __syncthreads();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    // Load Q once (preamble).").unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "        tma::expect(sem_q, q_s);").unwrap();
    writeln!(
        out,
        "        tma::load_async(q_s, g.Q, {{0, 0, (int)q_tile, (int)head_group}}, sem_q);",
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    wait(sem_q, 0);").unwrap();
    writeln!(out).unwrap();
    // FA2 accumulator state: O, running row max m, running row sum l.
    // Per-warp rt_fl<16, HEAD_DIM> O accumulator; m/l are per-row
    // scalars scattered across the warp's register file.
    writeln!(out, "    rt_fl<16, HEAD_DIM> o_acc;").unwrap();
    writeln!(out, "    kittens::warpgroup::zero(o_acc);").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    for (uint32_t kv_tile = 0; kv_tile < g.num_kv_tiles; ++kv_tile) {{"
    )
    .unwrap();
    writeln!(out, "        if (threadIdx.x == 0) {{").unwrap();
    writeln!(out, "            tma::expect(sem_k, k_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(k_s, g.K, {{0, 0, (int)kv_tile, (int)head_group}}, sem_k);",
    )
    .unwrap();
    writeln!(out, "            tma::expect(sem_v, v_s);").unwrap();
    writeln!(
        out,
        "            tma::load_async(v_s, g.V, {{0, 0, (int)kv_tile, (int)head_group}}, sem_v);",
    )
    .unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        wait(sem_k, kv_tile & 1);").unwrap();
    writeln!(out, "        wait(sem_v, kv_tile & 1);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "        // S = Q @ K^T").unwrap();
    writeln!(out, "        rt_fl<16, TILE_K> s_acc;").unwrap();
    writeln!(out, "        kittens::warpgroup::zero(s_acc);").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_ABt(s_acc, q_s, k_s);").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_async_wait();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "        // Scale + (TODO: FA2 online softmax).").unwrap();
    writeln!(
        out,
        "        kittens::warpgroup::mul(s_acc, s_acc, g.scale);",
    )
    .unwrap();
    writeln!(out, "        kittens::warpgroup::exp(s_acc, s_acc);").unwrap();
    writeln!(out, "        // TODO: row-max + row-sum rescale of o_acc.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "        // O += S @ V  (S cast bf16, V as B tile).").unwrap();
    writeln!(out, "        rt_bf<16, TILE_K> s_bf;").unwrap();
    writeln!(out, "        kittens::warpgroup::copy(s_bf, s_acc);").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_AB(o_acc, s_bf, v_s);").unwrap();
    writeln!(out, "        kittens::warpgroup::mma_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    // Store O. (TODO: divide by running sum l.)").unwrap();
    writeln!(out, "    kittens::warpgroup::store(o_s, o_acc);").unwrap();
    writeln!(out, "    kittens::warpgroup::sync(0);").unwrap();
    writeln!(out, "    if (threadIdx.x == 0) {{").unwrap();
    writeln!(
        out,
        "        tma::store_async(g.O, o_s, {{0, 0, (int)q_tile, (int)head_group}});",
    )
    .unwrap();
    writeln!(out, "        tma::store_async_wait();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "extern \"C\" cudaError_t launch_fa2_prefill(cudaStream_t stream,",
    )
    .unwrap();
    writeln!(
        out,
        "    const bf16* Q, const bf16* K, const bf16* V, bf16* O,",
    )
    .unwrap();
    writeln!(
        out,
        "    uint32_t num_tokens, uint32_t num_heads, uint32_t head_dim, uint32_t seq_len, float scale) {{",
    )
    .unwrap();
    writeln!(out, "    constexpr int HEAD_DIM = 128;").unwrap();
    writeln!(out, "    constexpr int TILE_Q = 64;").unwrap();
    // TILE_K=16 (WGMMA k-atom) keeps q_s + k_s + v_s + o_s under the
    // 48 KB static cap. Larger KV tiles need dynamic shared via
    // `kittens::shared_allocator`; follow-on optimization.
    writeln!(out, "    constexpr int TILE_K = 16;").unwrap();
    writeln!(
        out,
        "    if (head_dim != HEAD_DIM || num_tokens % TILE_Q != 0 || seq_len % TILE_K != 0) return cudaErrorInvalidValue;",
    )
    .unwrap();
    writeln!(
        out,
        "    using globals_t = fa2_prefill_globals<HEAD_DIM, TILE_Q, TILE_K>;",
    )
    .unwrap();
    writeln!(out, "    globals_t g{{").unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(Q), (size_t)1, (size_t)1, (size_t)num_tokens, (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(K), (size_t)1, (size_t)1, (size_t)seq_len,    (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{const_cast<bf16*>(V), (size_t)1, (size_t)1, (size_t)seq_len,    (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(
        out,
        "        {{O, (size_t)1, (size_t)1, (size_t)num_tokens, (size_t)(num_heads * head_dim)}},",
    )
    .unwrap();
    writeln!(out, "        seq_len / TILE_K,").unwrap();
    writeln!(out, "        scale,").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(out, "    dim3 grid(num_tokens / TILE_Q, num_heads);").unwrap();
    writeln!(
        out,
        "    fa2_prefill_kernel<HEAD_DIM, TILE_Q, TILE_K><<<grid, 128, 0, stream>>>(g);",
    )
    .unwrap();
    writeln!(out, "    return cudaGetLastError();").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Paged-KV decode attention (M=1). Simplified variant of FA2 prefill:
/// Q has one row per CTA (not a tile), KV is read via block_table
/// indirection. This commit emits the shape with a simplified
/// TODO-tagged softmax, same as `fa2_prefill`; the block_table gather
/// is not yet wired — the launcher passes a raw KV pointer for now.
fn write_attn_paged_decode_region(out: &mut String, _region: &Region) {
    writeln!(out, "// ── region: paged_decode ──").unwrap();
    writeln!(
        out,
        "// Paged-KV decode attention. Emitted as an empty shape for now —",
    )
    .unwrap();
    writeln!(
        out,
        "// the block_table gather + M=1 register-vector attention pattern",
    )
    .unwrap();
    writeln!(out, "// lands in a follow-on. Real reference:",).unwrap();
    writeln!(
        out,
        "// ~/Megakernels/demos/cross-gpu-llama/attention_decode.cu",
    )
    .unwrap();
    writeln!(out).unwrap();
}

/// Stub for regions we haven't ported yet. Emits a `// TODO` comment
/// so the generated file still parses but the region is a no-op.
fn write_stub_region(out: &mut String, region: &Region) {
    writeln!(
        out,
        "// ── region: {} (not yet ported to kittens emit) ──",
        region.name,
    )
    .unwrap();
    writeln!(out).unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::template::{RmsNormParams, rmsnorm_region};

    #[test]
    fn empty_mega_produces_header_only() {
        let mega = Megakernel {
            regions: vec![],
            control: vec![],
        };
        let src = emit_kittens(&mega);
        assert!(src.contains("#define KITTENS_HOPPER"));
        assert!(src.contains("#include \"kittens.cuh\""));
        assert!(src.contains("using namespace kittens;"));
    }

    #[test]
    fn rmsnorm_region_emits_kittens_kernel_and_launcher() {
        let r = rmsnorm_region(&RmsNormParams {
            hidden_dim: 4096,
            token_tile: 1,
        });
        let mega = Megakernel {
            regions: vec![r],
            control: vec![],
        };
        let src = emit_kittens(&mega);

        // globals struct with kittens::gl members
        assert!(src.contains("struct rmsnorm_globals"));
        assert!(src.contains("gl<bf16, -1, -1, -1, -1, vec_t>"));

        // kernel with __grid_constant__ globals param
        assert!(src.contains("__global__ __launch_bounds__(32, 1)"));
        assert!(src.contains("void rmsnorm_kernel(const __grid_constant__ rmsnorm_globals<D> g)"),);

        // kittens primitives in the body
        assert!(src.contains("warp::load(x_s, g.x"));
        assert!(src.contains("warp::load(w_s, g.w"));
        assert!(src.contains("warp::mul(sq_s, x_s, x_s)"));
        assert!(src.contains("warp::sum(sum_sq, sq_s)"));
        assert!(src.contains("warp::store(g.y, x_s"));

        // extern "C" launcher present
        assert!(src.contains("extern \"C\" cudaError_t launch_rmsnorm"));
    }
}
