// AUTO-GENERATED by scheduled_codegen.rs — do not edit.
// {{ num_nodes }} nodes, {{ num_waves }} waves, {{ num_ctas }} CTAs

#pragma once
#include <cstdint>
#include <cuda_runtime.h>
#include <cuda_bf16.h>
#include <mma.h>
#include <cstdio>
#include <cooperative_groups.h>

// ── CUTLASS device-side primitives for the GEMM dispatch arms ──
// Used by the cutlass_sm80_multistage branch of the per-target
// gemm_kernel choice. The pfl_cutlass / pfl_cutlass_small namespaces
// vendored below are byte-identical to the proven configs from
// templates/fused/preamble_header.cu (which the existing fused
// prefill kernel uses to hit the 42 ms baseline).
#include <cutlass/cutlass.h>
#include <cutlass/numeric_types.h>
#include <cutlass/arch/mma.h>
#include <cutlass/gemm/gemm.h>
#include <cutlass/gemm/threadblock/default_mma.h>
#include <cutlass/layout/matrix.h>
#include <cutlass/epilogue/thread/linear_combination.h>
#include <cutlass/epilogue/threadblock/default_epilogue_tensor_op.h>

// ── pfl_cutlass: 256x128x32 / 4-stage / 8 warps. For the BIG GEMMs:
//    down_proj (M=seq, K=ID=8192, N=HD=2048) and gate_up
//    (M=seq, K=HD=2048, N=ID=8192). Vendored byte-identical from
//    templates/fused/preamble_header.cu — re-vendor when the cutlass
//    pin changes.
namespace pfl_cutlass {
    using ElementA       = cutlass::bfloat16_t;
    using ElementB       = cutlass::bfloat16_t;
    using ElementAccum   = float;
    using LayoutA        = cutlass::layout::RowMajor;
    using LayoutB        = cutlass::layout::ColumnMajor;
    using LayoutC        = cutlass::layout::RowMajor;

    using ThreadblockShape = cutlass::gemm::GemmShape<256, 128, 32>;
    using WarpShape        = cutlass::gemm::GemmShape<64, 64, 32>;
    using InstructionShape = cutlass::gemm::GemmShape<16, 8, 16>;

    using DefaultMmaT = cutlass::gemm::threadblock::DefaultMma<
        ElementA, LayoutA, /*kAlignmentA=*/8,
        ElementB, LayoutB, /*kAlignmentB=*/8,
        ElementAccum, LayoutC,
        cutlass::arch::OpClassTensorOp,
        cutlass::arch::Sm80,
        ThreadblockShape, WarpShape, InstructionShape,
        /*Stages=*/4,
        cutlass::arch::OpMultiplyAdd>;

    using ThreadblockMma = typename DefaultMmaT::ThreadblockMma;
    using IteratorA      = typename DefaultMmaT::IteratorA;
    using IteratorB      = typename DefaultMmaT::IteratorB;
    using MmaSharedStorage = typename ThreadblockMma::SharedStorage;

    using ElementOutput = cutlass::bfloat16_t;
    static constexpr int kEpilogueElementsPerAccess = 8;
    using OutputOpT = cutlass::epilogue::thread::LinearCombination<
        ElementOutput, kEpilogueElementsPerAccess, ElementAccum, ElementAccum>;
    using DefaultEpilogueT = cutlass::epilogue::threadblock::DefaultEpilogueTensorOp<
        ThreadblockShape, typename ThreadblockMma::Operator,
        /*PartitionsK=*/1, OutputOpT, kEpilogueElementsPerAccess>;
    using Epilogue              = typename DefaultEpilogueT::Epilogue;
    using OutputTileIterator    = typename DefaultEpilogueT::OutputTileIterator;
    using EpilogueSharedStorage = typename Epilogue::SharedStorage;

    union SharedStorage {
        MmaSharedStorage main_loop;
        EpilogueSharedStorage epilogue;
    };

    // ── Custom output op: D = silu(alpha*acc) * source. Used for the
    // SECOND of the two gate_up cutlass calls (gate-with-silu*up).
    template <typename ElementOutput_, int Count_, typename ElementAccum_,
              typename ElementCompute_ = ElementAccum_>
    class LinearCombinationSiluMul {
    public:
        using ElementOutput      = ElementOutput_;
        using ElementAccumulator = ElementAccum_;
        using ElementCompute     = ElementCompute_;
        static int const kCount  = Count_;
        using FragmentOutput      = cutlass::Array<ElementOutput, kCount>;
        using FragmentAccumulator = cutlass::Array<ElementAccumulator, kCount>;
        using FragmentSource      = cutlass::Array<ElementOutput, kCount>;
        struct Params {
            ElementCompute alpha = ElementCompute(1);
            ElementCompute beta  = ElementCompute(1);
            ElementCompute const *alpha_ptr = nullptr;
            ElementCompute const *beta_ptr  = nullptr;
            ElementCompute const *const *alpha_ptr_array = nullptr;
            ElementCompute const *const *beta_ptr_array  = nullptr;
            CUTLASS_HOST_DEVICE Params() {}
            CUTLASS_HOST_DEVICE Params(ElementCompute a, ElementCompute b) : alpha(a), beta(b) {}
        };
    private:
        ElementCompute alpha_;
    public:
        CUTLASS_HOST_DEVICE explicit LinearCombinationSiluMul(Params const &p) : alpha_(p.alpha) {}
        CUTLASS_HOST_DEVICE bool is_source_needed() const { return true; }
        CUTLASS_HOST_DEVICE void set_k_partition(int, int) {}
        CUTLASS_HOST_DEVICE
        FragmentOutput operator()(FragmentAccumulator const &accum) const {
            FragmentOutput r;
            CUTLASS_PRAGMA_UNROLL
            for (int i = 0; i < kCount; ++i) {
                float a = float(accum[i]) * float(alpha_);
                r[i] = ElementOutput(a / (1.0f + ::expf(-a)));
            }
            return r;
        }
        CUTLASS_HOST_DEVICE
        FragmentOutput operator()(FragmentAccumulator const &accum,
                                  FragmentSource const &source) const {
            FragmentOutput r;
            CUTLASS_PRAGMA_UNROLL
            for (int i = 0; i < kCount; ++i) {
                float a = float(accum[i]) * float(alpha_);
                float s = a / (1.0f + ::expf(-a));
                r[i] = ElementOutput(s * float(source[i]));
            }
            return r;
        }
    };
    using OutputOpSiluMul = LinearCombinationSiluMul<
        ElementOutput, kEpilogueElementsPerAccess, ElementAccum, ElementAccum>;
    using DefaultEpilogueSiluMulT = cutlass::epilogue::threadblock::DefaultEpilogueTensorOp<
        ThreadblockShape, typename ThreadblockMma::Operator,
        /*PartitionsK=*/1, OutputOpSiluMul, kEpilogueElementsPerAccess>;
    using EpilogueSiluMul = typename DefaultEpilogueSiluMulT::Epilogue;

    static_assert(sizeof(SharedStorage) <= 99 * 1024,
                  "pfl_cutlass SharedStorage exceeds 99KB sm89 dynamic shmem cap");
    static constexpr int kCutlassThreads = ThreadblockMma::WarpCount::kCount * 32;
    static_assert(kCutlassThreads == 256,
                  "pfl_cutlass ThreadblockMma WarpCount must equal 8 (256 threads)");
}  // namespace pfl_cutlass

// ── pfl_cutlass_small: 128x128x32 / 3-stage / 8 warps. For the SMALL
//    GEMMs: qkv (M=seq, K=HD, N=qkv_dim) and o_proj (M=seq, K=HD, N=HD).
namespace pfl_cutlass_small {
    using ElementA       = cutlass::bfloat16_t;
    using ElementB       = cutlass::bfloat16_t;
    using ElementAccum   = float;
    using LayoutA        = cutlass::layout::RowMajor;
    using LayoutB        = cutlass::layout::ColumnMajor;
    using LayoutC        = cutlass::layout::RowMajor;

    using ThreadblockShape = cutlass::gemm::GemmShape<128, 128, 32>;
    using WarpShape        = cutlass::gemm::GemmShape<64, 32, 32>;
    using InstructionShape = cutlass::gemm::GemmShape<16, 8, 16>;

    using DefaultMmaT = cutlass::gemm::threadblock::DefaultMma<
        ElementA, LayoutA, /*kAlignmentA=*/8,
        ElementB, LayoutB, /*kAlignmentB=*/8,
        ElementAccum, LayoutC,
        cutlass::arch::OpClassTensorOp,
        cutlass::arch::Sm80,
        ThreadblockShape, WarpShape, InstructionShape,
        /*Stages=*/3,
        cutlass::arch::OpMultiplyAdd>;

    using ThreadblockMma = typename DefaultMmaT::ThreadblockMma;
    using IteratorA      = typename DefaultMmaT::IteratorA;
    using IteratorB      = typename DefaultMmaT::IteratorB;
    using MmaSharedStorage = typename ThreadblockMma::SharedStorage;

    using ElementOutput = cutlass::bfloat16_t;
    static constexpr int kEpilogueElementsPerAccess = 8;
    using OutputOpT = cutlass::epilogue::thread::LinearCombination<
        ElementOutput, kEpilogueElementsPerAccess, ElementAccum, ElementAccum>;
    using DefaultEpilogueT = cutlass::epilogue::threadblock::DefaultEpilogueTensorOp<
        ThreadblockShape, typename ThreadblockMma::Operator,
        /*PartitionsK=*/1, OutputOpT, kEpilogueElementsPerAccess>;
    using Epilogue              = typename DefaultEpilogueT::Epilogue;
    using OutputTileIterator    = typename DefaultEpilogueT::OutputTileIterator;
    using EpilogueSharedStorage = typename Epilogue::SharedStorage;

    // SiluMul epilogue (for fused gate_up second pass).
    using OutputOpSiluMul = ::pfl_cutlass::LinearCombinationSiluMul<
        ElementOutput, kEpilogueElementsPerAccess, ElementAccum, ElementAccum>;
    using DefaultEpilogueSiluMulT = cutlass::epilogue::threadblock::DefaultEpilogueTensorOp<
        ThreadblockShape, typename ThreadblockMma::Operator,
        /*PartitionsK=*/1, OutputOpSiluMul, kEpilogueElementsPerAccess>;
    using EpilogueSiluMul = typename DefaultEpilogueSiluMulT::Epilogue;

    union SharedStorage {
        MmaSharedStorage main_loop;
        EpilogueSharedStorage epilogue;
    };

    static_assert(sizeof(SharedStorage) <= 99 * 1024,
                  "pfl_cutlass_small SharedStorage exceeds 99KB sm89 dynamic shmem cap");
    static constexpr int kCutlassThreads = ThreadblockMma::WarpCount::kCount * 32;
    static_assert(kCutlassThreads == 256,
                  "pfl_cutlass_small ThreadblockMma WarpCount must equal 8 (256 threads)");
}  // namespace pfl_cutlass_small

// ── Prelude: schedule data tables + model dim constants ──────────────
namespace pfl_sched_{{ name }} {

// NUM_NODES = number of unique coalesced DAG nodes (sizes the per-node
// validation flag array). NUM_OPS = total length of the per-CTA op
// stream (sizes WAVE_OPS and NODE_ID_FOR_OP). They differ when the
// schedule replicates wave-cooperative bindings across all CTAs in a
// wave; otherwise NUM_OPS == NUM_NODES.
constexpr uint32_t NUM_NODES = {{ num_nodes }};
constexpr uint32_t NUM_OPS   = {{ num_ops }};
constexpr uint32_t NUM_WAVES = {{ num_waves }};
constexpr uint32_t NUM_CTAS  = {{ num_ctas }};

// ── Per-target hardware profile (target_profile::TargetProfile) ──
// Single source of truth for device-specific values that flow into
// the schedule, the launcher, and the FlashInfer planner shim.
// Generated by the codegen from a Rust-side `TargetProfile` —
// each constant below traces back to one field. Adding a new arch
// is one new `TargetProfile` constructor on the Rust side; the
// rendered .cu picks up the new values automatically.
constexpr uint32_t TARGET_NUM_SM                  = {{ target_num_sm }};
constexpr uint32_t TARGET_COOPERATIVE_BLOCKS_PER_SM = {{ target_cooperative_blocks_per_sm }};
constexpr uint32_t TARGET_NUM_CLUSTERS            = {{ target_num_clusters }};
constexpr uint32_t TARGET_MAX_DYNAMIC_SHMEM_BYTES = {{ target_max_dynamic_shmem_bytes }};
static_assert(TARGET_NUM_CLUSTERS == NUM_CTAS,
              "schedule's NUM_CTAS must equal target.cooperative_grid_size() so the "
              "FlashInfer attention runner's work_indptr[blockIdx.y] indexing covers "
              "all the planned work");

// ── Kernel choice tags. Set per arch by `TargetProfile`. The
// per-tile-body branches in the megakernel template select between
// implementations via these tags. New variants = new template
// branches. ──
//
//   target_gemm_kernel       = "{{ target_gemm_kernel }}"
//   target_attention_kernel  = "{{ target_attention_kernel }}"
//   target_norm_kernel       = "{{ target_norm_kernel }}"
//   target_rope_kernel       = "{{ target_rope_kernel }}"
//
// GEMM tile shape parameters (only meaningful when
// `target_gemm_kernel` selects a CUTLASS variant; for
// HandWrittenWmma the per-tile body in this template uses its own
// hardcoded `M=16, N=128, K_BLOCK=32` shape and ignores these):
constexpr uint32_t TARGET_GEMM_TILE_M = {{ target_gemm_tile_m }};
constexpr uint32_t TARGET_GEMM_TILE_N = {{ target_gemm_tile_n }};
constexpr uint32_t TARGET_GEMM_TILE_K = {{ target_gemm_tile_k }};
constexpr uint32_t TARGET_GEMM_PIPELINE_STAGES = {{ target_gemm_pipeline_stages }};

// Kernel tags. The first u32 of each TileOp identifies which library
// kernel binding is responsible for that work item — see
// `BoundKernel::kernel_tag` in vllm-tk-macros-core/src/kernel_library.rs.
//
// Tags 0..7 dispatch to the existing per-row hand-written tile bodies
// (`HandWrittenRowTile`). Tags ≥8 dispatch to library-bound kernels:
//
//   8 — FlashInferAttentionLayer (one work item per layer; the
//       per-row work is rolled up into FlashInfer's persistent
//       runner). Production codegen does not yet emit this tag —
//       Phase C2b-step-2 enables it via the flashinfer-aware
//       coalesce pass and Phase C2b-step-3 replaces the placeholder
//       dispatch body below with a real call to
//       BlockBatchPagedAttentionPersistent::Run.
constexpr uint32_t PHASE_ATTN_NORM      = 0;
constexpr uint32_t PHASE_QKV            = 1;
constexpr uint32_t PHASE_ROPE           = 2;
constexpr uint32_t PHASE_ATTENTION      = 3;
constexpr uint32_t PHASE_O_PROJ         = 4;
constexpr uint32_t PHASE_MLP_NORM       = 5;
constexpr uint32_t PHASE_GATE_UP        = 6;
constexpr uint32_t PHASE_DOWN           = 7;
constexpr uint32_t PHASE_FLASHINFER_ATTN = 8;

// 16-byte TileOp (4 u32s — kernel_tag + layer + row + col).
struct TileOp {
  uint32_t kernel_tag;
  uint32_t layer;
  uint32_t row;
  uint32_t col;
};
static_assert(sizeof(TileOp) == 16, "TileOp layout drifted");

// WAVE_OPS — flat array of TileOps; one entry per scheduled op stream
// position (NUM_OPS, not NUM_NODES — wave-cooperative bindings can
// appear in every CTA's stream).
static __device__ const TileOp WAVE_OPS[NUM_OPS] = {
{{ wave_ops_table }}};

// NODE_ID_FOR_OP — parallel to WAVE_OPS for tick-stamp validation.
// Indexed by op stream position; the value is the unique coalesced
// node id (0..NUM_NODES-1) used as the rt.flags subscript.
static __device__ const uint32_t NODE_ID_FOR_OP[NUM_OPS] = {
{{ node_id_for_op_table }}};

// WAVE_CTA_OFFSETS — flat (NUM_WAVES * (NUM_CTAS+1)) prefix table.
static __device__ const uint32_t WAVE_CTA_OFFSETS[NUM_WAVES * (NUM_CTAS + 1)] = {
{{ wave_cta_offsets_table }}};

// Model dim constants — baked compile-time so tile bodies index gmem
// without an extra struct field per dim.
constexpr uint32_t MODEL_NUM_LAYERS    = {{ model_num_layers }};
constexpr uint32_t MODEL_HIDDEN_DIM    = {{ model_hidden_dim }};
constexpr uint32_t MODEL_INTERMEDIATE  = {{ model_intermediate }};
constexpr uint32_t MODEL_NUM_ATTN_H    = {{ model_num_attn_h }};
constexpr uint32_t MODEL_NUM_KV_H      = {{ model_num_kv_h }};
constexpr uint32_t MODEL_HEAD_DIM      = {{ model_head_dim }};
constexpr uint32_t MODEL_SEQ_LEN       = {{ model_seq_len }};
constexpr uint32_t MODEL_ROW_TILE      = {{ model_row_tile }};
constexpr uint32_t MODEL_QKV_COL_TILE  = {{ model_qkv_col_tile }};
constexpr uint32_t MODEL_O_COL_TILE    = {{ model_o_col_tile }};
constexpr uint32_t MODEL_GATE_UP_COL_TILE = {{ model_gate_up_col_tile }};
constexpr uint32_t MODEL_DOWN_COL_TILE = {{ model_down_col_tile }};
constexpr uint32_t MODEL_KV_PAGE_SIZE  = {{ model_kv_page_size }};
constexpr uint32_t MODEL_PAGES_PER_LAYER = {{ model_pages_per_layer }};

}  // namespace pfl_sched_{{ name }}

// ──────────────────────────────────────────────────────────────────────
// Phase 3c (in progress): scheduled BSP megakernel.
// Real tile bodies for phases that have been ported. Placeholders elsewhere.
// ──────────────────────────────────────────────────────────────────────

// FlashInfer attention runner instantiation. The
// `batch_attention_config.inc` brings in DTypeQ/DTypeKV/DTypeO,
// HEAD_DIM_QK/VO, the StandardAttention variant, and the
// PersistentParams struct that the runner reads. We then instantiate
// KernelTraits for the long-Q dispatch task (CTA_TILE_Q_1=128, the
// flashinfer-canonical prefill shape) — for our prefill-only
// workload, packed_qo_len always exceeds CTA_TILE_Q_2=16, so every
// fused FlashInferAttentionLayer node goes through KTraits1 and we
// can ignore KTraits2 entirely.
#include "flashinfer_inst/batch_attention_config.inc"
#include <flashinfer/attention/persistent.cuh>

namespace pfl_sched_{{ name }} {

// Bring the PersistentParams type into the per-variant namespace so
// the runtime struct can hold a typed pointer to a per-layer array.
using FlashInferParams = ::PersistentParams;

// Match `BatchPagedAttentionPersistent` in flashinfer/attention/persistent.cuh
// at line 606 — same `KernelTraits` template instantiation, fixed to
// our config (causal, bf16, head_dim=64, no soft cap).
constexpr uint32_t FI_CTA_TILE_Q   = 128;
constexpr uint32_t FI_NUM_WARPS_Q  = flashinfer::get_num_warps_q(FI_CTA_TILE_Q);
constexpr uint32_t FI_NUM_WARPS_KV = flashinfer::get_num_warps_kv(FI_CTA_TILE_Q);
constexpr uint32_t FI_NUM_MMA_Q    = flashinfer::get_num_mma_q(FI_CTA_TILE_Q);
constexpr uint32_t FI_NUM_MMA_KV   = 4;
constexpr uint32_t FI_NUM_MMA_D_QK = HEAD_DIM_QK / 16;
constexpr uint32_t FI_NUM_MMA_D_VO = HEAD_DIM_VO / 16;

using FlashInferKTraits = flashinfer::KernelTraits<
    flashinfer::MaskMode::kCausal,
    /*CTA_TILE_Q=*/FI_CTA_TILE_Q,
    /*NUM_MMA_Q=*/FI_NUM_MMA_Q,
    /*NUM_MMA_KV=*/FI_NUM_MMA_KV,
    /*NUM_MMA_D_QK=*/FI_NUM_MMA_D_QK,
    /*NUM_MMA_D_VO=*/FI_NUM_MMA_D_VO,
    /*NUM_WARPS_Q=*/FI_NUM_WARPS_Q,
    /*NUM_WARPS_KV=*/FI_NUM_WARPS_KV,
    flashinfer::PosEncodingMode::kNone,
    DTypeQ, DTypeKV, DTypeO, float, IdType,
    StandardAttention<false>>;

using FlashInferRunner =
    flashinfer::BlockBatchPagedAttentionPersistent<FlashInferKTraits, FlashInferParams>;

// Compile-time CTA shape that the megakernel must launch with so the
// FlashInfer Run() invocation has the threads + smem it expects.
constexpr uint32_t FI_NUM_THREADS = FlashInferKTraits::NUM_THREADS;
constexpr size_t   FI_SHARED_STORAGE_BYTES = sizeof(FlashInferKTraits::SharedStorage);

// Megakernel CTA shape: at least 256 threads (the existing
// hand-written tile bodies were written for that count) and at
// least the FlashInfer NUM_THREADS. Worst case = take the max.
constexpr uint32_t MEGAKERNEL_NUM_THREADS =
    (FI_NUM_THREADS > 256) ? FI_NUM_THREADS : 256;

// Activation + weight pointers the tile bodies need. Pointers are typed as
// __nv_bfloat16* because that's what the existing fused kernel uses.
struct globals_t {
    // Activations (all bf16, all [seq_len, dim] row-major unless noted)
    __nv_bfloat16* hidden_states;  // [seq, HIDDEN_DIM]
    __nv_bfloat16* rms_rope;       // [seq, HIDDEN_DIM]  — output of attn_norm
    __nv_bfloat16* qkv;            // [seq, qkv_dim]      — output of qkv gemm
    __nv_bfloat16* q_post_rope;    // [seq, NAH * HEAD_DIM] — Q after rope
    __nv_bfloat16* attn_out;       // [seq, HIDDEN_DIM]
    __nv_bfloat16* rms_gate;       // [seq, HIDDEN_DIM]
    __nv_bfloat16* silu_out;       // [seq, INTERMEDIATE]
    // Paged KV cache. Layout matches the existing fused prefill kernel:
    //   [num_layers * pages_per_layer, page_size, num_kv_heads, head_dim]
    // Indexed as cache[page_idx * page_size * nkh * hd + slot * nkh * hd
    //                  + kv_head * hd + d]
    // where page_idx = prefill_kv_indices[token_pos / page_size]
    //                  + layer * pages_per_layer
    //       slot     = token_pos % page_size
    __nv_bfloat16* k_cache;
    __nv_bfloat16* v_cache;
    // Block table + indptrs (single sequence for the test fixture).
    const int32_t* prefill_kv_indices; // [pages_per_layer]
    const int32_t* prefill_kv_indptr;  // [num_seqs + 1]
    const int32_t* prefill_qo_indptr;  // [num_seqs + 1]
    // Norm weights, per layer.
    __nv_bfloat16* attn_norm_w;    // [num_layers, HIDDEN_DIM]
    __nv_bfloat16* mlp_norm_w;     // [num_layers, HIDDEN_DIM]
    // GEMM weights, per layer.
    __nv_bfloat16* qkv_w;          // [num_layers, qkv_dim, HIDDEN_DIM]
    __nv_bfloat16* o_w;             // [num_layers, HIDDEN_DIM, HIDDEN_DIM]
    __nv_bfloat16* gate_w;          // [num_layers, INTERMEDIATE, HIDDEN_DIM]
    __nv_bfloat16* up_w;            // [num_layers, INTERMEDIATE, HIDDEN_DIM]
    __nv_bfloat16* down_w;          // [num_layers, HIDDEN_DIM, INTERMEDIATE]
    float          eps;
    float          attn_scale;     // = 1 / sqrt(HEAD_DIM)
};

// Per-node validation slot. The kernel writes a monotonic tick into
// `flags[node_id]` at the moment the node executes; the host then checks
// that every node ran exactly once and that ticks respect topological order.
struct SchedRuntime {
    unsigned int* flags;           // [NUM_NODES]
    unsigned int* tick_counter;    // [1]
    unsigned int* barrier_arrived; // [1]
    // Optional per-phase clock accumulator. NULL disables instrumentation.
    // Layout: [num_ctas][NUM_CLOCK_SLOTS] u64 — one row per CTA, 8
    // HandWrittenRowTile slots, 1 FlashInferAttentionLayer slot, 1
    // idle/sync slot.
    unsigned long long* phase_clocks;
    // Per-layer FlashInfer PersistentParams array, populated on the
    // host before launch. May be NULL when no FlashInferAttentionLayer
    // node is in the schedule (in that case the dispatch arm is dead
    // code, never executed). Length = MODEL_NUM_LAYERS.
    FlashInferParams* flashinfer_params;
};

// ── tile_attn_norm: real RMS norm. Reads hidden_states, writes rms_rope. ──
//
// Per-row formula: y[c] = x[c] * w[c] / sqrt(mean(x^2) + eps)
//
// Runs on warp 0 only (32 threads). Other warps idle until the next
// __syncthreads. Each row: warp-shuffle reduction over HIDDEN_DIM, then
// writeback. No shmem.
__device__ __forceinline__ void tile_attn_norm(const globals_t& g, uint32_t layer, uint32_t row) {
    if (threadIdx.x >= 32) return;
    constexpr uint32_t HD       = MODEL_HIDDEN_DIM;
    constexpr uint32_t ROW_TILE = MODEL_ROW_TILE;
    const uint32_t row_start = row * ROW_TILE;
    const __nv_bfloat16* w = g.attn_norm_w + (size_t)layer * HD;
    const uint32_t lane = threadIdx.x;  // 0..31

    #pragma unroll 1
    for (uint32_t r = 0; r < ROW_TILE; ++r) {
        const uint32_t row_idx = row_start + r;
        if (row_idx >= MODEL_SEQ_LEN) break;
        const __nv_bfloat16* x = g.hidden_states + (size_t)row_idx * HD;
        __nv_bfloat16*       y = g.rms_rope      + (size_t)row_idx * HD;

        // ── Reduction: sum of squares across HIDDEN_DIM ──
        float my_sum = 0.0f;
        for (uint32_t c = lane; c < HD; c += 32) {
            float v = __bfloat162float(x[c]);
            my_sum += v * v;
        }
        // Warp shuffle reduction.
        for (int offset = 16; offset > 0; offset >>= 1) {
            my_sum += __shfl_xor_sync(0xffffffff, my_sum, offset);
        }
        const float scale = rsqrtf(my_sum / float(HD) + g.eps);

        // ── Writeback: y[c] = x[c] * scale * w[c] ──
        for (uint32_t c = lane; c < HD; c += 32) {
            float xv = __bfloat162float(x[c]);
            float wv = __bfloat162float(w[c]);
            y[c] = __float2bfloat16(xv * scale * wv);
        }
    }
}

// K-block size for shmem-staged wmma. The K dim is processed in chunks of
// this size; each chunk is loaded gmem→shmem cooperatively (256 threads)
// then consumed by 8 warps × (K_BLOCK/WMMA_K) wmma calls. Larger blocks
// amortize the gmem load cost over more compute but cost more shmem.
constexpr uint32_t SHMEM_GEMM_K_BLOCK = 32;

// cp.async 16-byte chunk copy from gmem→shmem. The shmem pointer must be
// 16-byte aligned. Issues a single sm_80+ cp.async.cg instruction; group
// commit / wait_group is the caller's responsibility.
__device__ __forceinline__ void cp_async_16(void* smem_dst, const void* gmem_src) {
    unsigned smem_int = static_cast<unsigned>(__cvta_generic_to_shared(smem_dst));
    asm volatile("cp.async.cg.shared.global [%0], [%1], 16;\n"
                 :: "r"(smem_int), "l"(gmem_src));
}
__device__ __forceinline__ void cp_async_commit() {
    asm volatile("cp.async.commit_group;\n" ::);
}
template<int N>
__device__ __forceinline__ void cp_async_wait_group() {
    asm volatile("cp.async.wait_group %0;\n" :: "n"(N));
}

// Single CTA-wide shmem arena reused across tile bodies. Wave scheduling
// guarantees only one tile body runs at a time per CTA, so all tile
// bodies that need shmem share this arena and partition it locally.
//
// Sized for the worst case (tile_gate_up: 2-stage cp.async double buffer
// for A + B_gate + B_up):
//   stage 0 / stage 1 each:
//     a_smem      = M  × KB × 2 = 16  × 32 × 2 = 1024 B
//     b_gate_smem = N  × KB × 2 = 128 × 32 × 2 = 8192 B
//     b_up_smem   = N  × KB × 2 = 128 × 32 × 2 = 8192 B
//     stage total                              = 17408 B
//   2 stages                                   = 34816 B
// Accumulator scratches (gate_scratch + up_scratch = 16 KiB) alias with
// stage 0 — they are only touched after the K loop ends, by which point
// stage 0 has been fully consumed.
// Rounded up to 36 KiB. Still within the 48 KiB default sm89 static
// shmem carveout.
constexpr uint32_t TILE_SHMEM_BYTES = 36 * 1024;

// ── tile_qkv: shmem-staged tensor-core GEMM. ──
//
// M=ROW_TILE=16, N=QKV_COL_TILE=128, K=HIDDEN_DIM.
//
// Each K_BLOCK iteration:
//   1. Cooperative gmem→shmem load of A[0:M, k:k+K_BLOCK] and
//      B[col_start:col_start+N, k:k+K_BLOCK] (256 threads, coalesced).
//   2. Each warp does K_BLOCK/16 wmma calls reading from shmem on its
//      16-col slice of the output.
//
// fp32 accumulator stays in registers across the full K. Per-warp 16×16
// fp32 scratch in shmem stages the bf16 writeback. All shmem comes from
// the kernel-scope arena passed via `tile_smem`.
__device__ __forceinline__ void tile_qkv(
    const globals_t& g, uint32_t layer, uint32_t row, uint32_t col, char* tile_smem)
{
    using namespace nvcuda::wmma;
    constexpr uint32_t M            = MODEL_ROW_TILE;
    constexpr uint32_t K            = MODEL_HIDDEN_DIM;
    constexpr uint32_t N            = MODEL_QKV_COL_TILE;
    constexpr uint32_t QKV_DIM_FULL = (MODEL_NUM_ATTN_H + 2 * MODEL_NUM_KV_H) * MODEL_HEAD_DIM;
    constexpr uint32_t WMMA_M       = 16;
    constexpr uint32_t WMMA_N       = 16;
    constexpr uint32_t WMMA_K       = 16;
    constexpr uint32_t N_WARPS      = 8;
    constexpr uint32_t N_PER_WARP   = N / N_WARPS;
    constexpr uint32_t KB           = SHMEM_GEMM_K_BLOCK;
    static_assert(M == WMMA_M, "tile_qkv assumes M == 16");
    static_assert(N % (WMMA_N * N_WARPS) == 0, "tile_qkv: N must be 8*16 multiple");
    static_assert(K % KB == 0, "tile_qkv: K must be a multiple of KB");
    static_assert(KB % WMMA_K == 0, "tile_qkv: KB must be a multiple of 16");
    static_assert(N_PER_WARP == 16, "tile_qkv: each warp owns one 16-col slice");

    const uint32_t row_start = row * M;
    const uint32_t col_start = col * N;
    if (row_start >= MODEL_SEQ_LEN) return;

    const __nv_bfloat16* A_base = g.rms_rope + (size_t)row_start * K;
    const __nv_bfloat16* B_base = g.qkv_w
        + (size_t)layer * QKV_DIM_FULL * K
        + (size_t)col_start * K;
    __nv_bfloat16* C_base = g.qkv + (size_t)row_start * QKV_DIM_FULL + col_start;

    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t n_warp_start = warp_id * N_PER_WARP;
    const uint32_t lane = threadIdx.x;

    // 2-stage cp.async double buffer for A and B (see tile_gate_up).
    constexpr uint32_t STAGE_BYTES = (M + N) * KB * 2;
    __nv_bfloat16* a_smem[2];
    __nv_bfloat16* b_smem[2];
    #pragma unroll
    for (int s = 0; s < 2; ++s) {
        char* base = tile_smem + (size_t)s * STAGE_BYTES;
        a_smem[s] = reinterpret_cast<__nv_bfloat16*>(base);
        b_smem[s] = a_smem[s] + M * KB;
    }
    float* qkv_scratch = reinterpret_cast<float*>(tile_smem);
    float* my_scratch = qkv_scratch + (size_t)warp_id * WMMA_M * WMMA_N;

    fragment<matrix_a, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, row_major> a_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> c_frag;
    fill_fragment(c_frag, 0.0f);

    constexpr uint32_t ELTS_PER_CHUNK = 8;
    constexpr uint32_t A_CHUNKS = (M * KB) / ELTS_PER_CHUNK;
    constexpr uint32_t B_CHUNKS = (N * KB) / ELTS_PER_CHUNK;

    // Prefetch stage 0.
    {
        const int s = 0;
        const uint32_t k_outer_local = 0;
        if (lane < A_CHUNKS) {
            const uint32_t m  = lane / (KB / ELTS_PER_CHUNK);
            const uint32_t k8 = lane % (KB / ELTS_PER_CHUNK);
            cp_async_16(a_smem[s] + m * KB + k8 * ELTS_PER_CHUNK,
                        A_base + (size_t)m * K + k_outer_local + k8 * ELTS_PER_CHUNK);
        }
        #pragma unroll
        for (uint32_t i = lane; i < B_CHUNKS; i += 256) {
            const uint32_t n  = i / (KB / ELTS_PER_CHUNK);
            const uint32_t k8 = i % (KB / ELTS_PER_CHUNK);
            cp_async_16(b_smem[s] + n * KB + k8 * ELTS_PER_CHUNK,
                        B_base + (size_t)n * K + k_outer_local + k8 * ELTS_PER_CHUNK);
        }
        cp_async_commit();
    }

    #pragma unroll 1
    for (uint32_t k_outer = 0; k_outer < K; k_outer += KB) {
        const int cur = (k_outer / KB) & 1;
        const uint32_t k_next = k_outer + KB;

        if (k_next < K) {
            const int s_next = cur ^ 1;
            if (lane < A_CHUNKS) {
                const uint32_t m  = lane / (KB / ELTS_PER_CHUNK);
                const uint32_t k8 = lane % (KB / ELTS_PER_CHUNK);
                cp_async_16(a_smem[s_next] + m * KB + k8 * ELTS_PER_CHUNK,
                            A_base + (size_t)m * K + k_next + k8 * ELTS_PER_CHUNK);
            }
            #pragma unroll
            for (uint32_t i = lane; i < B_CHUNKS; i += 256) {
                const uint32_t n  = i / (KB / ELTS_PER_CHUNK);
                const uint32_t k8 = i % (KB / ELTS_PER_CHUNK);
                cp_async_16(b_smem[s_next] + n * KB + k8 * ELTS_PER_CHUNK,
                            B_base + (size_t)n * K + k_next + k8 * ELTS_PER_CHUNK);
            }
            cp_async_commit();
            cp_async_wait_group<1>();
        } else {
            cp_async_wait_group<0>();
        }
        __syncthreads();

        #pragma unroll
        for (uint32_t k_inner = 0; k_inner < KB; k_inner += WMMA_K) {
            load_matrix_sync(a_frag, a_smem[cur] + k_inner, KB);
            load_matrix_sync(b_frag,
                             b_smem[cur] + (size_t)n_warp_start * KB + k_inner,
                             KB);
            mma_sync(c_frag, a_frag, b_frag, c_frag);
        }
        __syncthreads();
    }

    store_matrix_sync(my_scratch, c_frag, WMMA_N, mem_row_major);
    __syncthreads();

    // Cooperative bf16 writeback across all 256 threads.
    const uint32_t total = M * N;
    for (uint32_t idx = lane; idx < total; idx += 256) {
        const uint32_t m = idx / N;
        const uint32_t n = idx % N;
        if (row_start + m >= MODEL_SEQ_LEN) continue;
        const uint32_t w = n / N_PER_WARP;
        const uint32_t local_n = n % N_PER_WARP;
        const float v = qkv_scratch[w * WMMA_M * WMMA_N + m * WMMA_N + local_n];
        C_base[m * QKV_DIM_FULL + n] = __float2bfloat16(v);
    }
    __syncthreads();
}


// ── tile_rope: rotate + KV cache append for one ROW_TILE-row tile.
//
// Reads qkv[row, qkv_dim] where qkv_dim = (NAH + 2*NKH) * HEAD_DIM and is
// laid out as [Q (NAH*HDM)][K (NKH*HDM)][V (NKH*HDM)].
//
// Writes:
//   - q_post_rope[row, NAH*HDM]   ← rotated Q heads
//   - k_cache[page_idx, slot, kv_head, d]  ← rotated K heads (paged)
//   - v_cache[page_idx, slot, kv_head, d]  ← passthrough V heads (paged)
//
// page_idx = prefill_kv_indices[row / PAGE_SIZE] + layer * PAGES_PER_LAYER
// slot     = row % PAGE_SIZE
//
// Split-half rotation:
//   x0_new = x0 * cos(θ) - x1 * sin(θ)
//   x1_new = x0 * sin(θ) + x1 * cos(θ)
// where θ = position / 10000^(2c/HDM), c ∈ [0, HDM/2).
//
// 32 threads (one warp). The qkv buffer is NOT modified.
__device__ __forceinline__ void tile_rope(const globals_t& g, uint32_t layer, uint32_t row) {
    if (threadIdx.x >= 32) return;  // warp 0 only
    constexpr uint32_t HDM             = MODEL_HEAD_DIM;
    constexpr uint32_t HALF            = HDM / 2;
    constexpr uint32_t NAH             = MODEL_NUM_ATTN_H;
    constexpr uint32_t NKH             = MODEL_NUM_KV_H;
    constexpr uint32_t QKV_DIM         = (NAH + 2 * NKH) * HDM;
    constexpr uint32_t Q_DIM           = NAH * HDM;
    constexpr uint32_t K_OFF           = NAH * HDM;            // K region offset in qkv row
    constexpr uint32_t V_OFF           = (NAH + NKH) * HDM;    // V region offset in qkv row
    constexpr uint32_t ROW_TILE        = MODEL_ROW_TILE;
    constexpr uint32_t PAGE_SIZE       = MODEL_KV_PAGE_SIZE;
    constexpr uint32_t PAGES_PER_LAYER = MODEL_PAGES_PER_LAYER;
    constexpr uint32_t SLOT_STRIDE     = NKH * HDM;            // bf16 elements
    constexpr uint32_t PAGE_STRIDE     = PAGE_SIZE * NKH * HDM;
    constexpr float    THETA_BASE      = 10000.0f;
    const uint32_t lane = threadIdx.x;
    const uint32_t row_start = row * ROW_TILE;

    #pragma unroll 1
    for (uint32_t r = 0; r < ROW_TILE; ++r) {
        const uint32_t row_idx = row_start + r;
        if (row_idx >= MODEL_SEQ_LEN) break;
        const float pos = float(row_idx);
        const __nv_bfloat16* qkv_row = g.qkv + (size_t)row_idx * QKV_DIM;

        // Paged cache slot for this token.
        const uint32_t logical_page  = row_idx / PAGE_SIZE;
        const uint32_t slot_in_page  = row_idx % PAGE_SIZE;
        const int32_t physical_page  = g.prefill_kv_indices[logical_page]
                                       + (int32_t)layer * (int32_t)PAGES_PER_LAYER;
        const size_t page_off = (size_t)physical_page * PAGE_STRIDE;
        const size_t slot_off = (size_t)slot_in_page * SLOT_STRIDE;
        __nv_bfloat16* k_slot = g.k_cache + page_off + slot_off;
        __nv_bfloat16* v_slot = g.v_cache + page_off + slot_off;

        // ── Q heads: rotate, write to q_post_rope ──
        __nv_bfloat16* q_post = g.q_post_rope + (size_t)row_idx * Q_DIM;
        for (uint32_t h = 0; h < NAH; ++h) {
            const __nv_bfloat16* q_in  = qkv_row + h * HDM;
            __nv_bfloat16*       q_out = q_post  + h * HDM;
            for (uint32_t c = lane; c < HALF; c += 32) {
                const float exp_v   = float(2 * c) / float(HDM);
                const float inv_freq = __powf(THETA_BASE, -exp_v);
                const float ang     = pos * inv_freq;
                float cos_v, sin_v;
                __sincosf(ang, &sin_v, &cos_v);
                const float x0 = __bfloat162float(q_in[c]);
                const float x1 = __bfloat162float(q_in[c + HALF]);
                q_out[c]        = __float2bfloat16(x0 * cos_v - x1 * sin_v);
                q_out[c + HALF] = __float2bfloat16(x0 * sin_v + x1 * cos_v);
            }
        }

        // ── K heads: rotate, write to k_cache[page, slot, kv_head, d] ──
        for (uint32_t h = 0; h < NKH; ++h) {
            const __nv_bfloat16* k_in  = qkv_row + K_OFF + h * HDM;
            __nv_bfloat16*       k_out = k_slot  + h * HDM;
            for (uint32_t c = lane; c < HALF; c += 32) {
                const float exp_v   = float(2 * c) / float(HDM);
                const float inv_freq = __powf(THETA_BASE, -exp_v);
                const float ang     = pos * inv_freq;
                float cos_v, sin_v;
                __sincosf(ang, &sin_v, &cos_v);
                const float x0 = __bfloat162float(k_in[c]);
                const float x1 = __bfloat162float(k_in[c + HALF]);
                k_out[c]        = __float2bfloat16(x0 * cos_v - x1 * sin_v);
                k_out[c + HALF] = __float2bfloat16(x0 * sin_v + x1 * cos_v);
            }
        }

        // ── V heads: passthrough copy to v_cache[page, slot, kv_head, d] ──
        for (uint32_t h = 0; h < NKH; ++h) {
            const __nv_bfloat16* v_in  = qkv_row + V_OFF + h * HDM;
            __nv_bfloat16*       v_out = v_slot  + h * HDM;
            for (uint32_t d = lane; d < HDM; d += 32) {
                v_out[d] = v_in[d];
            }
        }
    }
}
// ── tile_attention: 8-warp cooperative paged FA-2 with shmem K/V staging.
//
// Each warp owns ROWS_PER_WARP = ROW_TILE / N_WARPS consecutive rows of
// the row tile (typically 16/8 = 2 rows per warp). All 8 warps share K
// and V via shmem, loaded cooperatively one (kv_head, page) at a time.
//
// Per q_head:
//   - Each warp loads its 2 Q vectors into registers
//   - Per-row online softmax state (m, l, O) lives in registers
//   - For each page in 0..num_pages:
//       all 256 threads load K[page, kv_head, :] and V[page, kv_head, :]
//       into shmem, __syncthreads
//       each warp: for each key in the page, dot product, causal mask,
//                  online softmax update, V accumulator
//   - After all pages: divide O by l, write to attn_out
//
// Causal mask is per-row (warps own different rows with different q_pos).
// num_pages is computed from cta_max_attend so all warps stay in lockstep
// at the cooperative load + sync. Warps whose rows don't need a particular
// page just skip the inner work for that page.
//
// Shmem footprint: K_smem (PAGE_SIZE × HDM × 2 B) + V_smem same. For
// PAGE_SIZE=16, HDM=64: 4 KB total. Fits comfortably in the tile_smem
// arena alongside any other tile body.
__device__ __forceinline__ void tile_attention(
    const globals_t& g, uint32_t layer, uint32_t row, char* tile_smem)
{
    constexpr uint32_t HDM             = MODEL_HEAD_DIM;
    constexpr uint32_t NAH             = MODEL_NUM_ATTN_H;
    constexpr uint32_t NKH             = MODEL_NUM_KV_H;
    constexpr uint32_t GQA_RATIO       = NAH / NKH;
    constexpr uint32_t HD_FULL         = NAH * HDM;
    constexpr uint32_t Q_DIM           = NAH * HDM;
    constexpr uint32_t ROW_TILE        = MODEL_ROW_TILE;
    constexpr uint32_t PAGE_SIZE       = MODEL_KV_PAGE_SIZE;
    constexpr uint32_t PAGES_PER_LAYER = MODEL_PAGES_PER_LAYER;
    constexpr uint32_t N_WARPS         = 8;
    constexpr uint32_t ROWS_PER_WARP   = ROW_TILE / N_WARPS;
    constexpr uint32_t D_PER_LANE      = HDM / 32;
    static_assert(ROW_TILE == N_WARPS * ROWS_PER_WARP,
                  "tile_attention: ROW_TILE must be 8 * ROWS_PER_WARP");
    static_assert(HDM % 32 == 0, "tile_attention: HEAD_DIM must be multiple of 32");

    const uint32_t row_start = row * ROW_TILE;
    if (row_start >= MODEL_SEQ_LEN) return;
    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t lane    = threadIdx.x % 32;
    const uint32_t my_r0   = warp_id * ROWS_PER_WARP;

    // Shmem partition: K_smem | V_smem (each [PAGE_SIZE, HDM] row-major).
    __nv_bfloat16* k_smem = reinterpret_cast<__nv_bfloat16*>(tile_smem);
    __nv_bfloat16* v_smem = k_smem + PAGE_SIZE * HDM;

    const float attn_scale = g.attn_scale;

    // CTA-wide max q_pos determines how many pages every warp must walk
    // (so that the cooperative loads stay in lockstep across warps).
    const uint32_t cta_max_qpos =
        (row_start + ROW_TILE - 1 < MODEL_SEQ_LEN) ? (row_start + ROW_TILE - 1)
                                                   : (MODEL_SEQ_LEN - 1);
    const uint32_t cta_max_attend = cta_max_qpos + 1;
    const uint32_t num_pages = (cta_max_attend + PAGE_SIZE - 1) / PAGE_SIZE;

    // Outer loop: q_head. Each iteration processes ALL rows (for all 8
    // warps) against the same kv_head's K/V data, so the cooperative load
    // amortizes across all 16 rows in the tile.
    for (uint32_t h = 0; h < NAH; ++h) {
        const uint32_t kv_head = h / GQA_RATIO;

        // Load Q for this warp's rows into registers.
        float q_reg[ROWS_PER_WARP][D_PER_LANE];
        #pragma unroll
        for (uint32_t r = 0; r < ROWS_PER_WARP; ++r) {
            const uint32_t row_idx = row_start + my_r0 + r;
            #pragma unroll
            for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                const uint32_t d = dd * 32 + lane;
                if (row_idx < MODEL_SEQ_LEN) {
                    q_reg[r][dd] = __bfloat162float(
                        g.q_post_rope[(size_t)row_idx * Q_DIM + h * HDM + d]);
                } else {
                    q_reg[r][dd] = 0.0f;
                }
            }
        }

        // Per-row online softmax state.
        float m_state[ROWS_PER_WARP];
        float l_state[ROWS_PER_WARP];
        float o_reg[ROWS_PER_WARP][D_PER_LANE];
        #pragma unroll
        for (uint32_t r = 0; r < ROWS_PER_WARP; ++r) {
            m_state[r] = -1e30f;
            l_state[r] = 0.0f;
            #pragma unroll
            for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                o_reg[r][dd] = 0.0f;
            }
        }

        // Page loop: cooperative K/V load + per-row scan.
        for (uint32_t p = 0; p < num_pages; ++p) {
            // Resolve the (kv_head, page) slice in gmem.
            const int32_t physical_page =
                g.prefill_kv_indices[p] + (int32_t)layer * (int32_t)PAGES_PER_LAYER;
            const size_t page_off =
                (size_t)physical_page * PAGE_SIZE * NKH * HDM
                + (size_t)kv_head * HDM;
            const __nv_bfloat16* k_src = g.k_cache + page_off;
            const __nv_bfloat16* v_src = g.v_cache + page_off;

            // Cooperative gmem→shmem load. 256 threads, PAGE_SIZE * HDM
            // elements per buffer = (16*64) / 256 = 4 elements per thread.
            for (uint32_t i = threadIdx.x; i < PAGE_SIZE * HDM; i += 256) {
                const uint32_t k_local = i / HDM;
                const uint32_t d       = i % HDM;
                k_smem[k_local * HDM + d] = k_src[k_local * NKH * HDM + d];
                v_smem[k_local * HDM + d] = v_src[k_local * NKH * HDM + d];
            }
            __syncthreads();

            // How many keys in this page are valid (last page may be short).
            const uint32_t page_kv_start = p * PAGE_SIZE;
            const uint32_t valid_keys =
                (page_kv_start + PAGE_SIZE <= cta_max_attend)
                    ? PAGE_SIZE
                    : (cta_max_attend - page_kv_start);

            // Per-warp scan: each row in this warp processes its valid keys.
            for (uint32_t k_local = 0; k_local < valid_keys; ++k_local) {
                const uint32_t k_pos = page_kv_start + k_local;
                #pragma unroll
                for (uint32_t r = 0; r < ROWS_PER_WARP; ++r) {
                    const uint32_t q_pos = row_start + my_r0 + r;
                    if (q_pos >= MODEL_SEQ_LEN) continue;
                    if (k_pos > q_pos) continue;  // causal mask

                    // Q[r] · K[k_local].
                    float score_partial = 0.0f;
                    #pragma unroll
                    for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                        const uint32_t d = dd * 32 + lane;
                        score_partial += q_reg[r][dd]
                                       * __bfloat162float(k_smem[k_local * HDM + d]);
                    }
                    #pragma unroll
                    for (int offset = 16; offset > 0; offset >>= 1) {
                        score_partial +=
                            __shfl_xor_sync(0xffffffff, score_partial, offset);
                    }
                    const float score = score_partial * attn_scale;

                    // Online softmax update.
                    const float m_new = fmaxf(m_state[r], score);
                    const float alpha = __expf(m_state[r] - m_new);
                    const float se    = __expf(score      - m_new);
                    #pragma unroll
                    for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                        const uint32_t d = dd * 32 + lane;
                        const float vv = __bfloat162float(v_smem[k_local * HDM + d]);
                        o_reg[r][dd] = o_reg[r][dd] * alpha + se * vv;
                    }
                    l_state[r] = l_state[r] * alpha + se;
                    m_state[r] = m_new;
                }
            }

            __syncthreads();  // before next page overwrites shmem
        }

        // Normalize and write attn_out for this warp's rows / this q_head.
        #pragma unroll
        for (uint32_t r = 0; r < ROWS_PER_WARP; ++r) {
            const uint32_t row_idx = row_start + my_r0 + r;
            if (row_idx >= MODEL_SEQ_LEN) continue;
            const float inv_l = 1.0f / l_state[r];
            #pragma unroll
            for (uint32_t dd = 0; dd < D_PER_LANE; ++dd) {
                const uint32_t d = dd * 32 + lane;
                g.attn_out[(size_t)row_idx * HD_FULL + h * HDM + d] =
                    __float2bfloat16(o_reg[r][dd] * inv_l);
            }
        }
    }
}

// ── tile_o_proj: shmem-staged tensor-core GEMM + residual. ──
//
// hidden_states[m,n] += sum_k attn_out[m,k] * o_w[layer, n, k]
//
// Same shmem-staged wmma structure as tile_qkv. The residual seed is
// folded in during the cooperative writeback (read existing bf16, add
// the wmma fp32 result, store bf16).
__device__ __forceinline__ void tile_o_proj(
    const globals_t& g, uint32_t layer, uint32_t row, uint32_t col, char* tile_smem)
{
    using namespace nvcuda::wmma;
    constexpr uint32_t M          = MODEL_ROW_TILE;
    constexpr uint32_t K          = MODEL_HIDDEN_DIM;
    constexpr uint32_t N          = MODEL_O_COL_TILE;
    constexpr uint32_t HD_FULL    = MODEL_HIDDEN_DIM;
    constexpr uint32_t WMMA_M     = 16;
    constexpr uint32_t WMMA_N     = 16;
    constexpr uint32_t WMMA_K     = 16;
    constexpr uint32_t N_WARPS    = 8;
    constexpr uint32_t N_PER_WARP = N / N_WARPS;
    constexpr uint32_t KB         = SHMEM_GEMM_K_BLOCK;
    static_assert(M == WMMA_M, "tile_o_proj assumes M == 16");
    static_assert(N % (WMMA_N * N_WARPS) == 0, "tile_o_proj: N must be 8*16 multiple");
    static_assert(K % KB == 0, "tile_o_proj: K must be a multiple of KB");
    static_assert(KB % WMMA_K == 0, "tile_o_proj: KB must be a multiple of 16");
    static_assert(N_PER_WARP == 16, "tile_o_proj: each warp owns one 16-col slice");

    const uint32_t row_start = row * M;
    const uint32_t col_start = col * N;
    if (row_start >= MODEL_SEQ_LEN) return;

    const __nv_bfloat16* A_base = g.attn_out + (size_t)row_start * K;
    const __nv_bfloat16* B_base = g.o_w
        + (size_t)layer * HD_FULL * K
        + (size_t)col_start * K;
    __nv_bfloat16* C_base = g.hidden_states + (size_t)row_start * HD_FULL + col_start;

    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t n_warp_start = warp_id * N_PER_WARP;
    const uint32_t lane = threadIdx.x;

    // 2-stage cp.async double buffer for A and B (see tile_gate_up).
    constexpr uint32_t STAGE_BYTES = (M + N) * KB * 2;
    __nv_bfloat16* a_smem[2];
    __nv_bfloat16* b_smem[2];
    #pragma unroll
    for (int s = 0; s < 2; ++s) {
        char* base = tile_smem + (size_t)s * STAGE_BYTES;
        a_smem[s] = reinterpret_cast<__nv_bfloat16*>(base);
        b_smem[s] = a_smem[s] + M * KB;
    }
    float* oproj_scratch = reinterpret_cast<float*>(tile_smem);
    float* my_scratch = oproj_scratch + (size_t)warp_id * WMMA_M * WMMA_N;

    fragment<matrix_a, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, row_major> a_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> c_frag;
    fill_fragment(c_frag, 0.0f);

    constexpr uint32_t ELTS_PER_CHUNK = 8;
    constexpr uint32_t A_CHUNKS = (M * KB) / ELTS_PER_CHUNK;
    constexpr uint32_t B_CHUNKS = (N * KB) / ELTS_PER_CHUNK;

    // Prefetch stage 0.
    {
        const int s = 0;
        const uint32_t k_outer_local = 0;
        if (lane < A_CHUNKS) {
            const uint32_t m  = lane / (KB / ELTS_PER_CHUNK);
            const uint32_t k8 = lane % (KB / ELTS_PER_CHUNK);
            cp_async_16(a_smem[s] + m * KB + k8 * ELTS_PER_CHUNK,
                        A_base + (size_t)m * K + k_outer_local + k8 * ELTS_PER_CHUNK);
        }
        #pragma unroll
        for (uint32_t i = lane; i < B_CHUNKS; i += 256) {
            const uint32_t n  = i / (KB / ELTS_PER_CHUNK);
            const uint32_t k8 = i % (KB / ELTS_PER_CHUNK);
            cp_async_16(b_smem[s] + n * KB + k8 * ELTS_PER_CHUNK,
                        B_base + (size_t)n * K + k_outer_local + k8 * ELTS_PER_CHUNK);
        }
        cp_async_commit();
    }

    #pragma unroll 1
    for (uint32_t k_outer = 0; k_outer < K; k_outer += KB) {
        const int cur = (k_outer / KB) & 1;
        const uint32_t k_next = k_outer + KB;

        if (k_next < K) {
            const int s_next = cur ^ 1;
            if (lane < A_CHUNKS) {
                const uint32_t m  = lane / (KB / ELTS_PER_CHUNK);
                const uint32_t k8 = lane % (KB / ELTS_PER_CHUNK);
                cp_async_16(a_smem[s_next] + m * KB + k8 * ELTS_PER_CHUNK,
                            A_base + (size_t)m * K + k_next + k8 * ELTS_PER_CHUNK);
            }
            #pragma unroll
            for (uint32_t i = lane; i < B_CHUNKS; i += 256) {
                const uint32_t n  = i / (KB / ELTS_PER_CHUNK);
                const uint32_t k8 = i % (KB / ELTS_PER_CHUNK);
                cp_async_16(b_smem[s_next] + n * KB + k8 * ELTS_PER_CHUNK,
                            B_base + (size_t)n * K + k_next + k8 * ELTS_PER_CHUNK);
            }
            cp_async_commit();
            cp_async_wait_group<1>();
        } else {
            cp_async_wait_group<0>();
        }
        __syncthreads();

        #pragma unroll
        for (uint32_t k_inner = 0; k_inner < KB; k_inner += WMMA_K) {
            load_matrix_sync(a_frag, a_smem[cur] + k_inner, KB);
            load_matrix_sync(b_frag,
                             b_smem[cur] + (size_t)n_warp_start * KB + k_inner,
                             KB);
            mma_sync(c_frag, a_frag, b_frag, c_frag);
        }
        __syncthreads();
    }

    store_matrix_sync(my_scratch, c_frag, WMMA_N, mem_row_major);
    __syncthreads();

    // Cooperative residual + writeback.
    const uint32_t total = M * N;
    for (uint32_t idx = lane; idx < total; idx += 256) {
        const uint32_t m = idx / N;
        const uint32_t n = idx % N;
        if (row_start + m >= MODEL_SEQ_LEN) continue;
        const uint32_t w = n / N_PER_WARP;
        const uint32_t local_n = n % N_PER_WARP;
        const float mma_val = oproj_scratch[w * WMMA_M * WMMA_N + m * WMMA_N + local_n];
        const float old_c  = __bfloat162float(C_base[m * HD_FULL + n]);
        C_base[m * HD_FULL + n] = __float2bfloat16(old_c + mma_val);
    }
    __syncthreads();
}


// ── tile_mlp_norm: real RMS norm, same structure as tile_attn_norm but
// reads attn_out and writes rms_gate using mlp_norm_w. ──
// ── tile_gate_up: silu(rms_gate @ gate_w^T) * (rms_gate @ up_w^T). ──
//
// Output:  silu_out[m, n] = silu(g_acc) * u_acc
//   g_acc = sum_k rms_gate[m, k] * gate_w[layer, n, k]
//   u_acc = sum_k rms_gate[m, k] *   up_w[layer, n, k]
//
// Two shmem-staged GEMMs sharing the same A operand (rms_gate), fused
// with the SwiGLU elementwise op. Per K_BLOCK: cooperatively load A, gate
// B, and up B into shmem; each warp issues paired wmma over the K_BLOCK
// for both the gate and up accumulators. The fused silu*mul happens in
// fp32 during the cooperative writeback.
__device__ __forceinline__ void tile_gate_up(
    const globals_t& g, uint32_t layer, uint32_t row, uint32_t col, char* tile_smem)
{
    using namespace nvcuda::wmma;
    constexpr uint32_t M          = MODEL_ROW_TILE;
    constexpr uint32_t K          = MODEL_HIDDEN_DIM;
    constexpr uint32_t N          = MODEL_GATE_UP_COL_TILE;
    constexpr uint32_t ID         = MODEL_INTERMEDIATE;
    constexpr uint32_t WMMA_M     = 16;
    constexpr uint32_t WMMA_N     = 16;
    constexpr uint32_t WMMA_K     = 16;
    constexpr uint32_t N_WARPS    = 8;
    constexpr uint32_t N_PER_WARP = N / N_WARPS;
    constexpr uint32_t KB         = SHMEM_GEMM_K_BLOCK;
    static_assert(M == WMMA_M, "tile_gate_up assumes M == 16");
    static_assert(N % (WMMA_N * N_WARPS) == 0, "tile_gate_up: N must be 8*16 multiple");
    static_assert(K % KB == 0, "tile_gate_up: K must be a multiple of KB");
    static_assert(KB % WMMA_K == 0, "tile_gate_up: KB must be a multiple of 16");
    static_assert(N_PER_WARP == 16, "tile_gate_up: each warp owns one 16-col slice");

    const uint32_t row_start = row * M;
    const uint32_t col_start = col * N;
    if (row_start >= MODEL_SEQ_LEN) return;

    const __nv_bfloat16* A_base      = g.rms_gate + (size_t)row_start * K;
    const __nv_bfloat16* B_gate_base = g.gate_w
        + (size_t)layer * ID * K
        + (size_t)col_start * K;
    const __nv_bfloat16* B_up_base   = g.up_w
        + (size_t)layer * ID * K
        + (size_t)col_start * K;
    __nv_bfloat16* C_base = g.silu_out + (size_t)row_start * ID + col_start;

    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t n_warp_start = warp_id * N_PER_WARP;
    const uint32_t lane = threadIdx.x;

    // Two-stage cp.async double buffer for A, B_gate, B_up.
    //
    // Layout (per stage):
    //   a_smem      [M  × KB] = 16  × 32 × 2 =  1024 B
    //   b_gate_smem [N  × KB] = 128 × 32 × 2 =  8192 B
    //   b_up_smem   [N  × KB] = 128 × 32 × 2 =  8192 B
    //   stage size                              17408 B
    // Two stages: 34816 B. Scratches (g+u = 16 KiB) alias with stage 0,
    // because they are only touched after the K loop completes.
    constexpr uint32_t STAGE_BYTES = (M + 2 * N) * KB * 2;  // bf16
    __nv_bfloat16* a_smem[2];
    __nv_bfloat16* b_gate_smem[2];
    __nv_bfloat16* b_up_smem[2];
    #pragma unroll
    for (int s = 0; s < 2; ++s) {
        char* base = tile_smem + (size_t)s * STAGE_BYTES;
        a_smem[s]      = reinterpret_cast<__nv_bfloat16*>(base);
        b_gate_smem[s] = a_smem[s] + M * KB;
        b_up_smem[s]   = b_gate_smem[s] + N * KB;
    }
    // Scratches alias with stage 0 — used only after the K loop, by which
    // point stage 0 has been fully consumed and the wmma fragments hold
    // the data we need to spill.
    float* gate_scratch = reinterpret_cast<float*>(tile_smem);
    float* up_scratch   = gate_scratch + N_WARPS * WMMA_M * WMMA_N;
    float* my_g_scratch = gate_scratch + (size_t)warp_id * WMMA_M * WMMA_N;
    float* my_u_scratch = up_scratch   + (size_t)warp_id * WMMA_M * WMMA_N;

    fragment<matrix_a, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, row_major> a_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_g_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_u_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> g_acc_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> u_acc_frag;
    fill_fragment(g_acc_frag, 0.0f);
    fill_fragment(u_acc_frag, 0.0f);

    // 16-byte cp.async = 8 bf16 elements per copy.
    constexpr uint32_t ELTS_PER_CHUNK = 8;
    constexpr uint32_t A_CHUNKS = (M * KB) / ELTS_PER_CHUNK;        // 64
    constexpr uint32_t B_CHUNKS = (N * KB) / ELTS_PER_CHUNK;        // 512

    // Prefetch stage 0 (inlined; A: 64 chunks, B_gate/B_up: 512 chunks each).
    {
        const int s = 0;
        const uint32_t k_outer_local = 0;
        if (lane < A_CHUNKS) {
            const uint32_t m   = lane / (KB / ELTS_PER_CHUNK);
            const uint32_t k8  = lane % (KB / ELTS_PER_CHUNK);
            cp_async_16(a_smem[s] + m * KB + k8 * ELTS_PER_CHUNK,
                        A_base + (size_t)m * K + k_outer_local + k8 * ELTS_PER_CHUNK);
        }
        #pragma unroll
        for (uint32_t i = lane; i < B_CHUNKS; i += 256) {
            const uint32_t n   = i / (KB / ELTS_PER_CHUNK);
            const uint32_t k8  = i % (KB / ELTS_PER_CHUNK);
            cp_async_16(b_gate_smem[s] + n * KB + k8 * ELTS_PER_CHUNK,
                        B_gate_base + (size_t)n * K + k_outer_local + k8 * ELTS_PER_CHUNK);
            cp_async_16(b_up_smem[s]   + n * KB + k8 * ELTS_PER_CHUNK,
                        B_up_base   + (size_t)n * K + k_outer_local + k8 * ELTS_PER_CHUNK);
        }
        cp_async_commit();
    }

    #pragma unroll 1
    for (uint32_t k_outer = 0; k_outer < K; k_outer += KB) {
        const int cur = (k_outer / KB) & 1;
        const uint32_t k_next = k_outer + KB;

        if (k_next < K) {
            // Issue next stage (inline), then wait for the previous one.
            const int s_next = cur ^ 1;
            if (lane < A_CHUNKS) {
                const uint32_t m   = lane / (KB / ELTS_PER_CHUNK);
                const uint32_t k8  = lane % (KB / ELTS_PER_CHUNK);
                cp_async_16(a_smem[s_next] + m * KB + k8 * ELTS_PER_CHUNK,
                            A_base + (size_t)m * K + k_next + k8 * ELTS_PER_CHUNK);
            }
            #pragma unroll
            for (uint32_t i = lane; i < B_CHUNKS; i += 256) {
                const uint32_t n   = i / (KB / ELTS_PER_CHUNK);
                const uint32_t k8  = i % (KB / ELTS_PER_CHUNK);
                cp_async_16(b_gate_smem[s_next] + n * KB + k8 * ELTS_PER_CHUNK,
                            B_gate_base + (size_t)n * K + k_next + k8 * ELTS_PER_CHUNK);
                cp_async_16(b_up_smem[s_next]   + n * KB + k8 * ELTS_PER_CHUNK,
                            B_up_base   + (size_t)n * K + k_next + k8 * ELTS_PER_CHUNK);
            }
            cp_async_commit();
            cp_async_wait_group<1>();
        } else {
            cp_async_wait_group<0>();
        }
        __syncthreads();

        #pragma unroll
        for (uint32_t k_inner = 0; k_inner < KB; k_inner += WMMA_K) {
            load_matrix_sync(a_frag, a_smem[cur] + k_inner, KB);
            load_matrix_sync(b_g_frag, b_gate_smem[cur] + (size_t)n_warp_start * KB + k_inner, KB);
            load_matrix_sync(b_u_frag, b_up_smem[cur]   + (size_t)n_warp_start * KB + k_inner, KB);
            mma_sync(g_acc_frag, a_frag, b_g_frag, g_acc_frag);
            mma_sync(u_acc_frag, a_frag, b_u_frag, u_acc_frag);
        }
        __syncthreads();
    }

    store_matrix_sync(my_g_scratch, g_acc_frag, WMMA_N, mem_row_major);
    store_matrix_sync(my_u_scratch, u_acc_frag, WMMA_N, mem_row_major);
    __syncthreads();

    // Cooperative SwiGLU writeback: silu(g) * u → bf16
    const uint32_t total = M * N;
    for (uint32_t idx = lane; idx < total; idx += 256) {
        const uint32_t m = idx / N;
        const uint32_t n = idx % N;
        if (row_start + m >= MODEL_SEQ_LEN) continue;
        const uint32_t w = n / N_PER_WARP;
        const uint32_t local_n = n % N_PER_WARP;
        const uint32_t off = w * WMMA_M * WMMA_N + m * WMMA_N + local_n;
        const float gv = gate_scratch[off];
        const float uv = up_scratch[off];
        const float silu_g = gv / (1.0f + __expf(-gv));
        C_base[m * ID + n] = __float2bfloat16(silu_g * uv);
    }
    __syncthreads();
}

__device__ __forceinline__ void tile_mlp_norm(const globals_t& g, uint32_t layer, uint32_t row) {
    if (threadIdx.x >= 32) return;  // warp 0 only
    constexpr uint32_t HD       = MODEL_HIDDEN_DIM;
    constexpr uint32_t ROW_TILE = MODEL_ROW_TILE;
    const uint32_t row_start = row * ROW_TILE;
    const __nv_bfloat16* w = g.mlp_norm_w + (size_t)layer * HD;
    const uint32_t lane = threadIdx.x;

    #pragma unroll 1
    for (uint32_t r = 0; r < ROW_TILE; ++r) {
        const uint32_t row_idx = row_start + r;
        if (row_idx >= MODEL_SEQ_LEN) break;
        const __nv_bfloat16* x = g.attn_out + (size_t)row_idx * HD;
        __nv_bfloat16*       y = g.rms_gate + (size_t)row_idx * HD;

        float my_sum = 0.0f;
        for (uint32_t c = lane; c < HD; c += 32) {
            float v = __bfloat162float(x[c]);
            my_sum += v * v;
        }
        for (int offset = 16; offset > 0; offset >>= 1) {
            my_sum += __shfl_xor_sync(0xffffffff, my_sum, offset);
        }
        const float scale = rsqrtf(my_sum / float(HD) + g.eps);

        for (uint32_t c = lane; c < HD; c += 32) {
            float xv = __bfloat162float(x[c]);
            float wv = __bfloat162float(w[c]);
            y[c] = __float2bfloat16(xv * scale * wv);
        }
    }
}

// ── tile_down: shmem-staged tensor-core GEMM + residual.
//
// hidden_states[m,n] += sum_k silu_out[m,k] * down_w[layer, n, k]
//
// Same shmem-staged wmma + residual writeback as tile_o_proj. K is the
// intermediate dim, which is the largest K of the four GEMMs.
__device__ __forceinline__ void tile_down(
    const globals_t& g, uint32_t layer, uint32_t row, uint32_t col, char* tile_smem)
{
    using namespace nvcuda::wmma;
    constexpr uint32_t M          = MODEL_ROW_TILE;
    constexpr uint32_t K          = MODEL_INTERMEDIATE;
    constexpr uint32_t N          = MODEL_DOWN_COL_TILE;
    constexpr uint32_t HD_FULL    = MODEL_HIDDEN_DIM;
    constexpr uint32_t WMMA_M     = 16;
    constexpr uint32_t WMMA_N     = 16;
    constexpr uint32_t WMMA_K     = 16;
    constexpr uint32_t N_WARPS    = 8;
    constexpr uint32_t N_PER_WARP = N / N_WARPS;
    constexpr uint32_t KB         = SHMEM_GEMM_K_BLOCK;
    static_assert(M == WMMA_M, "tile_down assumes M == 16");
    static_assert(N % (WMMA_N * N_WARPS) == 0, "tile_down: N must be 8*16 multiple");
    static_assert(K % KB == 0, "tile_down: K must be a multiple of KB");
    static_assert(KB % WMMA_K == 0, "tile_down: KB must be a multiple of 16");
    static_assert(N_PER_WARP == 16, "tile_down: each warp owns one 16-col slice");

    const uint32_t row_start = row * M;
    const uint32_t col_start = col * N;
    if (row_start >= MODEL_SEQ_LEN) return;

    const __nv_bfloat16* A_base = g.silu_out + (size_t)row_start * K;
    const __nv_bfloat16* B_base = g.down_w
        + (size_t)layer * HD_FULL * K
        + (size_t)col_start * K;
    __nv_bfloat16* C_base = g.hidden_states + (size_t)row_start * HD_FULL + col_start;

    const uint32_t warp_id = threadIdx.x / 32;
    const uint32_t n_warp_start = warp_id * N_PER_WARP;
    const uint32_t lane = threadIdx.x;

    // 2-stage cp.async double buffer for A and B. Stage layout:
    //   a_smem [M  × KB] = 1024 B
    //   b_smem [N  × KB] = 8192 B
    //   stage total      = 9216 B  (× 2 = 18432 B)
    // down_scratch (8 KiB) aliases with stage 0 — only used after K loop.
    constexpr uint32_t STAGE_BYTES = (M + N) * KB * 2;  // bf16
    __nv_bfloat16* a_smem[2];
    __nv_bfloat16* b_smem[2];
    #pragma unroll
    for (int s = 0; s < 2; ++s) {
        char* base = tile_smem + (size_t)s * STAGE_BYTES;
        a_smem[s] = reinterpret_cast<__nv_bfloat16*>(base);
        b_smem[s] = a_smem[s] + M * KB;
    }
    float* down_scratch = reinterpret_cast<float*>(tile_smem);
    float* my_scratch = down_scratch + (size_t)warp_id * WMMA_M * WMMA_N;

    fragment<matrix_a, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, row_major> a_frag;
    fragment<matrix_b, WMMA_M, WMMA_N, WMMA_K, __nv_bfloat16, col_major> b_frag;
    fragment<accumulator, WMMA_M, WMMA_N, WMMA_K, float> c_frag;
    fill_fragment(c_frag, 0.0f);

    constexpr uint32_t ELTS_PER_CHUNK = 8;
    constexpr uint32_t A_CHUNKS = (M * KB) / ELTS_PER_CHUNK;  // 64
    constexpr uint32_t B_CHUNKS = (N * KB) / ELTS_PER_CHUNK;  // 512

    // Prefetch stage 0.
    {
        const int s = 0;
        const uint32_t k_outer_local = 0;
        if (lane < A_CHUNKS) {
            const uint32_t m  = lane / (KB / ELTS_PER_CHUNK);
            const uint32_t k8 = lane % (KB / ELTS_PER_CHUNK);
            cp_async_16(a_smem[s] + m * KB + k8 * ELTS_PER_CHUNK,
                        A_base + (size_t)m * K + k_outer_local + k8 * ELTS_PER_CHUNK);
        }
        #pragma unroll
        for (uint32_t i = lane; i < B_CHUNKS; i += 256) {
            const uint32_t n  = i / (KB / ELTS_PER_CHUNK);
            const uint32_t k8 = i % (KB / ELTS_PER_CHUNK);
            cp_async_16(b_smem[s] + n * KB + k8 * ELTS_PER_CHUNK,
                        B_base + (size_t)n * K + k_outer_local + k8 * ELTS_PER_CHUNK);
        }
        cp_async_commit();
    }

    #pragma unroll 1
    for (uint32_t k_outer = 0; k_outer < K; k_outer += KB) {
        const int cur = (k_outer / KB) & 1;
        const uint32_t k_next = k_outer + KB;

        if (k_next < K) {
            const int s_next = cur ^ 1;
            if (lane < A_CHUNKS) {
                const uint32_t m  = lane / (KB / ELTS_PER_CHUNK);
                const uint32_t k8 = lane % (KB / ELTS_PER_CHUNK);
                cp_async_16(a_smem[s_next] + m * KB + k8 * ELTS_PER_CHUNK,
                            A_base + (size_t)m * K + k_next + k8 * ELTS_PER_CHUNK);
            }
            #pragma unroll
            for (uint32_t i = lane; i < B_CHUNKS; i += 256) {
                const uint32_t n  = i / (KB / ELTS_PER_CHUNK);
                const uint32_t k8 = i % (KB / ELTS_PER_CHUNK);
                cp_async_16(b_smem[s_next] + n * KB + k8 * ELTS_PER_CHUNK,
                            B_base + (size_t)n * K + k_next + k8 * ELTS_PER_CHUNK);
            }
            cp_async_commit();
            cp_async_wait_group<1>();
        } else {
            cp_async_wait_group<0>();
        }
        __syncthreads();

        #pragma unroll
        for (uint32_t k_inner = 0; k_inner < KB; k_inner += WMMA_K) {
            load_matrix_sync(a_frag, a_smem[cur] + k_inner, KB);
            load_matrix_sync(b_frag,
                             b_smem[cur] + (size_t)n_warp_start * KB + k_inner,
                             KB);
            mma_sync(c_frag, a_frag, b_frag, c_frag);
        }
        __syncthreads();
    }

    store_matrix_sync(my_scratch, c_frag, WMMA_N, mem_row_major);
    __syncthreads();

    const uint32_t total = M * N;
    for (uint32_t idx = lane; idx < total; idx += 256) {
        const uint32_t m = idx / N;
        const uint32_t n = idx % N;
        if (row_start + m >= MODEL_SEQ_LEN) continue;
        const uint32_t w = n / N_PER_WARP;
        const uint32_t local_n = n % N_PER_WARP;
        const float mma_val = down_scratch[w * WMMA_M * WMMA_N + m * WMMA_N + local_n];
        const float old_c  = __bfloat162float(C_base[m * HD_FULL + n]);
        C_base[m * HD_FULL + n] = __float2bfloat16(old_c + mma_val);
    }
    __syncthreads();
}


// ── CUTLASS device-side dispatch helpers ──
//
// One helper per (cutlass namespace × epilogue) combination. Mirrors
// gemm_cutlass_mcta.cu from the existing fused prefill kernel
// exactly — same iterator construction, same epilogue, same CTA-strided
// loop over (rt, ct) work tiles. Wave-cooperative: every persistent
// CTA in the wave runs the helper, each picks its share of
// (M_tile, N_tile) work via its `bid` = blockIdx.y in the strided
// loop.
//
// Inlined as four separate functions (instead of one templated
// helper) because nvcc rejects namespace names as template type
// arguments — `tile_cutlass_gemm_layer<::pfl_cutlass, …>` doesn't
// compile.

#define TILE_CUTLASS_GEMM_BODY(NS, EpilogueT, OutputOpT)                                            \
    using PflMma            = typename NS::ThreadblockMma;                                          \
    using PflIteratorA      = typename NS::IteratorA;                                               \
    using PflIteratorB      = typename NS::IteratorB;                                               \
    using PflSharedStorage  = typename NS::SharedStorage;                                           \
    using PflFragmentC      = typename PflMma::FragmentC;                                           \
    using PflLayoutA        = typename NS::LayoutA;                                                 \
    using PflLayoutB        = typename NS::LayoutB;                                                 \
    using PflLayoutC        = typename NS::LayoutC;                                                 \
    using PflOutputTileIter = typename NS::OutputTileIterator;                                      \
                                                                                                    \
    constexpr int kThreadblockM = NS::ThreadblockShape::kM;                                         \
    constexpr int kThreadblockN = NS::ThreadblockShape::kN;                                         \
    constexpr int kThreadblockK = NS::ThreadblockShape::kK;                                         \
                                                                                                    \
    const int row_tiles_cta = (M + kThreadblockM - 1) / kThreadblockM;                              \
    const int col_tiles_cta = (N + kThreadblockN - 1) / kThreadblockN;                              \
    const int total_work_cta = row_tiles_cta * col_tiles_cta;                                       \
                                                                                                    \
    PflSharedStorage& shared_storage = *reinterpret_cast<PflSharedStorage*>(dyn_smem);              \
                                                                                                    \
    const int thread_idx = threadIdx.x;                                                             \
    const int warp_idx   = thread_idx / 32;                                                         \
    const int lane_idx   = thread_idx % 32;                                                         \
                                                                                                    \
    PflLayoutA layout_a{K};                                                                         \
    PflLayoutB layout_b{K};                                                                         \
    PflLayoutC layout_c{N};                                                                         \
    typename PflIteratorA::Params params_A{layout_a};                                               \
    typename PflIteratorB::Params params_B{layout_b};                                               \
    typename PflOutputTileIter::Params params_C{layout_c};                                          \
    typename PflOutputTileIter::Params params_D{layout_c};                                          \
                                                                                                    \
    cutlass::bfloat16_t* ptr_A_cl = reinterpret_cast<cutlass::bfloat16_t*>(a_ptr);                  \
    cutlass::bfloat16_t* ptr_B_cl = reinterpret_cast<cutlass::bfloat16_t*>(b_ptr);                  \
    cutlass::bfloat16_t* ptr_OUT_cl = reinterpret_cast<cutlass::bfloat16_t*>(out_ptr);              \
                                                                                                    \
    for (int wu = (int)cta_id_in_grid; wu < total_work_cta; wu += (int)NUM_CTAS) {                  \
        const int rt = wu / col_tiles_cta;                                                          \
        const int ct = wu % col_tiles_cta;                                                          \
        const int tb_m = rt * kThreadblockM;                                                        \
        const int tb_n = ct * kThreadblockN;                                                        \
                                                                                                    \
        PflIteratorA iter_A(                                                                        \
            params_A, ptr_A_cl, /*extent*/ {M, K}, thread_idx,                                      \
            /*tb_offset*/ {tb_m, 0}, /*gather_indices*/ nullptr);                                   \
        PflIteratorB iter_B(                                                                        \
            params_B, ptr_B_cl, /*extent*/ {K, N}, thread_idx,                                      \
            /*tb_offset*/ {0, tb_n}, /*gather_indices*/ nullptr);                                   \
                                                                                                    \
        PflMma mma(shared_storage.main_loop, thread_idx, warp_idx, lane_idx);                       \
        PflFragmentC accum;                                                                         \
        accum.clear();                                                                              \
                                                                                                    \
        const int gemm_k_iterations = (K + kThreadblockK - 1) / kThreadblockK;                      \
        mma(gemm_k_iterations, accum, iter_A, iter_B, accum);                                       \
                                                                                                    \
        __syncthreads();                                                                            \
                                                                                                    \
        PflOutputTileIter iter_C(                                                                   \
            params_C, ptr_OUT_cl, /*extent*/ {M, N}, thread_idx,                                    \
            /*tb_offset*/ {tb_m, tb_n}, /*scatter_indices*/ nullptr);                               \
        PflOutputTileIter iter_D(                                                                   \
            params_D, ptr_OUT_cl, /*extent*/ {M, N}, thread_idx,                                    \
            /*tb_offset*/ {tb_m, tb_n}, /*scatter_indices*/ nullptr);                               \
                                                                                                    \
        typename OutputOpT::Params output_params{/*alpha=*/1.0f, /*beta=*/beta_value};              \
        OutputOpT output_op(output_params);                                                         \
        EpilogueT epilogue(shared_storage.epilogue, thread_idx, warp_idx, lane_idx);                \
        epilogue(output_op, iter_D, accum, iter_C);                                                 \
                                                                                                    \
        __syncthreads();                                                                            \
    }

__device__ __forceinline__ void tile_cutlass_gemm_big_lincomb(
    __nv_bfloat16* a_ptr, __nv_bfloat16* b_ptr, __nv_bfloat16* out_ptr,
    int M, int K, int N, float beta_value,
    char* dyn_smem, uint32_t cta_id_in_grid)
{
    TILE_CUTLASS_GEMM_BODY(::pfl_cutlass, ::pfl_cutlass::Epilogue, ::pfl_cutlass::OutputOpT)
}

__device__ __forceinline__ void tile_cutlass_gemm_big_silumul(
    __nv_bfloat16* a_ptr, __nv_bfloat16* b_ptr, __nv_bfloat16* out_ptr,
    int M, int K, int N, float beta_value,
    char* dyn_smem, uint32_t cta_id_in_grid)
{
    TILE_CUTLASS_GEMM_BODY(::pfl_cutlass, ::pfl_cutlass::EpilogueSiluMul,
                           ::pfl_cutlass::OutputOpSiluMul)
}

__device__ __forceinline__ void tile_cutlass_gemm_small_lincomb(
    __nv_bfloat16* a_ptr, __nv_bfloat16* b_ptr, __nv_bfloat16* out_ptr,
    int M, int K, int N, float beta_value,
    char* dyn_smem, uint32_t cta_id_in_grid)
{
    TILE_CUTLASS_GEMM_BODY(::pfl_cutlass_small, ::pfl_cutlass_small::Epilogue,
                           ::pfl_cutlass_small::OutputOpT)
}

__device__ __forceinline__ void tile_cutlass_gemm_small_silumul(
    __nv_bfloat16* a_ptr, __nv_bfloat16* b_ptr, __nv_bfloat16* out_ptr,
    int M, int K, int N, float beta_value,
    char* dyn_smem, uint32_t cta_id_in_grid)
{
    TILE_CUTLASS_GEMM_BODY(::pfl_cutlass_small, ::pfl_cutlass_small::EpilogueSiluMul,
                           ::pfl_cutlass_small::OutputOpSiluMul)
}

#undef TILE_CUTLASS_GEMM_BODY

// Grid-wide barrier via a single global counter. Every CTA's thread 0 bumps
// the counter once per wave; all CTAs spin until the counter reaches the
// expected (wave_idx + 1) * NUM_CTAS value. Requires the launch to fit all
// CTAs concurrently — true for us at num_ctas == num_sms with 1 CTA/SM.
__device__ __forceinline__ void grid_barrier(unsigned int* counter, unsigned int wave_idx) {
    // Hand-rolled gmem-flag spin barrier. Tried replacing with
    // cooperative_groups::this_grid().sync() — measured identical
    // idle/sync at seq=1024 (14.6 → 14.8 ms), so the per-barrier cost
    // is fundamental, not mechanism. Reducing it requires fewer
    // barriers, not a faster barrier.
    __syncthreads();
    if (threadIdx.x == 0) {
        const unsigned int target = (wave_idx + 1u) * NUM_CTAS;
        atomicAdd(counter, 1u);
        __threadfence();
        while (atomicAdd(counter, 0u) < target) {
            // spin
        }
    }
    __syncthreads();
}

__global__ void scheduled_megakernel_{{ name }}(globals_t g, SchedRuntime rt) {
    // Persistent CTA id lives in blockIdx.y so that FlashInfer's
    // attention runner — which reads `work_indptr[blockIdx.y]` —
    // sees the right per-CTA work range. The grid is launched as
    // `dim3(1, NUM_CTAS)` for the same reason. blockIdx.x stays at
    // 0 (FlashInfer uses it for the cluster Q-split, which we run
    // with cluster_size=1).
    const uint32_t cta_id = blockIdx.y;
    const uint32_t tid    = threadIdx.x;
    if (cta_id >= NUM_CTAS) return;

    // Single CTA-wide shmem arena reused across tile bodies. Wave scheduling
    // means only one tile body runs at a time per CTA, so they can share.
    //
    // Phase C2b-step-3a: this is now a *dynamic* shmem allocation
    // (`extern __shared__`) so the launcher can opt into L4's 99 KiB
    // carveout via `cudaFuncSetAttribute(...,
    // cudaFuncAttributeMaxDynamicSharedMemorySize, ...)`. The size is
    // passed through the third launch arg of
    // `cudaLaunchCooperativeKernel`. For sub-step 3a the requested
    // size is unchanged from the old static `TILE_SHMEM_BYTES`
    // (36 KiB) — sub-step 3c grows it to fit FlashInfer's
    // `KTraits::SharedStorage` once the runner is wired in.
    extern __shared__ __align__(16) uint8_t tile_smem_dyn[];
    char* tile_smem = reinterpret_cast<char*>(tile_smem_dyn);

    // Per-CTA per-kernel-tag clock accumulator (sum of clock64() deltas
    // around each tile body). Lives in registers; written to gmem at
    // the very end if instrumentation is enabled (rt.phase_clocks !=
    // nullptr). Slots 0..7 are the per-phase HandWrittenRowTile bodies,
    // slot 8 is FlashInferAttentionLayer, slot 9 is "idle / sync /
    // barrier" (everything outside a tile body). The Rust bench reader
    // strides at 10 to match.
    // Slots 0..7: hand-written tile phase tags (PHASE_*).
    // Slot 8: FlashInfer attention. Slot 9: idle/sync.
    // Slots 10..13: CutlassGemmLayer tags (qkv/oproj/gate_up/down).
    // Must cover the maximum kernel_tag any op can carry —
    // phase_clock[op.kernel_tag] is a direct index, and a stack-array
    // OOB here silently corrupts adjacent locals. The "case 12 cursed
    // smem misalign" debugging saga was an OOB write into this array
    // before NUM_CLOCK_SLOTS was bumped past 9.
    constexpr uint32_t NUM_CLOCK_SLOTS = 14;
    constexpr uint32_t IDLE_SLOT = 9;
    unsigned long long phase_clock[NUM_CLOCK_SLOTS] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    const bool prof = (rt.phase_clocks != nullptr) && (tid == 0);
    unsigned long long t_outside = prof ? clock64() : 0ULL;

    for (uint32_t w = 0; w < NUM_WAVES; ++w) {
        const uint32_t off = WAVE_CTA_OFFSETS[w * (NUM_CTAS + 1) + cta_id];
        const uint32_t end = WAVE_CTA_OFFSETS[w * (NUM_CTAS + 1) + cta_id + 1];

        // Execute every tile assigned to this CTA in this wave.
        for (uint32_t i = off; i < end; ++i) {
            const TileOp op = WAVE_OPS[i];
            unsigned long long t_in = 0ULL;
            if (prof) {
                t_in = clock64();
                phase_clock[IDLE_SLOT] += t_in - t_outside;  // accumulate idle time
            }
            switch (op.kernel_tag) {
                case PHASE_ATTN_NORM: tile_attn_norm(g, op.layer, op.row); break;
                case PHASE_QKV:       tile_qkv      (g, op.layer, op.row, op.col, tile_smem); break;
                case PHASE_ROPE:      tile_rope     (g, op.layer, op.row); break;
                case PHASE_ATTENTION: tile_attention(g, op.layer, op.row, tile_smem); break;
                case PHASE_O_PROJ:    tile_o_proj   (g, op.layer, op.row, op.col, tile_smem); break;
                case PHASE_MLP_NORM:  tile_mlp_norm (g, op.layer, op.row); break;
                case PHASE_GATE_UP:   tile_gate_up  (g, op.layer, op.row, op.col, tile_smem); break;
                case PHASE_DOWN:      tile_down     (g, op.layer, op.row, op.col, tile_smem); break;
                case 10 /* CutlassGemmLayer { Qkv } */: {
                    // QKV: A=g.rms_rope [seq, HD], B=g.qkv_w[layer]
                    // [QKV_DIM_FULL, HD], C=g.qkv [seq, QKV_DIM_FULL].
                    // beta=0 (plain store). pfl_cutlass_small.
                    constexpr uint32_t QKV_DIM_FULL =
                        (MODEL_NUM_ATTN_H + 2 * MODEL_NUM_KV_H) * MODEL_HEAD_DIM;
                    tile_cutlass_gemm_small_lincomb(
                        g.rms_rope,
                        g.qkv_w + (size_t)op.layer * (size_t)QKV_DIM_FULL
                                                   * (size_t)MODEL_HIDDEN_DIM,
                        g.qkv,
                        /*M=*/(int)MODEL_SEQ_LEN,
                        /*K=*/(int)MODEL_HIDDEN_DIM,
                        /*N=*/(int)QKV_DIM_FULL,
                        /*beta=*/0.0f,
                        (char*)tile_smem_dyn, cta_id);
                    break;
                }
                case 11 /* CutlassGemmLayer { OProj } */: {
                    // o_proj + residual: A=g.attn_out [seq, HD],
                    // B=g.o_w[layer] [HD, HD], C=g.hidden_states [seq, HD].
                    // beta=1 (residual add). pfl_cutlass_small.
                    tile_cutlass_gemm_small_lincomb(
                        g.attn_out,
                        g.o_w + (size_t)op.layer * (size_t)MODEL_HIDDEN_DIM
                                                 * (size_t)MODEL_HIDDEN_DIM,
                        g.hidden_states,
                        /*M=*/(int)MODEL_SEQ_LEN,
                        /*K=*/(int)MODEL_HIDDEN_DIM,
                        /*N=*/(int)MODEL_HIDDEN_DIM,
                        /*beta=*/1.0f,
                        (char*)tile_smem_dyn, cta_id);
                    break;
                }
                case 12 /* CutlassGemmLayer { GateUp } */: {
                    // Two cutlass-small calls sharing A=g.rms_gate.
                    //   1. up   = rms_gate × up_w[layer]   → silu_out (β=0)
                    //   2. silu_out = silu(rms_gate × gate_w[layer]) * silu_out
                    //      via the LinearCombinationSiluMul epilogue
                    //      (which reads silu_out as `source`).
                    // Tried pfl_cutlass big 256x128x32: gate_up went
                    // 19.3 → 21.3 ms (down went 10.2 → 13.7). The big
                    // tile wins in the standalone fused kernel but
                    // loses here because all dispatch arms coexist in
                    // the same TU — adding the big tile bumps the
                    // megakernel's worst-case register footprint and
                    // hurts the other phases.
                    auto* b_up = g.up_w + (size_t)op.layer
                                              * (size_t)MODEL_INTERMEDIATE
                                              * (size_t)MODEL_HIDDEN_DIM;
                    auto* b_gate = g.gate_w + (size_t)op.layer
                                                  * (size_t)MODEL_INTERMEDIATE
                                                  * (size_t)MODEL_HIDDEN_DIM;
                    tile_cutlass_gemm_small_lincomb(
                        g.rms_gate, b_up, g.silu_out,
                        /*M=*/(int)MODEL_SEQ_LEN,
                        /*K=*/(int)MODEL_HIDDEN_DIM,
                        /*N=*/(int)MODEL_INTERMEDIATE,
                        /*beta=*/0.0f,
                        (char*)tile_smem_dyn, cta_id);
                    cooperative_groups::this_grid().sync();
                    tile_cutlass_gemm_small_silumul(
                        g.rms_gate, b_gate, g.silu_out,
                        /*M=*/(int)MODEL_SEQ_LEN,
                        /*K=*/(int)MODEL_HIDDEN_DIM,
                        /*N=*/(int)MODEL_INTERMEDIATE,
                        /*beta=*/1.0f, // unused by SiluMul
                        (char*)tile_smem_dyn, cta_id);
                    break;
                }
                case 13 /* CutlassGemmLayer { Down } */: {
                    // down + residual. pfl_cutlass_small (128x128x32).
                    // Tried big (256x128x32): down went 10.22 → 13.75 ms,
                    // probably because for down's M=1024, K=8192, N=2048
                    // shape, total_work_cta = 4 × 16 = 64 ops / 58 CTAs
                    // ≈ 1 per CTA — not enough work to amortize the
                    // bigger tile's shmem footprint and accumulator
                    // state. Small tile's 128 ops / 58 ≈ 2 per CTA
                    // packs better.
                    tile_cutlass_gemm_small_lincomb(
                        g.silu_out,
                        g.down_w + (size_t)op.layer
                                       * (size_t)MODEL_HIDDEN_DIM
                                       * (size_t)MODEL_INTERMEDIATE,
                        g.hidden_states,
                        /*M=*/(int)MODEL_SEQ_LEN,
                        /*K=*/(int)MODEL_INTERMEDIATE,
                        /*N=*/(int)MODEL_HIDDEN_DIM,
                        /*beta=*/1.0f,
                        (char*)tile_smem_dyn, cta_id);
                    break;
                }
                case PHASE_FLASHINFER_ATTN: {
                    // FlashInfer's BlockBatchPagedAttentionPersistent::Run
                    // is a wave-cooperative __device__ runner: each
                    // persistent CTA in the grid pulls its share of
                    // the layer's attention work via
                    // `params.work_indptr[blockIdx.y]`. The host plan
                    // (TwoStageHolisticPlan called once per launch in
                    // the Rust harness) populated the indirection
                    // arrays into a workspace buffer, and the per-
                    // layer Params records carry pointers into that
                    // workspace.
                    //
                    // Cast our shared shmem arena to FlashInfer's
                    // expected SharedStorage layout. We sized the
                    // launcher's `kSmemBytes` to be at least
                    // FI_SHARED_STORAGE_BYTES so the cast is in
                    // bounds.
                    auto& smem_storage =
                        *reinterpret_cast<FlashInferKTraits::SharedStorage*>(tile_smem_dyn);
                    FlashInferRunner::Run(rt.flashinfer_params[op.layer], &smem_storage);
                    break;
                }
                default: break;
            }
            // Stamp validation tick. Single-threaded.
            __syncthreads();
            if (prof) {
                t_outside = clock64();
                phase_clock[op.kernel_tag] += t_outside - t_in;
            }
            // Validation tick stamp. Wave-cooperative bindings (e.g.
            // FlashInferAttentionLayer) appear once per CTA in the
            // wave op stream, but the work is done once cooperatively
            // — so only cta_id 0 stamps the validation flag, otherwise
            // the tick counter overcounts and rt.flags[node_id] gets
            // a different value than the per-CTA count.
            // Wave-cooperative tags: FlashInfer attention (8), the
            // CutlassGemmLayer cutlass arms (10, 11, 13 — case 12 is
            // disabled, see comment there), and the wave-coop
            // hand-written gate_up wrapper (14). All replicated across
            // every CTA in the wave by the scheduler, so the
            // validation tick must only be stamped by cta_id 0.
            const bool wave_coop = (op.kernel_tag == PHASE_FLASHINFER_ATTN)
                                || (op.kernel_tag >= 10 && op.kernel_tag <= 14);
            if (tid == 0 && (!wave_coop || cta_id == 0)) {
                const uint32_t tick = atomicAdd(rt.tick_counter, 1u) + 1u;
                const uint32_t node_id = NODE_ID_FOR_OP[i];
                rt.flags[node_id] = tick;
            }
            __syncthreads();
        }

        // One grid barrier per wave.
        grid_barrier(rt.barrier_arrived, w);
    }

    // Flush per-kernel-tag clocks to gmem.
    if (prof) {
        const unsigned long long t_end = clock64();
        phase_clock[IDLE_SLOT] += t_end - t_outside;
        unsigned long long* row = rt.phase_clocks + (size_t)cta_id * NUM_CLOCK_SLOTS;
        #pragma unroll
        for (int p = 0; p < (int)NUM_CLOCK_SLOTS; ++p) {
            row[p] = phase_clock[p];
        }
    }
}

}  // namespace pfl_sched_{{ name }}

extern "C" void launch_scheduled_megakernel_{{ name }}(
    // Activation buffers (bf16, [seq, dim] row-major)
    void* hidden_states,
    void* rms_rope,
    void* qkv,
    void* q_post_rope,
    void* attn_out,
    void* rms_gate,
    void* silu_out,
    // Paged KV cache (bf16)
    void* k_cache,
    void* v_cache,
    // Block table + indptrs (i32)
    const int* prefill_kv_indices,
    const int* prefill_kv_indptr,
    const int* prefill_qo_indptr,
    // Norm weights (bf16, [num_layers, hidden_dim])
    void* attn_norm_w,
    void* mlp_norm_w,
    // GEMM weights (bf16)
    void* qkv_w,
    void* o_w,
    void* gate_w,
    void* up_w,
    void* down_w,
    float eps,
    float attn_scale,
    // Validation buffers
    unsigned int* flags,
    unsigned int* tick_counter,
    unsigned int* barrier_arrived,
    // Optional per-phase clock instrumentation. Pass nullptr to disable.
    // Layout when set: [num_ctas][NUM_CLOCK_SLOTS=10] u64.
    unsigned long long* phase_clocks,
    // FlashInfer per-layer PersistentParams array (device pointer,
    // length = MODEL_NUM_LAYERS). Built once per launch by the host
    // helper `build_flashinfer_attention_plan_for_megakernel` after
    // running `TwoStageHolisticPlan`. May be nullptr in test paths
    // that don't exercise the FlashInferAttentionLayer dispatch.
    void* flashinfer_params,
    cudaStream_t stream) {
    pfl_sched_{{ name }}::globals_t g{
        reinterpret_cast<__nv_bfloat16*>(hidden_states),
        reinterpret_cast<__nv_bfloat16*>(rms_rope),
        reinterpret_cast<__nv_bfloat16*>(qkv),
        reinterpret_cast<__nv_bfloat16*>(q_post_rope),
        reinterpret_cast<__nv_bfloat16*>(attn_out),
        reinterpret_cast<__nv_bfloat16*>(rms_gate),
        reinterpret_cast<__nv_bfloat16*>(silu_out),
        reinterpret_cast<__nv_bfloat16*>(k_cache),
        reinterpret_cast<__nv_bfloat16*>(v_cache),
        prefill_kv_indices,
        prefill_kv_indptr,
        prefill_qo_indptr,
        reinterpret_cast<__nv_bfloat16*>(attn_norm_w),
        reinterpret_cast<__nv_bfloat16*>(mlp_norm_w),
        reinterpret_cast<__nv_bfloat16*>(qkv_w),
        reinterpret_cast<__nv_bfloat16*>(o_w),
        reinterpret_cast<__nv_bfloat16*>(gate_w),
        reinterpret_cast<__nv_bfloat16*>(up_w),
        reinterpret_cast<__nv_bfloat16*>(down_w),
        eps,
        attn_scale,
    };
    pfl_sched_{{ name }}::SchedRuntime rt{
        flags,
        tick_counter,
        barrier_arrived,
        phase_clocks,
        reinterpret_cast<pfl_sched_{{ name }}::FlashInferParams*>(flashinfer_params),
    };
    // 2D grid with blockIdx.y = persistent CTA id; blockIdx.x = 0
    // (FlashInfer's cluster Q-split, which we always run at
    // cluster_size=1 — single-batch prefill). See the kernel-side
    // `cta_id = blockIdx.y` comment.
    dim3 grid(1, pfl_sched_{{ name }}::NUM_CTAS);
    // CTA size = max(256, FlashInfer KTraits::NUM_THREADS). The
    // existing hand-written tile bodies were written for 256 threads
    // and gate higher tids to warp 0; FlashInfer's runner needs at
    // least KTraits::NUM_THREADS to populate its per-warp Q/K/V
    // fragments. Take the max so both paths are happy.
    dim3 block(pfl_sched_{{ name }}::MEGAKERNEL_NUM_THREADS);

    // Dynamic shared memory size: max of (the existing tile arena),
    // (FlashInfer's per-CTA SharedStorage footprint), and (the
    // CUTLASS pfl_cutlass + pfl_cutlass_small SharedStorage union
    // footprints). Same arena backs all of them — the wave-cooperative
    // dispatch only runs one wave at a time, so the layouts don't
    // overlap in time. Capped against
    // TARGET_MAX_DYNAMIC_SHMEM_BYTES via a static_assert below
    // (rendered from `TargetProfile::max_dynamic_shmem_bytes`).
    constexpr size_t kCutlassBigShmem = sizeof(::pfl_cutlass::SharedStorage);
    constexpr size_t kCutlassSmallShmem = sizeof(::pfl_cutlass_small::SharedStorage);
    constexpr size_t kMaxAB =
        pfl_sched_{{ name }}::TILE_SHMEM_BYTES > pfl_sched_{{ name }}::FI_SHARED_STORAGE_BYTES
            ? pfl_sched_{{ name }}::TILE_SHMEM_BYTES
            : pfl_sched_{{ name }}::FI_SHARED_STORAGE_BYTES;
    constexpr size_t kMaxABC = kMaxAB > kCutlassBigShmem ? kMaxAB : kCutlassBigShmem;
    constexpr size_t kSmemBytes = kMaxABC > kCutlassSmallShmem ? kMaxABC : kCutlassSmallShmem;
    static_assert(kSmemBytes <= pfl_sched_{{ name }}::TARGET_MAX_DYNAMIC_SHMEM_BYTES,
                  "megakernel SharedStorage exceeds target.max_dynamic_shmem_bytes");

    // Opt the kernel into the larger dynamic shmem carveout. Required
    // any time `kSmemBytes` exceeds the default 48 KiB ceiling on
    // sm_80+, harmless when it doesn't.
    auto attr_err = cudaFuncSetAttribute(
        (const void*)pfl_sched_{{ name }}::scheduled_megakernel_{{ name }},
        cudaFuncAttributeMaxDynamicSharedMemorySize,
        (int)kSmemBytes);
    if (attr_err != cudaSuccess) {
        printf("scheduled_megakernel_{{ name }}: cudaFuncSetAttribute failed: %s\n",
               cudaGetErrorString(attr_err));
        return;
    }

    // The grid-barrier counter is cumulative across waves, so it must be
    // reset to 0 before every launch — otherwise the second launch's
    // wave-0 barrier sees the counter already past its target and exits
    // without actually synchronizing, racing the rest of the kernel.
    // Async on the same stream → effectively free.
    cudaMemsetAsync(barrier_arrived, 0, sizeof(unsigned int), stream);

    // Cooperative launch — the megakernel uses `grid_barrier()` (a
    // gmem-flag spin-loop) for inter-wave synchronization, which only
    // works correctly when ALL the launched CTAs are guaranteed to be
    // resident concurrently. cudaLaunchCooperativeKernel enforces
    // that constraint at launch time and is also what FlashInfer's
    // `cg::this_grid().sync()` requires (sub-step 3c).
    void* args[] = { &g, &rt };
    auto launch_err = cudaLaunchCooperativeKernel(
        (const void*)pfl_sched_{{ name }}::scheduled_megakernel_{{ name }},
        grid, block, args, kSmemBytes, stream);
    if (launch_err != cudaSuccess) {
        printf("scheduled_megakernel_{{ name }}: cudaLaunchCooperativeKernel failed: %s\n",
               cudaGetErrorString(launch_err));
    }
}

extern "C" unsigned int scheduled_megakernel_{{ name }}_num_nodes() {
    return pfl_sched_{{ name }}::NUM_NODES;
}

extern "C" unsigned int scheduled_megakernel_{{ name }}_num_ctas() {
    return pfl_sched_{{ name }}::NUM_CTAS;
}

extern "C" unsigned int scheduled_megakernel_{{ name }}_num_waves() {
    return pfl_sched_{{ name }}::NUM_WAVES;
}
