// SPDX-License-Identifier: Apache-2.0
//! Correctness test: compare TK kernel output against golden reference logits.
//!
//! Golden files are pre-generated by `gen_golden` binary (runs CudaWorker).
//! This test only needs the TK backend — no CudaWorker dependency at test time.
//!
//! Run on a GPU pod with:
//!   cargo test -p vllm-tk-static --features cuda --test correctness -- --ignored

#![cfg(feature = "cuda")]
#![allow(unsafe_op_in_unsafe_fn)]

use std::path::{Path, PathBuf};

use half::f16;
use vllm_cuda::dtype::DType;
use vllm_cuda::tensor::GpuTensor;
use vllm_cuda::{OwnedTensor, driver};
use vllm_tk::scheduler::PrefillSeq;
use vllm_tk::worker::{TkWorker, TkWorkerConfig};

// ── Golden file loading ────────────────────────────────────────────────

#[derive(Debug)]
struct GoldenData {
    model_id: String,
    input_ids: Vec<u32>,
    vocab_size: usize,
    top1_token_id: usize,
    top_k_logits: Vec<(usize, f32)>, // (token_id, logit)
}

fn load_golden(model_id: &str) -> GoldenData {
    let safe_name = model_id.replace('/', "__");
    let golden_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("golden");
    let path = golden_dir.join(format!("{safe_name}.json"));
    let data: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&path).unwrap_or_else(|_| {
            panic!(
                "Golden file not found: {}. Run `cargo run -p vllm-tk-static --features cuda --bin gen_golden --release` first.",
                path.display()
            )
        }))
        .expect("parse golden JSON");

    let input_ids: Vec<u32> = data["input_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as u32)
        .collect();

    let top_k_logits: Vec<(usize, f32)> = data["top_k_logits"]
        .as_array()
        .unwrap()
        .iter()
        .map(|entry| {
            let id = entry["token_id"].as_u64().unwrap() as usize;
            let logit = entry["logit"].as_f64().unwrap() as f32;
            (id, logit)
        })
        .collect();

    GoldenData {
        model_id: data["model_id"].as_str().unwrap().to_string(),
        input_ids,
        vocab_size: data["vocab_size"].as_u64().unwrap() as usize,
        top1_token_id: data["top1_token_id"].as_u64().unwrap() as usize,
        top_k_logits,
    }
}

// ── Helpers ────────────────────────────────────────────────────────────

fn resolve_model_dir(model_id: &str) -> PathBuf {
    let api = hf_hub::api::sync::ApiBuilder::from_env()
        .build()
        .expect("hf_hub API");
    let repo = api.model(model_id.to_string());
    let config_path = repo.get("config.json").expect("download config.json");
    config_path.parent().unwrap().to_path_buf()
}

fn parse_llama_config(model_dir: &Path) -> vllm_cuda::model::llama::LlamaConfig {
    let config_path = model_dir.join("config.json");
    let data: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&config_path).expect("read config.json"))
            .expect("parse config.json");

    let hidden_size = data["hidden_size"].as_u64().unwrap() as usize;
    let num_attention_heads = data["num_attention_heads"].as_u64().unwrap() as usize;
    let num_kv_heads = data
        .get("num_key_value_heads")
        .and_then(|v| v.as_u64())
        .unwrap_or(num_attention_heads as u64) as usize;
    let head_dim = data
        .get("head_dim")
        .and_then(|v| v.as_u64())
        .map(|v| v as usize)
        .unwrap_or(hidden_size / num_attention_heads);

    let llama3_rope_scaling = data.get("rope_scaling").and_then(|rs| {
        let rope_type = rs
            .get("rope_type")
            .or_else(|| rs.get("type"))
            .and_then(|v| v.as_str())?;
        if rope_type != "llama3" {
            return None;
        }
        Some(vllm_cuda::model::llama::Llama3RopeScaling {
            factor: rs.get("factor")?.as_f64()?,
            low_freq_factor: rs
                .get("low_freq_factor")
                .and_then(|v| v.as_f64())
                .unwrap_or(1.0),
            high_freq_factor: rs
                .get("high_freq_factor")
                .and_then(|v| v.as_f64())
                .unwrap_or(4.0),
            original_max_position_embeddings: rs
                .get("original_max_position_embeddings")
                .and_then(|v| v.as_u64())
                .unwrap_or(8192) as usize,
        })
    });

    vllm_cuda::model::llama::LlamaConfig {
        hidden_size,
        num_attention_heads,
        num_kv_heads,
        num_hidden_layers: data["num_hidden_layers"].as_u64().unwrap() as usize,
        intermediate_size: data["intermediate_size"].as_u64().unwrap() as usize,
        vocab_size: data["vocab_size"].as_u64().unwrap() as usize,
        max_position_embeddings: data
            .get("max_position_embeddings")
            .and_then(|v| v.as_u64())
            .unwrap_or(4096) as usize,
        rms_norm_eps: data
            .get("rms_norm_eps")
            .and_then(|v| v.as_f64())
            .unwrap_or(1e-5) as f32,
        rope_theta: data
            .get("rope_theta")
            .and_then(|v| v.as_f64())
            .unwrap_or(10000.0),
        head_dim,
        tie_word_embeddings: data
            .get("tie_word_embeddings")
            .and_then(|v| v.as_bool())
            .unwrap_or(false),
        llama3_rope_scaling,
    }
}

unsafe fn gpu_bf16_to_f32(
    ptr: *const u8,
    numel: usize,
    stream: cudarc::driver::sys::CUstream,
) -> Vec<f32> {
    let mut host_bf16 = vec![0u16; numel];
    driver::memcpy_dtoh_async(host_bf16.as_mut_ptr() as *mut u8, ptr, numel * 2, stream)
        .expect("dtoh logits");
    driver::stream_synchronize(stream).expect("sync");
    host_bf16
        .iter()
        .map(|&bits| f16::from_bits(bits).to_f32())
        .collect()
}

// ── TK Worker prefill ──────────────────────────────────────────────────

fn tk_worker_prefill(
    model_dir: &Path,
    config: &vllm_cuda::model::llama::LlamaConfig,
    input_ids: &[u32],
) -> Vec<f32> {
    let num_tokens = input_ids.len();
    let num_blocks = 64;

    let mut worker = TkWorker::new(TkWorkerConfig {
        model_path: model_dir.to_string_lossy().to_string(),
        dtype: "bfloat16".to_string(),
        hf_token: None,
        device_id: 0,
        max_num_batched_tokens: 512,
        gpu_memory_utilization: 0.9,
        sm_count: 0,
    });

    worker.init_device().expect("init_device");
    worker
        .load_model(model_dir, config.clone())
        .expect("load_model");
    worker.initialize_cache(num_blocks).expect("init_cache");
    worker.ensure_ctx().expect("ensure_ctx");

    let stream = worker.stream().expect("stream");

    let input_bytes = num_tokens * 4;
    let input_ptr = unsafe { driver::mem_alloc(input_bytes).expect("alloc input_ids") };
    unsafe {
        driver::memcpy_htod_async(
            input_ptr,
            input_ids.as_ptr() as *const u8,
            input_bytes,
            stream,
        )
        .expect("upload input_ids");
    }
    let input_tensor = unsafe { GpuTensor::new(input_ptr, &[num_tokens], DType::U32) };

    let positions: Vec<u32> = (0..num_tokens as u32).collect();
    let pages_needed = num_tokens.div_ceil(64);
    let block_table: Vec<usize> = (0..pages_needed).collect();
    let prefill_seqs = vec![PrefillSeq {
        chunk_len: num_tokens,
        extend_offset: 0,
    }];

    unsafe {
        worker.launch_prefill(
            input_tensor,
            &prefill_seqs,
            &[&block_table[..]],
            &positions,
            &[num_tokens],
            num_tokens,
        );
    }

    let vocab_size = config.vocab_size;
    let logits_gpu = worker.logits_tensor().expect("logits_tensor");
    let all_logits =
        unsafe { gpu_bf16_to_f32(logits_gpu.as_ptr::<u8>(), num_tokens * vocab_size, stream) };

    unsafe {
        driver::mem_free(input_ptr).ok();
    }

    all_logits[(num_tokens - 1) * vocab_size..].to_vec()
}

// ── Tests ──────────────────────────────────────────────────────────────

fn run_golden_comparison(model_id: &str) {
    let golden = load_golden(model_id);
    let model_dir = resolve_model_dir(model_id);
    let config = parse_llama_config(&model_dir);

    eprintln!("Model: {model_id}");
    eprintln!(
        "  hidden_size={}, layers={}, vocab={}",
        config.hidden_size, config.num_hidden_layers, config.vocab_size
    );

    let tk_logits = tk_worker_prefill(&model_dir, &config, &golden.input_ids);
    assert_eq!(tk_logits.len(), golden.vocab_size, "vocab size mismatch");

    // Top-1
    let tk_top1 = tk_logits
        .iter()
        .enumerate()
        .max_by(|a, b| a.1.partial_cmp(b.1).unwrap())
        .unwrap()
        .0;

    eprintln!(
        "  Golden top-1: token {} (logit={:.4})",
        golden.top1_token_id, golden.top_k_logits[0].1
    );
    eprintln!(
        "  TK     top-1: token {tk_top1} (logit={:.4})",
        tk_logits[tk_top1]
    );

    // Compare top-k logit diffs
    let mut max_topk_diff: f32 = 0.0;
    for &(token_id, golden_logit) in &golden.top_k_logits {
        let tk_logit = tk_logits[token_id];
        let diff = (golden_logit - tk_logit).abs();
        max_topk_diff = max_topk_diff.max(diff);
    }
    eprintln!("  max top-k logit diff: {max_topk_diff:.6}");

    // Top-5 comparison
    let mut tk_sorted: Vec<(usize, f32)> = tk_logits.iter().copied().enumerate().collect();
    tk_sorted.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
    eprintln!("  TK top-5:");
    for (id, val) in &tk_sorted[..5] {
        eprintln!("    token {id}: {val:.4}");
    }
    eprintln!("  Golden top-5:");
    for (id, val) in &golden.top_k_logits[..5] {
        eprintln!("    token {id}: {val:.4}");
    }

    assert_eq!(
        tk_top1, golden.top1_token_id,
        "Top-1 token mismatch: TK={tk_top1}, Golden={}",
        golden.top1_token_id,
    );
    assert!(
        max_topk_diff < 1.0,
        "max top-k logit diff too large: {max_topk_diff:.6} (expected < 1.0)"
    );

    eprintln!("  PASSED");
}

#[test]
#[ignore]
fn test_tk_vs_golden_llama_1b() {
    run_golden_comparison("unsloth/Llama-3.2-1B-Instruct");
}

#[test]
#[ignore]
fn test_tk_vs_golden_llama_3b() {
    run_golden_comparison("unsloth/Llama-3.2-3B-Instruct");
}

#[test]
#[ignore]
fn test_tk_vs_golden_llama_8b() {
    run_golden_comparison("unsloth/Llama-3.1-8B-Instruct");
}

/// Standalone CudaWorker golden file regeneration test.
/// Use this to verify the CudaWorker path works before generating golden files.
#[test]
#[ignore]
fn test_cuda_worker_prefill_1b() {
    use vllm_cuda::device::GpuDevice;
    use vllm_cuda::kv_cache::KvCachePool;
    use vllm_cuda::model::llama::LlamaForCausalLM;
    use vllm_cuda::weights::GpuWeights;

    let model_id = "unsloth/Llama-3.2-1B-Instruct";
    let model_dir = resolve_model_dir(model_id);
    let config = parse_llama_config(&model_dir);

    let mut input_ids = vec![0u32; 128];
    input_ids[0] = 128000;
    input_ids[1] = 9906;
    input_ids[2] = 1917;

    let num_tokens = input_ids.len();
    let block_size = 16;
    let num_blocks = 64;

    let mut device = GpuDevice::new(0).expect("GpuDevice");
    let mut weights = GpuWeights::from_dir(&model_dir, device.compute_stream).expect("GpuWeights");
    let model = LlamaForCausalLM::load(&mut weights, &config, DType::BF16, &device).expect("load");

    let kv_cache = unsafe {
        KvCachePool::new(
            config.num_hidden_layers,
            num_blocks,
            block_size,
            config.num_kv_heads,
            config.head_dim,
            DType::BF16,
        )
        .expect("KvCachePool")
    };

    let positions: Vec<u32> = (0..num_tokens as u32).collect();
    let slot_mapping: Vec<i64> = (0..num_tokens as i64).collect();
    let cu_seqlens_q = vec![0i32, num_tokens as i32];
    let seqused_k = vec![num_tokens as i32];
    let blocks_needed = num_tokens.div_ceil(block_size);
    let block_table: Vec<i32> = (0..blocks_needed as i32).collect();

    unsafe {
        let gpu_input_ids = {
            let t = device.caching.alloc_tensor(&[num_tokens], DType::U32);
            driver::memcpy_htod_async(
                t.as_gpu_tensor().as_mut_ptr::<u8>(),
                input_ids.as_ptr() as *const u8,
                num_tokens * 4,
                device.compute_stream,
            )
            .expect("h2d");
            t
        };
        let gpu_positions = {
            let t = device.caching.alloc_tensor(&[num_tokens], DType::U32);
            driver::memcpy_htod_async(
                t.as_gpu_tensor().as_mut_ptr::<u8>(),
                positions.as_ptr() as *const u8,
                num_tokens * 4,
                device.compute_stream,
            )
            .expect("h2d");
            t
        };
        let gpu_slot_mapping = {
            let t = device.caching.alloc_tensor(&[num_tokens], DType::I64);
            driver::memcpy_htod_async(
                t.as_gpu_tensor().as_mut_ptr::<u8>(),
                slot_mapping.as_ptr() as *const u8,
                num_tokens * 8,
                device.compute_stream,
            )
            .expect("h2d");
            t
        };
        let gpu_cu = {
            let t = device.caching.alloc_tensor(&[2], DType::I32);
            driver::memcpy_htod_async(
                t.as_gpu_tensor().as_mut_ptr::<u8>(),
                cu_seqlens_q.as_ptr() as *const u8,
                8,
                device.compute_stream,
            )
            .expect("h2d");
            t
        };
        let gpu_seqused = {
            let t = device.caching.alloc_tensor(&[1], DType::I32);
            driver::memcpy_htod_async(
                t.as_gpu_tensor().as_mut_ptr::<u8>(),
                seqused_k.as_ptr() as *const u8,
                4,
                device.compute_stream,
            )
            .expect("h2d");
            t
        };
        let mut gpu_bt = {
            let t = device.caching.alloc_tensor(&[blocks_needed], DType::I32);
            driver::memcpy_htod_async(
                t.as_gpu_tensor().as_mut_ptr::<u8>(),
                block_table.as_ptr() as *const u8,
                blocks_needed * 4,
                device.compute_stream,
            )
            .expect("h2d");
            t
        };
        gpu_bt.reshape(&[1, blocks_needed], DType::I32);

        let logits_owned = model.forward(
            gpu_input_ids.view(),
            gpu_positions.view(),
            gpu_slot_mapping.view(),
            gpu_cu.view(),
            gpu_seqused.view(),
            gpu_bt.view(),
            num_tokens,
            num_tokens,
            &kv_cache,
            &mut device,
            None,
        );

        let vocab_size = config.vocab_size;
        let all_logits = gpu_bf16_to_f32(
            logits_owned.as_gpu_tensor().as_ptr::<u8>(),
            num_tokens * vocab_size,
            device.compute_stream,
        );

        let last_logits = &all_logits[(num_tokens - 1) * vocab_size..];
        let top1 = last_logits
            .iter()
            .enumerate()
            .max_by(|a, b| a.1.partial_cmp(b.1).unwrap())
            .unwrap();
        eprintln!("CudaWorker top-1: token {} (logit={:.4})", top1.0, top1.1);
    }
}
